### ISSUE TITLE
Encoding java.lang.Class[T] and Vector[_ <: Object]

### ISSUE THREAD

**Issue by CasterKKK** [circe/circe#1014]
When writing a RPC framework, we need to codec the Request and Response class, here is my Request class:
```scala
trait Servicable {} // a marking Trait for the services

case class Request[T <: Servicable](
  id: String, 
  serviceClazz: Class[T],
  methodName: String, 
  paramTypes: Vector[Class[_]], 
  params: Vector[_ <: Object]
)
```

So I wonder how to serialize/deserialize the classes like this one? The main point is that circe seems not to provide Codec for ` java.lang.Class[T]`, and the ser/des of dynamic generic collection objects like `Vector[_ <: Object]` is also difficult.

Anybody can give me a hand?

**Comment by travisbrown** [comment]
The library isn't really designed to handle use cases like this. You can pretty easily define an encoder / decoder pair for `Class[_]` using `Class.forName` and `Class#getCanonicalName` or whatever, but circe-core doesn't provide these off the shelf. Similarly it's possible to write instances for `Vector[_ <: Object]`, but they're inherently unsafe and not provided by the library itself (see e.g. [this comment](https://github.com/circe/circe/issues/216#issuecomment-191730128) for some additional explanation).
