### ISSUE TITLE
Snake-case and kebab-case transformations are slow.

### ISSUE THREAD

**Issue by waiter-melon** [circe/circe#1021]
Snake-case and kebab-case transformations are slow.

There is a linked pull request on this topic (https://github.com/circe/circe/pull/940) that still has to be accepted.
- That solution is about **pre**-compiling regular expressions
- This solution is about using a fast implementation which can improve the performances x6 at least.

I've tried out [jsoniter-scala](https://github.com/plokhotnyuk/jsoniter-scala) but it does not support Scala.js at the moment.

Benchmarks:

Current:
`[info] KeyCasingBenchmark.snakeCase thrpt 10 ~ 829 556 ± 59956.575 ops/s`
With regular expressions pre-compilation:
`[info] KeyCasingBenchmark.snakeCase thrpt 10 ~ 1 861 369 ± 52228.706 ops/s`
With Jsoniter-Scala:
`[info] KeyCasingBenchmark.snakeCase thrpt 10 ~ 10 457 001 ± 52228.706 ops/s`

Please feel free to suggest another solution/library.

Thanks

**Comment by plokhotnyuk** [comment]
@waiter-melon these functions uses only Java String API and should work with Scala.js.

Feel free to copy code from jsoniter-scala and adopt to your requirements. It's license is compatible with Circe's Apache License just need to leave "License and copyright notice".

**Comment by travisbrown** [comment]
Fixed in #940 / #1035.
