### ISSUE TITLE
Printer with key ordering

### ISSUE THREAD

**Issue by koterpillar** [circe/circe#1045]
#556 talks about key ordering in `JsonObject`. People still want this, but I think merely adding another `Printer` would be sufficient to output keys in sorted order without changing the actual JSON objects passed around.

Proposal:
* Add a Printer that sorts object keys when outputting the values.
* Add `.spaces2OrderedKeys`, `spaces4OrderedKeys` and `noSpacesOrderedKeys` to invoke the key-sorting printer.
* No changes to `JsonObject` or anything else.

I'm prepared to make a PR implementing the above if it's deemed a good way forward.

**Comment by travisbrown** [comment]
Sounds reasonable to me, thanks!
