### ISSUE TITLE
Error message for control characters in strings contains an extra quotation mark in 0.11.0

### ISSUE THREAD

**Issue by bergmark** [circe/circe#1046]
This assertion succeeds in 0.11.0, note the quotation mark inside the apostrophes.

```
object Main extends App {
  val e = io.circe.parser.decode[String](""""\u0000"""").left.get.getMessage
  assert(
    e ==
    """control char (0) in string got '\u0000"' (line 1, column 2)""",
    e
  )
}
```

In 0.10.1 this string matches instead `"""control char (0) in string got \u0000 (line 1, column 2)"""`

I think the change to wrap in `'` is fine, but I'm not sure where the `"` is coming from.

**Comment by travisbrown** [comment]
Thanks for the report! I believe this is a bug in Jawn 0.14.0, probably introduced in [#129](https://github.com/typelevel/jawn/pull/129):

```scala
scala> import org.typelevel.jawn.{NullFacade, Parser}
import org.typelevel.jawn.{NullFacade, Parser}

scala> Parser.parseFromString(""""\u0000"""")(NullFacade)
res0: scala.util.Try[Unit] = Failure(org.typelevel.jawn.ParseException: control char (0) in string got '?"' (line 1, column 2))
```

I'll leave this issue open until we get it fixed, but do you mind opening an issue over on the Jawn repo, @bergmark?

**Comment by bergmark** [comment]
Whoops, I forgot about creating the issue, sorry. Thanks for doing it.

**Comment by bergmark** [comment]
Thanks for fixing this! I know have this passing assertion
```
getErrors[String](""""\u0000"""") shouldEqual Set("Parsing failure: control char (0) in string got '\u0000...' (line 1, column 2)")
```
