### ISSUE TITLE
A circe-spire module?

### ISSUE THREAD

**Issue by LukaJCB** [circe/circe#1051]
It'd be nice to be able encode and decode spire numeric types like `SafeLong`, `Rational`, `UInt` or `Algebraic`. I have implemented some of them in a recent project and could contribute them if wanted :)

**Comment by travisbrown** [comment]
Sounds good to me! I think I'd prefer a new circe org repo rather than a module here, since e.g. Spire doesn't have 2.13.0-Mx artifacts yet, etc.

**Comment by LukaJCB** [comment]
Cool! What's the best way to get started on that? You create the repo and I'll make a PR? :)

**Comment by travisbrown** [comment]
Yep, just sent an invite: https://github.com/circe/circe-spire

**Comment by travisbrown** [comment]
I'd recommend using something like circe-bson as a template (and adding the repo to scala-steward's list) to keep some kind of consistency, but definitely not required: https://github.com/circe/circe-bson

**Comment by LukaJCB** [comment]
Done! https://github.com/circe/circe-spire/commits/master

**Comment by travisbrown** [comment]
Looks good to me (I noticed one mention of circe-bson left over in the `build.sbt`, but can open a PR for it later). I also just tried to enable Travis CI and it's telling me "You don't have sufficient rights to enable this repo on Travis. Please contact the admin to enable it or to receive admin rights yourself."—even though I created the repo myself. I'll try to get that worked out now.

**Comment by travisbrown** [comment]
P.S. Travis CI is now working, and I opened https://github.com/circe/circe-spire/pull/2.
