### ISSUE TITLE
Missing java 8 java.time instances: DayOfWeek and Month

### ISSUE THREAD

**Issue by nafg** [circe/circe#1059]

**Comment by travisbrown** [comment]
This is an intentional omission, since we don't typically provide instances where there's not a clear encoding, and these can reasonably be encoded either as integers or as a (locale-determined) string. If you have a proposal for a (possibly non-implicit) way to include these, though, I'd be happy to review.

**Comment by nafg** [comment]
I would do it as an integer.

I can hear that having an implicit instance can be an issue if you have a
case where you want to encode it differently but I don't see why that's
specific to these. For instance what if I want to serialize a LocalTime in
a format other than iso. You would import or define a different implicit in
the particular scope.

I think using an integer for month and day of week is pretty standard
(although whether it should be 0 based or 1 based isn't but java.time's
convention would be used).

Another solution to making encodings flexible is to put them in a trait, if
in my app I use a different encoding I can subclass the trait with my own
object and override one encoding.

**Comment by travisbrown** [comment]
Closing as `won't-fix` for now. If someone wants to propose non-implicit helper methods (similar to what we have for changing the format for `LocalTime`) I'd be happy to review, but I don't personally think it's worth the added complexity, given that defining these instances by mapping / contra-mapping `Int` instances is pretty straightforward.
