### ISSUE TITLE
Need to import java8 time instances when using @JsonCodec annotation

### ISSUE THREAD

**Issue by carwynellis** [circe/circe#1075]
I'm not sure if this is by design or not, but when using the `@JsonCodec` annotation to handle semi-automatic derivation of encoders and decoders, I need to import the java8 time instances manually if the case class is using a java8 date time type.

For example 

```scala
import java.time.LocalDate
import io.circe.generic.JsonCodec
import io.circe.java8.time._ // This import will appear as unused in my IDE

@JsonCodec
case class Foo(date: Option[LocalDate])
```

Without the import, compilation will fail, and it's not too obvious why. Also my IDE will flag the import as unused since it can't see that it's being used, which may surprise someone else who might be tempted to remove it.

**Comment by travisbrown** [comment]
What Scala and circe version (this is expected on 2.11, for example, where circe-core doesn't provide these instances)? Can you derive an instance with e.g. `io.circe.generic.semiauto.deriveEncoder[Foo]` without the import? Does a plain old `Encoder[LocalDate]` compile without the import?

**Comment by carwynellis** [comment]
We're running 0.9.3 on scala 2.12 and you're up to 0.11.1. I've tried 0.11.1 and it works without the explicit java8 time import so I'll close this now non-issue.
