### ISSUE TITLE
Scala Native Support

### ISSUE THREAD

**Issue by sorenbug** [circe/circe#1077]
Currently seems to be blocked by https://github.com/typelevel/cats/issues/1549?

(Primarily made this issue so I can link to it from other projects that I'd like to see a Scala Native discussion on.)

**Comment by travisbrown** [comment]
Thanks @sorenbug, but yes, this is blocked for the foreseeable future.

**Comment by travisbrown** [comment]
Just for the record: I'm planning to drop 2.11 support in an upcoming release and will not include Scala Native support (even if Cats eventually does) until it works for more recent Scala versions.

**Comment by sorenbug** [comment]
Sounds good.

**Comment by travisbrown** [comment]
Closing for now, we can revisit if / when Cats supports Scala Native and Scala Native supports a modern Scala version.

**Comment by joroKr21** [comment]
> Closing for now, we can revisit if / when Cats supports Scala Native and Scala Native supports a modern Scala version.

They do!

**Comment by sideeffffect** [comment]
FYI, Scala Native support has been merged to jawn https://github.com/typelevel/jawn/pull/340

**Comment by armanbilge** [comment]
Scala Native support is landing in https://github.com/circe/circe/pull/2017.
