### ISSUE TITLE
Consider adding Json Pattern Functor

### ISSUE THREAD

**Issue by Baccata** [circe/circe#1088]
@travisbrown wondering if you'd agree to the addition in `circe-core` of a Pattern Functor version of circe's Json ADT,  which is required when working with recursion-schemes. I've been using the code below in a few occurrences, maybe it'd be worth PR-ing ? 

```scala
sealed trait JsonF[+A]

case object JNullF extends JsonF[Nothing]
case class JBooleanF(b: Boolean) extends JsonF[Nothing]
case class JNumberF(n: JsonNumber)  extends JsonF[Nothing]
case class JStringF(s: String) extends JsonF[Nothing]
case class JArrayF[A](value: Vector[A]) extends JsonF[A]
case class JObjectF[A](fields: Vector[(String, A)]) extends JsonF[A]

object JsonF {
   implicit val jsonTraverse : cats.Traverse[JsonF] = ??? 
   val unfold : Json => JsonF[Json] = ???
   val fold : JsonF[Json] => Json = ???
} 
```

**Comment by travisbrown** [comment]
@Baccata Yes, this is something I've played with and have been meaning to add for a while—I really wanted to land the circe-algebra work first, but I don't think that's necessary. I'd merge a new modules adding this today, and would be happy to discuss where it would fit in core.

**Comment by travisbrown** [comment]
(Thanks for bringing it up.)

**Comment by Baccata** [comment]
> I'd merge a new modules adding this today, and would be happy to discuss where it would fit in core. 

Your turf, your rules 😄 Was thinking of core as it wouldn't add any extra dependency, but if a new module is a better fit, happy with that as well (afk this week-end but should be able to PR it monday or tuesday)

**Comment by Baccata** [comment]
A bit later than I wanted here's the PR : https://github.com/circe/circe/pull/1092/

**Comment by travisbrown** [comment]
Done in #1092 (and the follow-up #1094).
