### ISSUE TITLE
Json.fromValues rename to Json.fromIterable to Json.fromCollection

### ISSUE THREAD

**Issue by ratoshniuk** [circe/circe#1090]
What do you think to make a rename of this method? I think it would be better to understand that this `fromIterable` wraps into json array instead of `fromValues`...

**Comment by travisbrown** [comment]
I don't understand the contrast you're suggesting with `Json.fromValues`? `JsonObject.fromIterable` is a semi-internal method (as the "provided for optimization" suggests) that's really just for cases where the more general `fromFoldable` (or just `apply`) have too much overhead.
