### ISSUE TITLE
Fix fold-related naming

### ISSUE THREAD

**Issue by travisbrown** [circe/circe#1097]
The fact that the `fold` method on `Json` is called `fold` has bothered me for years. The name is an inheritance from Argonaut, and it's inaccurate (or at least misleading), since this thing isn't really a catamorphism—it's more like what Buchlovsky calls [the "external" version](http://www.computer-science.birmingham.ac.uk/~hxt/research/mfps-visitors.pdf) of the visitor pattern.

We could change `fold` (and `Json.Folder`) to look something like this:

```scala
final def fold[X](
  jsonNull: => X,
  jsonBoolean: Boolean => X,
  jsonNumber: JsonNumber => X,
  jsonString: String => X,
  jsonArray: Iterable[X] => X,
  jsonObject: Iterable[(String, X)] => X
): X
```

…and then the name would make more sense. The problem is that in both circe and Argonaut `fold` is recommended as an alternative to pattern matching on constructors, in which case the external visitor is a better fit, and in my experience a real fold / internal visitor wouldn't work for many of the things I need to do with `fold` or `Json.Folder`—it's just not expressive enough to write something like the `Folder` we use in `Printer`, for example.

So we definitely need to keep the current `fold` and `Folder`, we just might want to change the names, and we might want to add the internal visitor version (since it's a little more elegant for the operations that it supports).

I'm interested in what other people think:

1. Should we rename `fold`?
2. Should we add a new method with the signature above? If so, what should we call it?

I know renaming something like this is annoying, but we can do it through a deprecation cycle, and I don't want to be stuck with inaccurate or misleading names in 1.0 just because I didn't want to inconvenience people a little before then.

**Comment by travisbrown** [comment]
For what it's worth, I think I'd currently answer something like this:

1. Yes, call it `transform` and rename `Folder` to `Visitor`.
2. Not now.

**Comment by ritschwumm** [comment]
are there precedents for `transform`, or why did you choose that name? just curious...

**Comment by travisbrown** [comment]
@ritschwumm Honestly I just made it up to suggest _something_. Something like `match` or `reduce` would be better but I'm not making everyone write backticks all over and "reduce" sounds too much like "catamorphism" again.

Any ideas for something better would be very much appreciated.

**Comment by LPTK** [comment]
> Any ideas for something better would be very much appreciated.

Perhaps `foldStep`, as it performs one step of a `fold`. Or `peel`/`unwrap` as it detaches the outer layer of the structure. A nice one might be `inspect`, as it's a way to look at ("inspect") the outer structure, but it's less specific (there is more than one way to inspect a structure).

**Comment by travisbrown** [comment]
@LPTK Thanks, I like both `foldStep` and `inspect` better than any of my previous current candidates!

**Comment by gatorcse** [comment]
`visit`?

**Comment by travisbrown** [comment]
@gatorcse But that feels reversed as a method on `Json`, since it's being visited by the argument.

**Comment by gatorcse** [comment]
Well since it's being visited by a visitor, how about `welcome` or `invite`?

j/k, those are terrible names.

**Comment by hamnis** [comment]
Closing in cleanup run, If anyone cares about this, please comment and I'll reopen.
