### ISSUE TITLE
asNumber always returns None

### ISSUE THREAD

**Issue by vincenzobaz** [circe/circe#1100]
I am encountering a weird behavior while transforming `JsonNumber` into `Double`

In particular:
```scala
Json("-22058000.00").flatMap(_.asNumber) // Gives None
Json("-22058000.00").flatMap(_.asString).map(_.toDouble) // Gives Some(-2.2058E7)
```

Am I doing something wrong?

**Comment by travisbrown** [comment]
Can you give a complete working example? `Json(...)` isn't valid code, and the following works just fine:

```scala
scala> io.circe.jawn.parse("-22058000.00").toOption.flatMap(_.asNumber)
res0: Option[io.circe.JsonNumber] = Some(-22058000.00)
```

I'd guess that you're calling `asNumber` on a `Json` value that represents a JSON string, but without actual compiling code who knows.

**Comment by vincenzobaz** [comment]
I am sorry it was the end of the day and the tracking down that bug in my code was quite frustrating.

You are right, the API I am requesting returns numbers as JSON strings.
