### ISSUE TITLE
How to continuous json parse

### ISSUE THREAD

**Issue by shogo-takao** [circe/circe#1114]
Hi.
I want to know how to parse JSON.
I am trying to parse json in scala.
But I do not know how to parse.
Is there any better way?
key is numbered sequentially from 1.
```
{
  "1": {
    "name": "hoge",
    "num": "60"
  },
  "2": {
    "name": "huga",
    "num": "100"
  },
  "3": {
    "name": "hogehuga",
    "num": "10"
  },
  .
  .
  .
  "10": {
    "name": "name",
    "num": "30"
  },
}
```

Do I need to write everything to Foo?
```
case class Bar(name : String, num: String)
case class Foo(`1` : Bar)
```

**Comment by plokhotnyuk** [comment]
@shogo-takao You can derive a decoder for `Map[Int, Bar]` like [here](https://github.com/plokhotnyuk/jsoniter-scala/blob/ea89a83a4825de4c145674415213b742de24cdee/jsoniter-scala-benchmark/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/benchmark/MapOfIntsToBooleansBenchmark.scala#L44)

**Comment by shogo-takao** [comment]
@plokhotnyuk 
thanks for answer!
`Map[Int, Bar]` write in case class?
I do not understand how to use this...
sorry...

**Comment by plokhotnyuk** [comment]
`Map` is a [Scala collection](https://docs.scala-lang.org/overviews/collections/maps.html).

You can do lookup values by the keys (`Int` in your case), group by keys, aggregate values, etc.

**Comment by shogo-takao** [comment]
Thank you!
I can decode json!
