### ISSUE TITLE
Printer - Exclude empty array

### ISSUE THREAD

**Issue by leobenkel** [circe/circe#1121]
Hello,

Is it possible to exclude empty list from the output json string representation ? 

Same way we have `dropNullValues` ?

Thanks

**Comment by travisbrown** [comment]
We're unlikely to support this at the printer level. It's pretty common (and at least recommended by some versions of the JSON spec, IIRC) to treat missing fields and null-valued fields as semantically equivalent, and while you sometimes see the same thing for `{}` and `[]`, it's much less common in my experience.

If someone wanted to add a convenience method for doing this at the `Json` level, I'd be happy to review.
