### ISSUE TITLE
Documentation example is not compiling (ADT, ShapesDerivation)

### ISSUE THREAD

**Issue by fancywriter** [circe/circe#1125]
Hello!
I am trying to compile the following example. https://circe.github.io/circe/codecs/adt.html
```
sealed trait Event

case class Foo(i: Int) extends Event
case class Bar(s: String) extends Event
case class Baz(c: Char) extends Event
case class Qux(values: List[String]) extends Event
```
Precisely I want to use `ShapesDerivation`, like here:
```
import io.circe._ // no such line in example, but had to import it
object ShapesDerivation {
  import io.circe.shapes // not used actually
  import shapeless.{ Coproduct, Generic }

  implicit def encodeAdtNoDiscr[A, Repr <: Coproduct](implicit
    gen: Generic.Aux[A, Repr],
    encodeRepr: Encoder[Repr]
  ): Encoder[A] = encodeRepr.contramap(gen.to)

  implicit def decodeAdtNoDiscr[A, Repr <: Coproduct](implicit
    gen: Generic.Aux[A, Repr],
    decodeRepr: Decoder[Repr]
  ): Decoder[A] = decodeRepr.map(gen.from)

}
```
Didn't use or write previous `GenericDerivation`, so no really need to suppress imports? 

And this example
```
import ShapesDerivation._
import io.circe.parser.decode, io.circe.syntax._
decode[Event]("""{ "i": 1000 }""")
(Foo(100): Event).asJson.noSpaces
```

Doesn't compile on line `decode[Event]("""{ "i": 1000 }""")`, gives two errors:
```
could not find implicit value for evidence parameter of type io.circe.Decoder[com.example.Event]
```
and
```
could not find implicit value for parameter encoder: io.circe.Encoder[com.example.Event]
```

What else do I need? 🤔  Or may be documentation is a bit out of date?

Version if all libraries I use is 0.11.1.

**Comment by travisbrown** [comment]
The documentation works (that's verified by CI on every pull request), but the trick is that you have to compile everything on the page, in order. In this case I believe what's missing is the `io.circe.generic.auto._` import, but I might be wrong.

Good catch on the unused import—I'd happily accept a PR removing it.

**Comment by fancywriter** [comment]
@travisbrown thank you! Found it https://github.com/circe/circe/blob/master/docs/src/main/tut/codecs/adt.md
Yes, may be you're right - will update and prepare PR later.

**Comment by fancywriter** [comment]
@travisbrown, no I am afraid it doesn't work that way. Could you give me a hand? Probably it's very silly mistake and I am indeed missing important import.

If I add the line `import io.circe.generic.auto._`, everything compiles fine, but `import ShapesDerivation._` is marked as unused in IDEA now (and in any code analyser).

And `decode[Foo]("""{ "i": 1000 }""")` works fine (translated to `Right(Foo(1000))`).
However, if I change `Foo` to `Event`, it gives me `Left(DecodingFailure(CNil, List()))`, but this is the whole idea, isn't it? 🤔

**Comment by travisbrown** [comment]
I just copied and pasted the code from the page and it decodes the example just fine:

```scala
sealed trait Event

case class Foo(i: Int) extends Event
case class Bar(s: String) extends Event
case class Baz(c: Char) extends Event
case class Qux(values: List[String]) extends Event

import cats.syntax.functor._
import io.circe.{ Decoder, Encoder }, io.circe.generic.auto._
import io.circe.syntax._

object GenericDerivation {
  implicit val encodeEvent: Encoder[Event] = Encoder.instance {
    case foo @ Foo(_) => foo.asJson
    case bar @ Bar(_) => bar.asJson
    case baz @ Baz(_) => baz.asJson
    case qux @ Qux(_) => qux.asJson
  }

  implicit val decodeEvent: Decoder[Event] =
    List[Decoder[Event]](
      Decoder[Foo].widen,
      Decoder[Bar].widen,
      Decoder[Baz].widen,
      Decoder[Qux].widen
    ).reduceLeft(_ or _)
}

import GenericDerivation._
// import GenericDerivation._

import io.circe.parser.decode
// import io.circe.parser.decode

decode[Event]("""{ "i": 1000 }""")
// res0: Either[io.circe.Error,Event] = Right(Foo(1000))

(Foo(100): Event).asJson.noSpaces
// res1: String = {"i":100}

import GenericDerivation.{ decodeEvent => _, encodeEvent => _ }

object ShapesDerivation {
  import io.circe.shapes
  import shapeless.{ Coproduct, Generic }

  implicit def encodeAdtNoDiscr[A, Repr <: Coproduct](implicit
    gen: Generic.Aux[A, Repr],
    encodeRepr: Encoder[Repr]
  ): Encoder[A] = encodeRepr.contramap(gen.to)

  implicit def decodeAdtNoDiscr[A, Repr <: Coproduct](implicit
    gen: Generic.Aux[A, Repr],
    decodeRepr: Decoder[Repr]
  ): Decoder[A] = decodeRepr.map(gen.from)

}

import ShapesDerivation._
// import ShapesDerivation._

import io.circe.parser.decode, io.circe.syntax._
// import io.circe.parser.decode
// import io.circe.syntax._

decode[Event]("""{ "i": 1000 }""")
// res3: Either[io.circe.Error,Event] = Right(Foo(1000))

(Foo(100): Event).asJson.noSpaces
```

**Comment by fancywriter** [comment]
Well, no wonder why it works - you put everything in one file, it means `GenericDerivation` is used. Have you tried to comment out or delete it's implementation?

I think the line `import GenericDerivation.{ decodeEvent => _, encodeEvent => _ }` doesn't work as expected in one file, it may work with separate files.

`GenericDerivation` works just fine, but I wanted to make `ShapesDerivation` to work too.

**Comment by travisbrown** [comment]
I don't have a lot of context for this example specifically or time to look at it at the moment, but yeah, I guess the `import GenericDerivation.{ decodeEvent => _, encodeEvent => _ }` isn't doing what the document says it does. I'll take a closer look and fix it when I can.

**Comment by travisbrown** [comment]
Here's the minimization that works as expected:

```scala
sealed trait Event

case class Foo(i: Int) extends Event
case class Bar(s: String) extends Event
case class Baz(c: Char) extends Event
case class Qux(values: List[String]) extends Event

import io.circe.{ Decoder, Encoder }
import io.circe.generic.auto._, io.circe.shapes._

object ShapesDerivation {
  import shapeless.{ Coproduct, Generic }

  implicit def encodeAdtNoDiscr[A, Repr <: Coproduct](implicit
    gen: Generic.Aux[A, Repr],
    encodeRepr: Encoder[Repr]
  ): Encoder[A] = encodeRepr.contramap(gen.to)

  implicit def decodeAdtNoDiscr[A, Repr <: Coproduct](implicit
    gen: Generic.Aux[A, Repr],
    decodeRepr: Decoder[Repr]
  ): Decoder[A] = decodeRepr.map(gen.from)
}

import ShapesDerivation._

io.circe.parser.decode[Event]("""{ "i": 1000 }""")
```

**Comment by chrisalbright** [comment]
@travisbrown - I hit up the Gitter channel a few days ago about this exact thing as well, and you helped me get the example working. I am able to make this work as well; however, if I change the setup (like, refactor the types or implicits into different files for example), it breaks. It's making me think I'm crazy, or there's something going on I seriously don't understand. I'll put some code examples here, but in the meantime... do you have any ideas? Is there some need for all the code to be in the same file/module?

**Comment by travisbrown** [comment]
@chrisalbright If you can post an example I can take a look.

**Comment by chrisalbright** [comment]
@travisbrown I'll put together some gists and post here. Thanks again.
