### ISSUE TITLE
Make a "create Json" function in Json that accepts field-Json pairs and an existing Json

### ISSUE THREAD

**Issue by allenjhan** [circe/circe#1128]
Let me begin by first saying thank you for this wonderful library.

My company recently switched from Jackson to Circe. Of course, one of the changes we want to minimize is the amount of code that has to be changed as part of this process.

What I currently plan to do is to write custom encoders and decoders for all of our traits so that they will be handled in the same way they were handled by Jackson.

One thing that would help others with this transition process from Jackson to Circe is if there was a function that created a Json class, given an already existing Json class and a String-Json pair. A generalization of the function would accept arbitrary numbers of String-Json pairs to append or prepend to the fields in an already existing Json class.

The reason for this is that Jackson handles serialization of traits by adding an extra field in the JSON to indicate what the subclass is. Circe, in contrast, by default puts this information in a fieldName and nests the JSON under that field name.

Here is an example.

```
trait Num{
  def valueAsDouble: Double
}
case class NaturalNumber(value: Int) extends Num {
  def valueAsDouble: Double = value
}
case class RationalNumber(value: Double) extends Num {
  def valueAsDouble: Double = value
}
case class SomeNumbers(value1: NaturalNumber, value2: RationalNumber)
```

Circe would parse SomeNumbers(NaturalNumber(1), RationalNumber(1.1)) as
```
{
  "value1": {
    "NaturalNumber": {
      "value": 1
    }
  },
  "value2": {
    "RationalNumber": {
      "value": 1.1
    }
  }
}
```

while Jackson would parse it as
```
{
  "value1": {
    "numberType": "NaturalNumber",
    "value": 1
  },
  "value2": {
    "numberType": "RationalNumber",
    "value": 1.1
  }
}
```
where the field numberType is specified by the user to distinguish the various subclasses of Num from each other.

What I am suggesting is that there be a function that would allow you to prepend or append an arbitrary number of fields to an existing Json class. That would allow the user to introduce the "numberType" field in the above example without having to write excessively long encoders and decoders for the entire subclass. A simple function call would prepend or append the desired fields to a Json class. It would probably be located in the Json object in io.Circe.

Even if someone implements the above function, it will not be implemented in time for me to use it. I plan to write the custom encoders and decoders by hand. However, for other people down the line, this could make the transition much smoother.

**Comment by allenjhan** [comment]
I would like to add that a prepend function would allow the user to prepend a field that describes the subclass of a trait.

Appending a function could be used to append evaluated functions to the JSON.

So for the previous example,
```
trait Num{
  def valueAsDouble: Double
}
case class NaturalNumber(value: Int) extends Num {
  def valueAsDouble: Double = value
}
```
it would be nice to be able to have an easy way to have NaturalNumber(1) be parsed as
```
{
  "numberType": "NaturalNumber",
  "value": 1,
  "valueAsDouble": 1
}
```
Here the numberType field was prepended to the JSON, and the valueAsDouble field was appended to the JSON. The automatic encoders and decoders do not create these fields, so it would be nice to have an easy way to attach them to an existing Json class to create a JSON.

**Comment by odenzo** [comment]
Trying to figure out something slight different but a few things to help:

* Recommend Circe Generic Extras for: deriveUnwrappedCodec
* Decoder.prepare(acursor => acursor.up) which will move the cursor to the enclosing JsonObject. 

And more directly to your point, On Encoder .mapJson (Encoder.AsObject .mapJsonObject) allows you to easily add fields. e.g. 

``` 
  implicit val encoder: Encoder.AsObject[Fooo] =
      deriveConfiguredEncoder[Fooo].mapJsonObject(_.add("Bar", "Open".asJson))

```

Regarding the prepare Decoder, I am just working with that now. This works:

Given:
```
{
    "a" : "TestA",
    "workday" : 123,
    "c" : {
        "workday" : 666
    }
}
```
case class Fooo(a: String, c: Either[Int, String])

  object Fooo {
    implicit val config: Configuration = Configuration.default
    implicit val encoder: Encoder.AsObject[Fooo] = deriveConfiguredEncoder[Fooo]

    implicit val ee: Encoder.AsObject[Either[Int, String]] = Encoder.encodeEither[Int, String]("workday", "weekday")

    implicit val dd: Decoder[Either[Int, String]] =
      Decoder.decodeEither[Int, String]("workday", "weekday").prepare(_.up)

    implicit val decoder: Decoder[Fooo] = deriveConfiguredDecoder[Fooo]

  }
```

Note: .prepare(_.up).   The cursor normally starts at the JsonObject in field 'c'
Moving up places the cursor in the enclosing JsonObject.

```
 logger.info(s"Decoded ${json.as[Fooo]} \n ${json.spaces4}")
```

Gives:

 Decoded Right(Fooo(TestA,Left(123))) 
 {
    "a" : "TestA",
    "workday" : 123,
    "c" : {
        "workday" : 666
    }
}

Without the prepare it would given 666.

Given all the great stuff (sometimes hidden) in Circe... I may try to document this!

Since I have the Either in *tons* of classes I am trying to figure out a better way to do the encoder with .mapJsonObject on the Fooo encoder to lift the fields, e.g. 

```
 def liftAllFields(toAddField: String, in: JsonObject): JsonObject = {
    in(toAddField).flatMap(_.asObject) match {
      case None      => in
      case Some(obj) => JsonObject.fromIterable(obj.toVector ++ in.remove(toAddField).toVector)
    }
  }

deriveConfiguredEncoder[Fooo].mapJsonObject(liftAllFields("c")
```

There appears to be no solution that just involves making changes to 
val ee: Encoder.AsObject[Either[Int, String]]

**Comment by allenjhan** [comment]
I think the easiest way to get the functionality I am talking about is to use the deepMerge function in sealed abstract class Json.

Here is an example, where I try to add "classType" field too Foo. The idea is to encode the MasterFoo trait and to add the "classType" field to the subtype's JSON.

```
import io.circe._
import io.circe.generic.extras.semiauto._

trait MasterFoo

object MasterFoo {
  import Foo._

  implicit val masterfooEncoder: Encoder[MasterFoo] = new Encoder[MasterFoo]{
    override def apply(a: MasterFoo): Json = {
      a match {
        case f: Foo =>
          val defaultEncoder = implicitly[Encoder[Foo]]
          val mergeMe = Json.obj(("classType", "Foo"))
          defaultEncoder.apply(f).deepMerge(mergeMe)
      }
    }
  }
}

case class Foo(count: Int) extends MasterFoo

object Foo {
  implicit val fooEncoder: Encoder[Foo] = deriveConfiguredEncoder
}
```
