### ISSUE TITLE
Add an option to fail on duplicate key when parsing an object

### ISSUE THREAD

**Issue by blitzkr1eg** [circe/circe#1130]
{ "a": 1, "a": 2 }

The above json is invalid (by jsonLint) but the parser succeeds and keeps the last value seen.
Add a mechanism to specify if duplicate keys are allowed or not when parsing.

**Comment by plokhotnyuk** [comment]
It is must have feature and it can be easy implemented by adding a configuration flag which will turn on checking of the result of all `m.put` calls [here](https://github.com/circe/circe/blob/master/modules/jawn/src/main/scala/io/circe/jawn/CirceSupportParser.scala).

**Comment by blitzkr1eg** [comment]
Thanks. I'm trying the fix.

**Comment by travisbrown** [comment]
Fixed in #1131 and #1149. Thanks @blitzkr1eg!
