### ISSUE TITLE
generic encoders ignore "non-constructor" case class members

### ISSUE THREAD

**Issue by aSapien** [circe/circe#1136]
Example:

```scala
object Example extends App {
  import io.circe.syntax._
  import io.circe.Printer.noSpaces.pretty
  import io.circe.generic.auto._

  case class Bar(foo: Int) {
    val baz: String = "boom"
  }

  println(pretty(Bar(1).asJson))
}
```

Expected: `{"foo":1,"baz":"boom"}`
Actual: `{"foo":1}`

I tried to enable `withDefaults` using `io.circe.generic.extras.Configuration`, but to no avail. 

I believe it is a common use-case in Scala. 
Why is this the default behavior? 
Is there a configuration option I'm missing? 

I'd really like to avoid creating my own `Encoder` for this.

Thanks,
Dima

**Comment by plokhotnyuk** [comment]
@aSapien Have you considered an option to move `baz` to the list of arguments, like here below?

```
case class Bar(foo: Int, baz: String = "boom")
```

**Comment by aSapien** [comment]
@plokhotnyuk that's what I did. For now :) 
However, I'd like to understand if this is a configurable feature, and if not, the reasoning behind it.

**Comment by travisbrown** [comment]
@aSapien All of the functionality in circe-generic-* is built around Shapeless's generic representation of case classes and sealed trait hierarchies, which does not include `val`s defined in the body of the class:

```scala
scala>   case class Bar(foo: Int) {
     |     val baz: String = "boom"
     |   }
defined class Bar

scala> shapeless.LabelledGeneric[Bar]
res0: shapeless.LabelledGeneric[Bar]{type Repr = Int with shapeless.labelled.KeyTag[Symbol with shapeless.tag.Tagged[String("foo")],Int] :: shapeless.HNil} = shapeless.LabelledGeneric$$anon$1@1f39c060
```
You could write your own `LabelledGeneric` instances (either per-class or as a generic macro) that would include things like `baz` as members, and everything in circe would just work as you expect. In my view this is how things should be for circe-generic and circe-generic-extras: `shapeless.LabelledGeneric` underlies everything, and while circe-generic does have some of its own macros, these are only for the purposes of efficiency—they don't try to extend or replace the work done by Shapeless.

I could imagine [circe-derivation](https://github.com/circe/circe-derivation) supporting these cases off-the-shelf, and I'd encourage you to open an issue there (if you don't want to go the route of writing your own `LabelledGeneric` instances). This isn't something I'm personally likely to prioritize (without getting paid for it), but I'd be happy to review PRs there.

**Comment by aSapien** [comment]
@travisbrown thanks for a detailed explanation!
