### ISSUE TITLE
Code from ADT section of documentation not compiling

### ISSUE THREAD

**Issue by TomPoczos** [circe/circe#1141]
On [this](https://circe.github.io/circe/codecs/adt.html) page you have the following code snippet:

```scala
implicit val decodeEvent: Decoder[Event] =
    List[Decoder[Event]](
      Decoder[Foo].widen,
      Decoder[Bar].widen,
      Decoder[Baz].widen,
      Decoder[Qux].widen
    ).reduceLeft(_ or _)
```

as far as I can tell it only compiles with the below changes:

```scala
implicit val decodeEvent: Decoder[Event] =
    List[Decoder[Event]](
      Decoder[Foo.type].widen,
      Decoder[Bar.type].widen,
      Decoder[Baz.type].widen,
      Decoder[Qux.type].widen
    ).reduceLeft(_ or _)
```

**Comment by travisbrown** [comment]
Can you provide a complete example showing the failure you saw? The version on the page is correct and adding `.type` should not even compile.

The following should compile on all recent circe versions:
```scala
sealed trait Event

case class Foo(i: Int) extends Event
case class Bar(s: String) extends Event
case class Baz(c: Char) extends Event
case class Qux(values: List[String]) extends Event

import cats.syntax.functor._
import io.circe.{ Decoder, Encoder }, io.circe.generic.auto._
import io.circe.syntax._

object GenericDerivation {
  implicit val encodeEvent: Encoder[Event] = Encoder.instance {
    case foo @ Foo(_) => foo.asJson
    case bar @ Bar(_) => bar.asJson
    case baz @ Baz(_) => baz.asJson
    case qux @ Qux(_) => qux.asJson
  }

  implicit val decodeEvent: Decoder[Event] =
    List[Decoder[Event]](
      Decoder[Foo].widen,
      Decoder[Bar].widen,
      Decoder[Baz].widen,
      Decoder[Qux].widen
    ).reduceLeft(_ or _)
}
```

**Comment by TomPoczos** [comment]
[Sure](https://github.com/TomPoczos/scalpaca/blob/6252db7ebf5339d746d1a10b9ae9187ffd2854be/src/main/scala/model/AccountStatus.scala#L32)

My master branch currently does what I expect it to while using the `Decoder[Foo.type].widen` version of ADT decoding, and it does not compile when I try to remove the `.type` part.

For reference, the code I ended up with is based on a [stackoverflow discussion](https://stackoverflow.com/questions/55670150/encountering-errors-when-trying-to-write-either-a-circe-encoder-or-decoder-for-a) from a while ago.

**Comment by travisbrown** [comment]
@TomPoczos Right, case objects only have singleton types, but since the doc example uses case classes I don't think this is really a matter for the issue tracker, no?

**Comment by TomPoczos** [comment]
You are of course right, thanks for your explanation. Since I didn't figure out what makes the difference between my code and what's in the documentation, I wanted to make sure this doesn't potentially slow down others just getting familiar with Circe and Scala, in case the issue was with the documentation. Turns out it's just me having to learn more about the language.

I think this can be closed, thanks for your time.
