### ISSUE TITLE
circe-java8  for Scala 2.13

### ISSUE THREAD

**Issue by hmf** [circe/circe#1171]
I have updated to `0.12.0-M3` but it seems like `circe-java8` only reached `0.12.0-M1` for Scala `2.13.0-RC1`. Maybe a small oversight in updating the library? Last reference  to this module is in https://github.com/circe/circe/issues/975 but that seems to be solved. 

TIA.

**Comment by travisbrown** [comment]
Please see [the 0.12.0-M3](https://github.com/circe/circe/releases/tag/v0.12.0-M3) release notes for an explanation of why we're no longer publishing circe-java8. You should be able to migrate simply by removing the dependency and imports, unless you are referring to the instances explicitly, in which case you'll need to replace `io.circe.java8.X` with `Decoder.X` or `Encoder.X` as appropriate. If you run into other issues with the migration, please let us know.

**Comment by hmf** [comment]
Thank you for the information. Will do.
