### ISSUE TITLE
[Automatic Derivation] Could not find Encoder for case class with Enum or sealed traits

### ISSUE THREAD

**Issue by chih-chen** [circe/circe#1203]
Hi, 

I have a case class like this: 

```scala
case class Admin(name: String, role: Role)
```

`Role` is an `Enumeration`
```scala
object Role extends Enumeration {
  type Role = Value
  val Manager = Value
}
```

When I try to: 
```scala
import io.circe.generic.auto._, io.circe.syntax._

val response = Admin("John", Role.Manager).asJson.noSpaces
```

**I get the implicit Encoder not found error.** 
```
not enough arguments for method asJson: (implicit encoder: io.circe.Encoder[Admin])io.circe.Json. Unspecified value parameter encoder.
```
I suppose this error is due Enumeration, so I changed to: 

```scala
trait Role

object Role {
  object Manager extends Role
}
```

But this does't work too. 

Lastly, I tried: 

```scala
trait Role

object Manager extends Role
```

And no success. Can someone help me please? Thanks!

**Comment by tindzk** [comment]
Your trait has to be `sealed`. This works for me (Scala 2.13.0, Circe 0.12.0-M4):

```scala
import io.circe.syntax._
import io.circe.generic.simple.auto._

sealed trait Role
case object Manager extends Role
case class Admin(name: String, role: Role)

val response = Admin("John", Manager).asJson.noSpaces
```

Your `Enumeration` example should work too if you use `deriveEnumerationEncoder` provided by `circe-generic-extras`.

**Comment by travisbrown** [comment]
@chih-chen There are a few ways you can make this work. As @tindzk says, you can seal the trait and use generic derivation, but you could also use `Encoder.encoderEnumeration` if you want to stick with Scala's enumerations (which I don't necessarily recommend, personally):

```scala
object Role extends Enumeration {
  type Role = Value
  val Manager = Value
}

case class Admin(name: String, role: Role.Role)

import io.circe.Encoder
import io.circe.generic.auto._, io.circe.syntax._

implicit val encodeRole: Encoder[Role.Role] = Encoder.encodeEnumeration(Role)
```
And then:
```scala
scala> val response = Admin("John", Role.Manager).asJson.noSpaces
response: String = {"name":"John","role":"Manager"}
```
