### ISSUE TITLE
[0.12.0] Hanging in `io.circe.Printer.pretty` with 100% CPU usage

### ISSUE THREAD

**Issue by plokhotnyuk** [circe/circe#1250]
Steps to reproduce:
```
git clone https://github.com/plokhotnyuk/jsoniter-scala.git
cd jsoniter-scala
sed -i 's/0.12.0-RC4/0.12.0/g' build.sbt
sbt clean test
```

Here is a flame graph that was built by async-profiler: https://gist.github.com/plokhotnyuk/722b319ca88ec303be015c40cf146f48

**Comment by travisbrown** [comment]
Oh, ouch, thanks—publishing an 0.12.1 now.
