### ISSUE TITLE
ConfiguredJsonCodec macro annotation does not work in Scala 2.13.

### ISSUE THREAD

**Issue by igortn** [circe/circe#1256]
Let's say we have a case class with ConfiguredJsonCodec macro annotation and with implicit configuration that supports this configured codec:
```
import io.circe.generic.extras.{Configuration, ConfiguredJsonCodec}

@ConfiguredJsonCodec
case class Item(
  itemId: Long,
  itemName: String
)

object Item {
  implicit val itemDecoderConf: Configuration = Configuration(_.capitalize, identity, useDefaults = false, None)
}
```
The motivation is that we want decode the json string like
```
val js = """{"ItemId" : 7, "ItemName" : "Trip"}"""
```
and we need to convert names from the Pascal case to the camel case to match the case class definition.

The code to parse and decode can look like
```
import io.circe.parser.parse

val parseResult = parse(jsString)
parseResult.fold(println, js => println(js.as[Item]))
```
The interesting piece here is decoding: `js.as[Item]`.

This works perfectly fine with scala 2.12.9 and the macro paradise compiler plugin.
After changing scala version to 2.13.0 and removing the macro paradise plugin ( it must be removed, as 2.13 includes macro processing in the standard lib), the code above does not compile anymore with the error message:
```
could not find implicit value for parameter d: io.circe.Decoder[Item]
```
which likely means that the decoder could not be generated as the result of macro processing.

The circe version used in both cases is 0.12.1, but I also tried 0.11.0 with exactly same results.

It seems that the implementation of `ConfiguredJsonCodec` needs to be adjusted for 2.13.

**Comment by travisbrown** [comment]
Oh, have you added the `-Ymacro-annotations` compiler option to your 2.13 build? It's the replacement for that part of the Paradise plugin, and should be all you need to use Circe's annotations.

**Comment by igortn** [comment]
That was it. Added, works as expected.

I do not know how I missed that. But it's all good now. Thank you.

This is non-issue.

**Comment by igortn** [comment]
With "-Ymacro-annotations" scalac flag, `@ConfiguredJsonCodec` works as expected in 2.13.
Closing this.

**Comment by yonatanomer** [comment]
ConfiguredJsonCodec seems not to be included anymore, is that correct?
I could find it only in custum-codecs.md file

**Comment by RodolVelasco** [comment]
How can I enabled  "-Ymacro-annotations" scalac flag? Scala version 2.13 and sbt 0.13.
I'm receiving this error
```
macro annotation could not be expanded (since these are experimental, you must enable them with -Ymacro-annotations)
@JsonCodec case class Author(@JsonKey("steamid") steamId: Long
```
