### ISSUE TITLE
Please improve error message for @ConfiguredJsonCodec

### ISSUE THREAD

**Issue by alexandru** [circe/circe#1262]
I've got a definition like this:

```scala
@ConfiguredJsonCodec
final case class Envelope(
  messageType: QueueMessageType,
  json: Json
)
```

Given the following conditions:

1. the encoder/decoder for `QueueMessageType` cannot be found OR
2. the `io.circe.generic.extras.Configuration` isn't in scope

It fails at compile time with an error like:

```
could not find Lazy implicit value of type io.circe.generic.extras.decoding.ConfiguredDecoder[Envelope]
```

Unfortunately this error message doesn't say anything about the cause, about what's missing.

Could this error message be improved?

Also a rookie question: is `@ConfiguredJsonCodec` not the recommended way to generate these derived (and configured) instances?

Thanks,

**Comment by travisbrown** [comment]
This is a long-standing known issue, unfortunately. We have to use Shapeless's `Lazy` to avoid false positives from the divergence checker pre-2.13, and it's a black box as far as compiler errors are concerned.

There are currently two ways to get better messages:

- Enable the [splain](https://github.com/tek/splain) compiler plugin, which special-cases `Lazy` and gives useful error messages here.
- Use [circe-derivation](https://github.com/circe/circe-derivation)'s annotations, which don't build up instances inductively via Shapeless's generic representation, and therefore don't need `Lazy`.

There's an experimental circe-generic-simple module for 2.13 that's built on by-name implicits, and it's likely to become the circe-generic implementation in circe 1.0, but that's still TBD.
