### ISSUE TITLE
@JsonCodec(encodeOnly=true) causes a compiler error in Scala 2.13

### ISSUE THREAD

**Issue by leonardehrenfried** [circe/circe#1264]
When upgrading from Scala 2.12 to 2.13 am running into the following compiler error:

```
Usage of named or default arguments transformed this annotation
[error] constructor call into a block. The corresponding AnnotationInfo
[error] will contain references to local values and default getters instead
[error] of the actual argument trees
[error]   @JsonCodec(decodeOnly = true)
[error]    ^
```

The full import is `io.circe.generic.JsonCodec`.

What is the correct way to express this in Scala 2.13?

Note that I have set my compiler options to very strict (https://github.com/DavidGregory084/sbt-tpolecat/blob/master/src/main/scala/io/github/davidgregory084/TpolecatPlugin.scala) and all warnings (which this might be) are converted to errors.

**Comment by leonardehrenfried** [comment]
Would you like an reproduction case for this?

**Comment by leonardehrenfried** [comment]
Ok, I figured it out myself.

I had not added the scalac option `-Ymacro-annotations".

```
scalacOptions in ThisBuild ++= Seq("-Ymacro-annotations")
```

fixes it.

**Comment by travisbrown** [comment]
That's odd—I've forgotten that option a few times but have seen different error messages. Thanks for tracking it down, @leonardehrenfried.
