### ISSUE TITLE
Decoder seems to have trouble dealing with new line

### ISSUE THREAD

**Issue by allenjhan** [circe/circe#1283]
I am working on a project where I am parsing JSONs that contain string fields that are actually csv formatted strings. This means the string has new line.

I am getting a ParserError when I try to decode the JSON. I have illustrated the problem in a minimally reproducible example below.

```
import io.circe.{Decoder, Encoder}
import io.circe.generic.semiauto._
import io.circe.parser._

object CirceTest extends App{

  case class Wrapper(csv: String)

  object Wrapper {
    implicit val wrapperEncoder: Encoder[Wrapper] = deriveEncoder
    implicit val wrapperDecoder: Decoder[Wrapper] = deriveDecoder
  }

  val json =
    """{
      |  "csv": "asdf
      |  asdfadsf
      |  asf"
      |}
    """.stripMargin

  println(decode[Wrapper](json))
}
```

Here is the output I get from the println:
```
Left(io.circe.ParsingFailure: control char (10) in string got '
...' (line 2, column 15))
```

This is slightly different from the error message I get from my actual program. This is the message I get: 
```
io.circe.ParsingFailure: control char (10) in string got \n (line 2, column 677)
```

This seems like a pretty trivial corner case, so I am probably missing something. However, a Google search and a look into the documentation turned up nothing. I even tried searching for the string "control char" in the Github repository for Circe, and got nothing.

Is there a fix or a workaround for this issue?

**Comment by tkroman** [comment]
This is not a valid JSON hence a parsing failure. Newlines in json are represented by e.g. `\n` embedded in a string.

**Comment by plokhotnyuk** [comment]
@allenjhan Your sample violates the statment from [the Section 7 of the JSON Specification](https://tools.ietf.org/html/rfc8259#section-7):
```
   All Unicode characters may be placed within the
   quotation marks, except for the characters that MUST be escaped:
   quotation mark, reverse solidus, and the control characters (U+0000
   through U+001F).
```

**Comment by travisbrown** [comment]
@allenjhan You could definitely modify Jawn or another JSON parsing library so that it accepts newlines, and use that with Circe. I think Jackson might even support this as an option, and it might be possible to use it with [circe-jackson](https://github.com/circe/circe-jackson) (if not, you could open an issue there and we could consider it).

As @tkroman and @plokhotnyuk point out, though, the official JSON spec doesn't allow unescaped newlines in strings, so this is out of scope for the core Circe modules in this repo.
