### ISSUE TITLE
java8 LocalDateTime is dropping 00 seconds value when parsing date string

### ISSUE THREAD

**Issue by Bunyod** [circe/circe#1292]
Currently, I'm experiencing an issue with LocalDateTime conversion.

I saw the latest changes in circe-0.12.2 here: [Commit](https://github.com/circe/circe/commit/631b299f175edf4aa6fbe4735ab34f588322ddbb
)
This change is leading to break everything related to LocalDateTime now in my company. 

I also read a similar problem on Stackoverflow and this is considered as a future. Here: [SO Answer](https://stackoverflow.com/questions/50786482/java-8-localdatetime-dropping-00-seconds-value-when-parsing-date-string-value-wi)

[You can see a live example here](https://scastie.scala-lang.org/Bunyod/ercAv3ewQHe7yJlHENfzIQ/25)

**Comment by travisbrown** [comment]
Thanks for the report. I'll publish an 0.12.3 this week (probably tomorrow).
