### ISSUE TITLE
Case Class could not find implicit encoder when Scala Collection is turned into Java One

### ISSUE THREAD

**Issue by alessandrolumino** [circe/circe#1300]
Hello everyone.

I am trying to parse a Json with a model based on this case class
`case class MyCaseClass(field: String, collection: Vector[String])`

Everything is fine but I'd prefer using this version.
`case class MyCaseClass(field: String, collection: java.util.Collection[String])`

As soon as I turn to this version, I get
```
Information:10/16/19 5:24 PM - Compilation completed with 2 errors and 0 warnings in 3 s 99 ms
    Error:Error:line (33)could not find implicit value for parameter d: io.circe.Decoder[models.MyCaseClass]
...
    Error:Error:line (33)not enough arguments for method as: (implicit d: io.circe.Decoder[models.MyCaseClass])io.circe.Decoder.Result[models.MyCaseClass].
Unspecified value parameter d.
...
```

Is it wrong using Java Collections with Circe?

**Comment by travisbrown** [comment]
We don’t provide these instances off the shelf, but you can certainly define your own, either directly or via a mapping to and from the Scala equivalents. I guess we could discuss a PR adding them natively, but there hasn’t been much demand.

**Comment by plokhotnyuk** [comment]
@alessandrolumino could you please share a use case for direct usage of Java collections (not wrapped by `scala.jdk.CollectionConverters._` wrappers)?

**Comment by alessandrolumino** [comment]
@plokhotnyuk Hi.. Let us suppose that you want to parse your Json with Circe and then construct a SpecificRecord in order to serialize it in Avro. If you want to serialize a `Vector[String]` object, Avro libraries will need a Java Collection. In fact, in this specific case, when producing to Kafka in Avro, you will get
```
org.apache.kafka.common.errors.SerializationException: Error serializing Avro message
Caused by: java.lang.ClassCastException: scala.collection.immutable.Vector cannot be cast to java.util.Collection
```

But unfortunately, if you try to cast your Scala collection to a Java one, you will get the first error I posted..

**Comment by plokhotnyuk** [comment]
@alessandrolumino why not just use a Scala library for serialization to Avro?

https://github.com/topics/avro?l=scala

**Comment by alessandrolumino** [comment]
@plokhotnyuk Very good point. It works, thanks.

**Comment by alessandrolumino** [comment]
By the way, I used avro4s!
