### ISSUE TITLE
Date objects in JSON (java8 time)

### ISSUE THREAD

**Issue by c-dante** [circe/circe#1319]
Circe has encoders/decoders for java8's time uses that the ISO standards.

JSON does not have a standard for Date objects -- in some applications, the ISO standard as a string is used, and in others, UTC millis are used.

I understand that it's ergonomic for circe to by default be able to derive those but is it possible to disable that behavior?

If my application uses UTC millis as the date representation, I need to be hyper vigilant to ensure custom UTC encoder/decoders are defined anywhere in the codebase where dates are involved alongside generic encoding/decoding.

This has cropped up in a lot of places where something like the following is set up:
```scala
case class GenericCase[T](something: T)

implicit def genericCaseEncoder[T : Encoder]: Encoder[GenericCase[T]]] = deriveEncoder
```

**Comment by hamnis** [comment]
One way to ensure you dont use the default serialization mechanism is to provide a wrapper type for the UTC millis

for Scala 2 this could be.

```scala
case class UTCMillis(value: Instant) extends AnyVal
object UTCMillis {
  implicit val codec: Codec[UTCMillis] = Codec.from(Decoder[Long].map(x => UTCMillis(Instant.ofEpochMilli(x))), Encoder[Long].contramap(_.value.toEpochMilli))
}


case class Foo(name: String, instant: UTCMillis)
```
