### ISSUE TITLE
Release Circe optics 0.12.3

### ISSUE THREAD

**Issue by tovbinm** [circe/circe#1322]
It seems that Circe Optics 0.12.(1,2,3) was never released. Please make a release for Circe optics 0.12.3.

Thanks!

**Comment by ruurtjan** [comment]
I'm also stuck on Circe 0.12.0 for this reason. A release of circe-optics 0.12.3 would be much appreciated!

**Comment by travisbrown** [comment]
All Circe releases within an 0.x series are (backwards) binary compatible with previous releases in that series. This means circe-optics 0.12.0 will work with any circe-core 0.12.x release. We do not keep patch versions in sync across repositories, so there won't be a circe-optics 0.12.1 (or 0.12.2, etc.) release unless there are fixes there that need to be published.

**Comment by ruurtjan** [comment]
Ah, that makes sense :) I assumed they had to be kept in sync because of how the quick start suggests to add dependencies:
https://github.com/circe/circe/blame/master/docs/src/main/tut/quickstart.md#L8
```
val circeVersion = "0.12.3"

libraryDependencies ++= Seq(
  "io.circe" %% "circe-core",
  "io.circe" %% "circe-generic",
  "io.circe" %% "circe-parser"
).map(_ % circeVersion)
```
