### ISSUE TITLE
Argonaut recommended over Circe

### ISSUE THREAD

**Issue by mikail-khan** [circe/circe#1379]
On your [website](https://circe.github.io/circe/) it states:

> Why?
> Argonaut is a great library. It’s by far the best JSON library for Scala, and the best JSON library on > the JVM. If you’re doing anything with JSON in Scala, you should be using Argonaut.

> circe is a fork of Argonaut with a few important differences.

Is that still the case?

**Comment by plokhotnyuk** [comment]
@mikail-khan I bet that it is not the case for now: [Argonaut has not fixed vulnerability](https://github.com/argonaut-io/argonaut/issues/314) that was reported more than a year ago.
