### ISSUE TITLE
Compare two jsons while ignoring certain keys

### ISSUE THREAD

**Issue by ashwinbhaskar** [circe/circe#1398]
It would be nice to have a method like `equalsIgnoringKeys(other: Json, ignoreKeys: List[List[String]])` on `io.circe.Json`. One common scenario where you would require this

- Response to a POST request is the request itself merged with some unique identifier. In such cases the unique identifier could be generated randomly and so you can't have that in your `expectedResponse`.  Here, it would be nice to have a a method which allows you to compare two jsons while ignoring certain keys.

Example
```
val inputJson = json"""
{
 "first_name":"John",
 "last_name":"Doe",
 "age":25,
 "email":"john.doe@psyche.com"
}"""

val response = serve(Request[IO](POST, uri"/user").withEntity(inputJson))
//response contains the exact input json plus a field called `user_id` which is a randomly generated string.

//It would be very useful to have 
response.equalsIgnoringKeys(inputJson, List(List("user_id"))
```
The second argument to `equalsIgnoringKeys` is a List of List because we want to be able give the path to every key. The key that you want to ignore could be nested.

**Comment by ybasket** [comment]
@ashwinbhaskar I would recommend [diffson](https://github.com/gnieh/diffson) for this kind of more advanced JSON comparison, it has circe support and gives a typed description of the differences which you then can easily filter for the key paths you're (not) interested in.

**Comment by hamnis** [comment]
Closing in cleanup run, If anyone cares about this, please comment and I'll reopen.
