### ISSUE TITLE
Release for Scala.js 1.0.0

### ISSUE THREAD

**Issue by darkfrog26** [circe/circe#1407]
There is a partial release for Scala.js 1.0.0-RC2, but it doesn't include everything.  Now that 1.0.0 is released, it would be nice to start using it.

**Comment by travisbrown** [comment]
Good timing, I just posted [an update](https://contributors.scala-lang.org/t/this-is-not-the-release-announcement-of-scala-js-1-0-0/4021/21?u=travisbrown) about this half an hour ago.

We can use this issue to track the missing dependencies:

- [ ] Shapeless
- [ ] Refined
- [ ] scala-java-time
- [ ] scodec-bits
- [ ] Scoverage

**Comment by darkfrog26** [comment]
Is there an alternative for using `circle-generic-extras` or is it still on its way?

I'm using it for:
```scala
import io.circe._
       import io.circe.generic.extras
       import io.circe.generic.extras.auto._
       implicit val customConfig: extras.Configuration = extras.Configuration.default.withDefaults
```

**Comment by travisbrown** [comment]
@darkfrog26 It’s waiting on Shapeless so cant really guess.

**Comment by darkfrog26** [comment]
No problem, I just wanted to verify that it wasn't being left behind and there was another path toward supporting default params in case classes.

**Comment by yurique** [comment]
@travisbrown 
Hi! I believe these libs from the list have releases for scalajs 1.0.0 now:

* shapeless - https://search.maven.org/search?q=a:shapeless_sjs1_2.13
* refined - https://search.maven.org/search?q=a:refined_sjs1_2.13
* scalajs-java-time - https://search.maven.org/search?q=a:scalajs-java-time_sjs1_2.13

**Comment by travisbrown** [comment]
Right, we're just waiting on scala-java-time now (I'll try just dropping Scoverage altogether for Scala.js).

**Comment by travisbrown** [comment]
Done! https://github.com/circe/circe/releases/tag/v0.13.0

**Comment by yurique** [comment]
Thank you, Travis! You're on top of it as always :)

**Comment by totallhall64** [comment]
L

**Comment by totallhall64** [comment]
Lying bitch i new u were part of grubhub
