### ISSUE TITLE
Expose Function for Sanitizing JSON?

### ISSUE THREAD

**Issue by kevinmeredith** [circe/circe#1425]
At work, I've written a function that sanitizes JSON if a key is not in an approved `Set[String]`.

The function looks like:

```scala
def sanitize(json: Json, approvedList: Set[String], sanitizedValue: String): Json
```

If a JSON key is in the whitelist, then its value will be shown*; otherwise, the key's value will be sanitized, i.e. replaced with $sanitizedValue.

Example:

```scala
val json: Json = Json.obj( ("foo" := "bar"), ("bip" := 1234) )
val output: Json = sanitize(json, Set("foo"), "XXXX")
```

`output` would equal `{ "foo" : "bar", "bip" : "XXXX"}` since `bip` is not in the approved list.

Please let me know if you're interested in such functionality, i.e. would welcome a PR.

Thanks

`*` - objects and arrays are handled differently.

**Comment by kevinmeredith** [comment]
Could you please let me know your thoughts, @travisbrown? Thanks

**Comment by travisbrown** [comment]
Thanks for proposing this. I don't really think it belongs in circe-core, but I've been thinking for a while that we should have a circe-extras module for stuff like this (it would have only a circe-core dependency, and would be for things that didn't quite make the circe-core cut). If someone wants to kick that off it'd definitely move faster than if it's left up to me.

**Comment by kevinmeredith** [comment]
> If someone wants to kick that off it'd definitely move faster than if it's left up to me.

Thanks, Travis! If I propose such a change, I'll do so in `circe-extras`, as you noted.
