### ISSUE TITLE
Using @JsonCodec + Scala 2.13.2 + sbt-tpolecat doesn't report unused imports

### ISSUE THREAD

**Issue by GuillaumeSaintRaymondSonos** [circe/circe#1484]
Here is a sample project reproducing the problem: https://github.com/GuillaumeSaintRaymondSonos/sbt-tpolecat-circe/ where I left an unused import in `Hello.scala`. The compiler doesn't report anything.
By downgrading to Scala 2.13.1, the compiler reports correctly the unused import.

I opened the issue first on the [sbt-tpolecat repository](https://github.com/DavidGregory084/sbt-tpolecat/issues/22).
I'm not 100% sure the problem comes from circe but I would appreciate greatly if I can have your point of view on this.

**Comment by SethTisue** [comment]
note that https://github.com/scala/scala/pull/8799 may be relevant

**Comment by GuillaumeSaintRaymondSonos** [comment]
Tried today with Scala 2.13.3, unused import is reported !
