### ISSUE TITLE
Encoder.at

### ISSUE THREAD

**Issue by Lasering** [circe/circe#1536]
Similarly to [Decoder.at](https://circe.github.io/circe/api/io/circe/Decoder.html#at(field:String):io.circe.Decoder[A]) there should also exist a method `at` in `Encoder`

```scala
trait Encoder[A] extends Serializable { self =>
  (...)
  final def at(field: String): Encoder[A] = mapJson(j => Json.obj(field -> j))
}
```

**Comment by travisbrown** [comment]
This sounds reasonable to me!
