### ISSUE TITLE
Add the `hacktoberfest` topic? 

### ISSUE THREAD

**Issue by x3ro** [circe/circe#1549]
Hey folks,

I'm a (relatively new) user of Circe and would like to give something back (documentation, potentially a slight expansion of how `.withDiscriminator` affects the output of YAML in `circe-yaml` as a proposal). In order for my contributions to count towards my Hacktoberfest goal it'd be nice if you could add the `hacktoberfest` topic to this repository and to `circe-yaml` ([more info here](https://hacktoberfest.digitalocean.com/details#maintainers)) 🙂 

Cheers
Lucas

**Comment by travisbrown** [comment]
Good idea, done!
