### ISSUE TITLE
Failure to decode on ScalaJS 1.3.1

### ISSUE THREAD

**Issue by sloshy** [circe/circe#1620]
Hello, I recently ran into an issue where ScalaJS 1.3.1 breaks Circe decoders for my project, and I'm not entirely sure why. I've copied over some code from a personal project and finagled with it a bit to get a minimal example going.

Repository reproducing the issue: https://github.com/sloshy/circe-bug-1620

To reproduce the issue:

1. Run `sbt test` to see the circe golden test for the codec succeed. You can also check the generated file in the `modules/core/jvm` project to see it's in the right format.
2. Run `sbt 'webClient/fastOptJS::webpack'` to build the app for ScalaJS. It doesn't need webpack, actually, I just copied enough code to get this to work from a project that does use it.
3. Load up `index.html` in a web browser (I just use `python3 -m http.server` and go to `localhost:8000`)
4. The web page will be blank, but open the web browser console. You should see the actual JSON as encoded by Circe, and then the results of trying to decode it.
5. Change the `project/plugins.sbt` version of ScalaJS to `1.3.0` or `1.2.0` and re-run step 2 to see the decoder work properly.

Any assistance is appreciated. I'll also link this bug in the ScalaJS gitter to see if it can get attention from people more familiar with ScalaJS since this could be a problem with the plugin moreso than circe.

**Comment by sjrd** [comment]
See https://github.com/scala-js/scala-js/issues/4305.

tl:dr Apparently a bug in Webpack, surfaced by a change in encoding in Scala.js 1.3.1. The ticket contains a workaround.

**Comment by sloshy** [comment]
Thanks, I somehow missed that when looking for this. I'll close this issue as I think it's a duplicate of that.
