### ISSUE TITLE
Provide a macro-annotation to reduce defining Encoder/Decoder pairs

### ISSUE THREAD

**Issue by dwijnand** [circe/circe#166]
From your blog post https://meta.plasm.us/posts/2016/01/14/configuring-generic-derivation/

I was wondering if perhaps

``` scala
import io.circe.generic.semiauto._

case class Foo(thisIsSomeNumber: Int = 0)
object Foo {
  implicit val decodeFoo: Decoder[Foo] = deriveConfiguredDecoder[Foo, SnakeCaseKeys]
  implicit val encodeFoo: Encoder[Foo] = deriveConfiguredEncoder[Foo, SnakeCaseKeys]
}
```

could be further boilerplate-reduced to

```
import io.circe.macros.MkCodec // or some other name
import io.circe.generic.semiauto._

@MkCodec case class Foo(thisIsSomeNumber: Int = 0)
```

I've read your "The public API should not contain unnecessary types" point in [DESIGN.md](https://github.com/travisbrown/circe/blob/94379728f8c4d3c799c076d0257b191ce58195c7/DESIGN.md) and #133, and I think this doesn't go against those wishes.

**Comment by travisbrown** [comment]
I've been resisting adding macros to circe, but the seal is broken now, so I think we should consider this.

We'd have to change the language in the first item in the design doc a bit. The prohibition against annotations there is primarily intended to target member-level annotations, and I don't think this kind of thing (where the macro annotation is just nice syntax for `semiauto` definitions) is so bad.

We'd probably want something like `@ConfiguredJsonCodec[C]` in addition to `@JsonCodec` (or whatever they end up being called).

Are you interested in adding this, @dwijnand? I'm not sure I'd be able to get to it for a week or so.

**Comment by dwijnand** [comment]
I'm not against rolling up my sleeves and contributing, but I've a stack of sbt things I'd like to tend to, so I don't think I'll be able to get to it in a week or so.

**Comment by ngbinh** [comment]
This is something we love to have also.

**Comment by dwijnand** [comment]
Initial support for this is now in master (via #203).

Support for a proposed `@ConfiguredJsonCodec[C]` one could say is blocked on still pending #164.

**Comment by dwijnand** [comment]
I should rivisit the tail part of this given https://github.com/circe/circe/pull/429 is merged.

**Comment by travisbrown** [comment]
#429 includes `@ConfiguredJsonCodec` so I think we can close this.
