### ISSUE TITLE
Port circe-literal macros to Scala 3

### ISSUE THREAD

**Issue by travisbrown** [circe/circe#1677]
The circe-literal module provides compile-time JSON parsing with interpolation via a fairly complex Scala 2 macro (where part of the complexity is due to the approach we've taken to not imposing a runtime Jawn dependency on circe-literal users).

At some point we'll need to port this functionality to Scala 3 macros. I'm not very familiar with macro-based string interpolation in Dotty / Scala 3, but it should be doable.

**Comment by SethTisue** [comment]
https://github.com/typelevel/literally ? (relaying a suggestion from Twitter)

**Comment by armanbilge** [comment]
I think you "closed" this as of https://github.com/circe/circe/pull/1874, but not in the spirit of this issue:
> not imposing a runtime Jawn dependency on circe-literal users
