### ISSUE TITLE
Add BigInt support

### ISSUE THREAD

**Issue by b0l0k** [circe/circe#1714]
Hi,

After some research, it seems that the current implementation of BigInt encoding/decoding doesn't support the (future) BigInt JS type: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/BigInt

Could you confirm that my understanding is correct? Is there a development planned on that?

**Comment by travisbrown** [comment]
I don't see that as in scope for Circe, which aims to provide identical behavior across platforms (in most cases) with as little platform-specific code as possible. I don't know whether it would be in scope for Scala.js (in general I don't know anything about Scala.js), but if Scala.js used this `BigInt` in its implementation of `scala.BigInt`, Circe would benefit from that.

If Scala.js doesn't provide any way to work with this `BigInt`, I guess I wouldn't be opposed to having some kind of wrapper and codec in circe-scalajs, but it's not something I have any plans to work on myself.

**Comment by vbouzon** [comment]
@travisbrown I'm not sure to follow your answer, I think I was not clear. My question was more about the encoding of `scala.Bigint` and its representation in Json.

For now, a BigInt with Circe is encoded as simple number:
`case class MyClass(value: BigInt)`
will give
`{ value: 10000000000000000 }`
but with this new type, that should be:
`{ value: 10000000000000000n }``

**Comment by travisbrown** [comment]
Oh, sorry, I misunderstood, I thought you meant working with this `BigInt` type via Scala.js.

We don't currently have any support for non-JSON JavaScript syntax or any other non-JSON encodings, except via integration modules like circe-bson. It shouldn't be _too_ hard to implement a printer on the model of projects like circe-bson that would output almost-JSON but with this syntax, but it doesn't currently exist.

**Comment by b0l0k** [comment]
Can be closed, too old.
