### ISSUE TITLE
None.type decoder is inconsistent with the Option decoder

### ISSUE THREAD

**Issue by nigredo-tori** [circe/circe#1725]
[With Circe 0.14.0-M5](https://scastie.scala-lang.org/WPVpHLc1Tpy3woTM5ZsG9Q):

```scala
import io.circe._

val n = Json.obj()

// Produces Right(None)
n.as(Decoder[Option[Int]].at("foo"))
// Produces Left
n.as(Decoder[None.type].at("foo"))
```
`Decoder[Option[Int]]` overrides `tryDecode` and `tryDecodeAccumulating` to handle `FailedCursor`, but `Decoder[None.type]` does not.

**Comment by travisbrown** [comment]
Interesting, good catch. In general there's no guarantee that a decoder for a subtype has the same behavior as a supertype decoder for a value of the subtype (e.g. the default handling of sealed trait hierarchies in circe-generic), but in this case I don't think the difference is intended. I'd be happy to review a fix.
