### ISSUE TITLE
Bincompat issues because of dependency on shapeless 2.3.6

### ISSUE THREAD

**Issue by catostrophe** [circe/circe#1766]
Shapeless 2.3.6 introduced a bincompat issue described here:
https://github.com/milessabin/shapeless/pull/1158#issuecomment-838071648

The following release 2.3.7 fixed it via https://github.com/milessabin/shapeless/pull/1162

Circe 0.14 depends on shapeless 2.3.6.

Having shapeless 2.3.7 in classpath leads to a compiletime error:
```console
[error] Symbol 'type shapeless.ops.function.FnFromProduct.Aux' is missing from the classpath.
[error] This symbol is required by 'value io.circe.generic.decoding.IncompleteDerivedDecoders.ffp'.
```

`circe-generic` can't work with shapeless 2.3.7+

cc @joroKr21

**Comment by catostrophe** [comment]
All circe modules dependent on shapeless should be updated and re-released :(

**Comment by travisbrown** [comment]
Ugh, this is a reminder that I probably rely on Scala Steward a little too heavily.

Are people actually confident that Shapeless 2.3.7 fixes this problem? I thought I remembered hearing the same thing about 2.3.6. I haven't been following it at all and don't want to redo more releases than I have to.

**Comment by catostrophe** [comment]
Modules dependent on shapeless that may be affected:

* inner modules:
 -`circe-generic`
 -`circe-generic-simple`
 -`circe-literal`

* external repos:
  -`circe-generic-extras`

**Comment by plokhotnyuk** [comment]
Sorry, it was my PR for updating to 2.3.6 because other transitive dependencies already depend on shapeless 2.3.6:
```
[info] io.circe:circe-refined_2.13:0.14.0 [S]
[info]   +-eu.timepit:refined_2.13:0.9.25 [S]
[info]   | +-com.chuusai:shapeless_2.13:2.3.6 [S]
```

**Comment by travisbrown** [comment]
@catostrophe I get complaints when I try to decouple versions for the core modules, so I'll just do a general 0.14.1 if we're sure this will fix the problem. (Also circe-literal only has a test dependency on Shapeless, so it should be fine.)

**Comment by catostrophe** [comment]
> Ugh, this is a reminder that I probably rely on Scala Steward a little too heavily.
> 
> Are people actually confident that Shapeless 2.3.7 fixes this problem? I thought I remembered hearing the same thing about 2.3.6. I haven't been following it at all and don't want to redo more releases than I have to.

@joroKr21 reverted the breaking change and released it in 2.3.7.
The original issues can't be detected with MiMa unfortunately.

I, as one who discovered the issue with circe 0.13 and shapeless 2.3.6, can confirm that it works with circe 0.13 and shapeless 2.3.7.

**Comment by plokhotnyuk** [comment]
Shouldn't we wait for a new release of `refined` to avoid bincompat issues with other users of `refined`?

https://github.com/fthomas/refined/compare/v0.9.25...master

**Comment by catostrophe** [comment]
Also it was mention in https://github.com/circe/circe/issues/1750

**Comment by travisbrown** [comment]
@plokhotnyuk My understanding of the issue here is that when Refined publishes a 0.9.26 release with Shapeless 2.3.7 that should work fine with circe-refined 0.14.1, since we don't rely on any of the Shapeless-powered macros in the circe-refined implementation. Users will just have to specify the new Refined version explicitly instead of letting 0.9.25 get pulled in transitively, which is fine with me.

**Comment by joroKr21** [comment]
FTR that's not exactly a binary compatibility issue. It's pickling issue, meaning that either it will:
 1. Not compile when mismatching versions of `Tupler`, `FnFromProduct` or `FnToProduct` are used
 2. Compile and work fine at runtime (since the type aliases are erased)

I couldn't find any usage of those in `refined` so it should be fine either way.

**Comment by catostrophe** [comment]
Yes, sorry for the wrong title. Anyway, it's a blocking issue.

**Comment by travisbrown** [comment]
Done! https://github.com/circe/circe/releases/tag/v0.14.1

**Comment by travisbrown** [comment]
Also did circe-generic-extras: https://github.com/circe/circe-generic-extras/releases/tag/v0.14.1
