### ISSUE TITLE
Discriminant configuration for Scala 3's `derives` syntax

### ISSUE THREAD

**Issue by grzegorz-bielski** [circe/circe#1777]
Hi!

It'd be useful to have a way of configuring how `Encoder` works for ADTs in Scala 3, in particular with the `derives` syntax.

I have an ADT like this:
```scala
sealed trait Event derives Codec.AsObject

case class Foo(i: Int) extends Event
case class Qux(values: List[String]) extends Event

println(List[Event](Qux(List("a", "b", "c"))).asJson)
```
which produces a JSON like this:
```
[{"Qux":{"values":["a","b","c"]}}]
```
however, I'd like to have an output like this:
```
[{"values":["a","b","c"]}]
```
or like this:
```
[{ "type": "Qux", "values":["a","b","c"]}]
```

From my understanding, this is not possible with the current mechanism so my fallback solution is a custom  ` given Encoder` with a huge `match` for each of the statements. Unfortunately, this is pretty boilerplateish.

Are there any plans to support something like this for Scala 3 derivation?

**Comment by heksesang** [comment]
Hopefully it will be possible to get a configurable derivation in `circe-core` that does not depend on `given`s in Scala 3.

My suggestion is to implement the derivation in forms of traits that allow you to configure an object which exposes an extension method for `Codec`, `Decoder` and `Encoder`.

Simple conceptual illustration:
```scala
// In circe-core
trait Derivation extends SumDerivation, ProductDerivation:
  extension (io.circe.Codec)
    def derived[A]: Codec[A] = ...

trait SumDerivation(field: Option[String] = None)
  def deriveSumCodec[A]: Codec[A] = ...

// In my own project I create a derivation object
object MyDerivation extends Derivation, SumDerivation(field = Some("type"))

// Then I can use it like this
import MyDerivation.derived

enum A derives Codec:
  case B()
  case C()
```

**Comment by Lasering** [comment]
The renaming from circe-derivation could also be implemented in the Encoder/Decoder derivation using a `given` configuration class.

**Comment by Lasering** [comment]
I have a working implementation, supporting `transformNames`, `useDefaults`, and `discriminator`.

The `useDefaults` is the tricky one, see https://stackoverflow.com/questions/68421043/type-class-derivation-accessing-default-values. It requires the compiler flag `-Yretain-trees` in the build file of the users.

I can make a PR. I just need to know how to compile code in `modules/core/shared/src/main/scala-0`.
