### ISSUE TITLE
Styling in the Circe doc site is broken

### ISSUE THREAD

**Issue by Kevin-Lee** [circe/circe#1780]
# Summary
Styling in the Circe doc site is broken. I think it's been broken for a couple of weeks.

## Details
When I access https://circe.github.io/circe, I get the site looks like
![Screen Shot 2021-06-10 at 11 07 53 am](https://user-images.githubusercontent.com/2307335/121449258-c92ba180-c9dc-11eb-9841-56b6ba7716c3.png)
***
![Screen Shot 2021-06-10 at 11 08 10 am](https://user-images.githubusercontent.com/2307335/121449264-cb8dfb80-c9dc-11eb-8fec-dbf6a576bab1.png)
***
## Cause
The cause I found is that there are two missing css files.
From Chrome's developer tools:
![Screen Shot 2021-06-10 at 11 09 00 am](https://user-images.githubusercontent.com/2307335/121449347-f8421300-c9dc-11eb-8874-412269888e65.png)
![Screen Shot 2021-06-10 at 11 09 12 am](https://user-images.githubusercontent.com/2307335/121449353-fa0bd680-c9dc-11eb-993c-90e19d8ba445.png)

**Comment by travisbrown** [comment]
I've been meaning to look at this but haven't had time. If anyone can help I'd appreciate it.

**Comment by Kevin-Lee** [comment]
Ah... Ok. Let me try tonight (in Sydney AU time).

**Comment by Kevin-Lee** [comment]
@travisbrown `css` folder is missing on the `gh-pages` branch so I guess the css files were not pushed to the branch somehow.
How does circe publish the doc site? I don't see any doc site publishing script or config in GitHub Actions settings.
Is it done by a manual push from someone's local machine? If so, I don't have permission to do it.

Do you mind if I add GitHub Actions workflow to publish the doc site? 
I've already done it and here is the example of the result from the GitHub Actions work.
https://kevin-lee.github.io/circe

If it's OK, I will create a PR.

**Comment by travisbrown** [comment]
@Kevin-Lee The publishing is done by sbt-ghpages, which is a dependency of sbt-microsites. I run `sbt docs/clean`, `sbt docs/makeMicrosite`, and `sbt docs/ghpagesPushSite` manually after each release.

How are you getting that result? When I run the commands above locally `docs/target/site/` is indeed missing the `css` directory.

I'm inclined not to publish on every merge to `main` because in the past I've seen questions indicating that this can be confusing (when the documentation doesn't agree with the most recent published version). I don't have a strong opinion, though.

**Comment by travisbrown** [comment]
(@Kevin-Lee, thanks for looking into this, by the way.)

**Comment by travisbrown** [comment]
@Kevin-Lee Oh, I think this might be the issue: https://47degrees.github.io/sbt-microsites/docs/troubleshooting/

**Comment by Kevin-Lee** [comment]
@travisbrown This is what I did. It's the separate workflow for doc site build and publish.
https://github.com/Kevin-Lee/circe/blob/46573681a8fdb901294e6af9d75b9f4450bf4d4c/.github/workflows/docs.yml#L51

At first I did `docs/publishMicrosite` to publish but [it failed](https://github.com/Kevin-Lee/circe/runs/2793337860?check_suite_focus=true#step:7:207) as I don't have permission to publish it to circe's branch. So I used [another sbt plugin](https://sbt-github-pages.kevinly.dev/) which I can use with GitHub without setting up SSH key. I think `sbt-ghpages` requires it.
(This plugin is my own project to publish GitHub Pages with GitHub Actions without any security hassles like ssh key or GitHub API token).
***

I can make the GitHub Actions workflow a completely manual job so that you can publish it whenever you want from any branch you want. I can also add an additional workflow to just build the doc site without publishing. A benefit of separate workflow is that you can save time on building the projects.

Here is an example of what I said. The following files are GitHub Actions workflow files from my personal project. I always do this for my projects.
* Automatic doc site build: https://github.com/Kevin-Lee/maven2sbt/blob/main/.github/workflows/doc-site-build-only.yml
* Manual doc site build and publish: https://github.com/Kevin-Lee/maven2sbt/blob/main/.github/workflows/doc-site-publish.yml

***
> (@Kevin-Lee, thanks for looking into this, by the way.)

No, I should thank you for creating and maintaining this project. 🙂

**Comment by travisbrown** [comment]
I think updating my local Jekyll will fix it (I'm trying now). It'd be great to have an easy way to push to a branch and have it publish from there, though.

**Comment by Kevin-Lee** [comment]
@travisbrown Sorry it's over midnight here in Sydney so I need to go to bed, so I left the PR with the GitHub Actions workflows I talked about. I don't mind declining it. 🙂

The manual build+publish would look like this.
<img width="934" alt="Screen Shot 2021-06-11 at 12 37 15 am" src="https://user-images.githubusercontent.com/2307335/121544780-50186280-ca4d-11eb-8b9d-b824c859f935.png">

**Comment by travisbrown** [comment]
@Kevin-Lee Thanks again very much! Will get it merged as soon as possible.

**Comment by Kevin-Lee** [comment]
@travisbrown Thanks! Again, as I said, if you don't need / want / like it, it doesn't have to be merged. I think it's certainly convenient and also saves time, but it's up to you. I think you're busy with many other projects so I don't want to add one more issue.

By the way, if there are any issues related to GitHub Actions and if I can help, I'm happy to.

Thanks for fixing the styling. It's fine now but the doc menu is missing. 🥲  I guess the old `pattern` theme was removed from the `build.sbt`. Luckily I have this one https://kevin-lee.github.io/circe for now. 😆
![Screen Shot 2021-06-11 at 10 57 22 am](https://user-images.githubusercontent.com/2307335/121615311-ea0afa00-caa3-11eb-92ea-9ac3d97fbea5.png)
