### ISSUE TITLE
Encoding value classes and mapping type fields to snakeCase

### ISSUE THREAD

**Issue by SarpongAbasimi** [circe/circe#1806]
Hey, please I came across something today that I am not sure how to get around.
Out of curiosity how will this be implemented?. The `implicit val config: Configuration = Configuration.default....` works fine when there isn't an implicit `deriveUnwrappedEncoder`.

```
Currently when the code compiles I get

{
  "someFriends" : "two",
  "resUrl" : "One"
}

which is not what I want, I want

{
  "some_friends" : "two",
  "res_url : "One"
}
```

![JTyFSYOn jpg-medium](https://user-images.githubusercontent.com/37377831/128643698-d58c87f6-39a6-46f9-879f-ca6886735627.jpeg)

```

import io.circe._
import io.circe.generic.extras.semiauto._
import io.circe.generic.extras.defaults._
import io.circe.generic.extras._, io.circe.syntax._

final case class ResUrl(resUrl: String) extends AnyVal
object ResUrl {
implicit val config: Configuration = Configuration.default.copy(
  transformMemberNames = {
    case "resUrl" => "res_url"
    case other => other
  }
)
  implicit val resUrlEncoder: Encoder[ResUrl] = deriveUnwrappedEncoder[ResUrl]
}

final case class SomeFriends(someFriends: String) extends AnyVal
object SomeFriends {
implicit val config: Configuration = Configuration.default.copy(
  transformMemberNames = {
    case "someFriends" => "some_friends"
    case other => other
  }
  )
  implicit val resUrlEncoder: Encoder[SomeFriends] =
    deriveUnwrappedEncoder[SomeFriends]
}

final case class FooBar(someFriends: SomeFriends, resUrl: ResUrl)
object FooBar {
  implicit val foobarEncoder: Encoder[FooBar] = deriveEncoder[FooBar]
}

val a = FooBar(SomeFriends("two"), ResUrl("One"))
```

**Comment by SarpongAbasimi** [comment]
I also came across this during the process of exploring.
I am guessing something needs to be enabled for this to compile.

<img width="1439" alt="Screenshot 2021-08-08 at 14 01 05" src="https://user-images.githubusercontent.com/37377831/128643862-3a65eef2-c62e-4f74-8f48-9a335d9b4d3c.png">

**Comment by travisbrown** [comment]
The issue is probably that you don't have an implicit configuration in scope for the `FooBar` encoder derivation? If that doesn't resolve it, it'd be best to open this issue over at the [circe-generic-extras](https://github.com/circe/circe-generic-extras) repo.

**Comment by SarpongAbasimi** [comment]
thanks @travisbrown , I just added a configuration for the `FooBar` encoder derivation but that didn't solve it.
I will raise an issue at the `circe-generic-extras` repo.
