### ISSUE TITLE
Broken link to generic-extras in the generated API document

### ISSUE THREAD

**Issue by ShapelessCat** [circe/circe#1836]
https://github.com/circe/circe/blob/master/modules/core/shared/src/main/scala/io/circe/package.scala

```
*   - [[io.circe.generic.extras generic-extras]]: additional experimental generic
*     derivation functionality (including some configurability).
```
I guess this is because of #1254.

**Comment by travisbrown** [comment]
Ah, good catch. Happy to merge a fix.

**Comment by ShapelessCat** [comment]
@travisbrown Yes. I want to push the fix, but I don't know what is the right link.

**Comment by zmccoy** [comment]
Hi @ShapelessCat the link to use would be https://github.com/circe/circe-generic-extras.  If you'd like to update that I'd be happy to merge it.  I can also get that done if not.  Thank you for bringing this up!

**Comment by ShapelessCat** [comment]
Hi @zmccoy I'll do it soon. Thanks!

**Comment by zmccoy** [comment]
@ShapelessCat Awesome, thank you :)
