### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by omerlh** [circe/circe#1933]
Look like the latest version released is almost a year old (May 2021) and since then a lot of commits have gone into master, including version bump that fix security issues:
```
[info] Issues with no direct upgrade or patch:
[info]   ✗ Denial of Service (DoS) [Medium Severity][https://snyk.io/vuln/SNYK-JAVA-ORGTYPELEVEL-2331743] in org.typelevel:jawn-parser_2.13@1.2.0
[info]     introduced by <> > io.circe:circe-parser_2.13@0.15.0-M1 > io.circe:circe-jawn_2.13@0.15.0-M1 > org.typelevel:jawn-parser_2.13@1.2.0 and 1 other path(s)
[info]   This issue was fixed in versions: 1.3.2
```
Are there plans to release a new version soon? I saw `0.15.0-M1` but this is also pretty old...

**Comment by armanbilge** [comment]
The good news is that the security advisory actually did not affect circe.

> Unaffected implementations include:
> - `io.circe :: circe-parser`

https://github.com/typelevel/jawn/security/advisories/GHSA-vc89-hccf-rq55

**Comment by majk-p** [comment]
@zmccoy @zarthross any plans for releases?

**Comment by majk-p** [comment]
Perfect, thank you for the update!
If there's anything I can help you with, please let me know

**Comment by zarthross** [comment]
I think the CI changes are finally ready, so we should be able to do a release relatively soon.

**Comment by sergio-margale** [comment]
@zmccoy @zarthross will this release have `circe-generic-extras` on Scala 3?

**Comment by zarthross** [comment]
@sergio-margale Its safe to say that the next release won't include Scala 3 for circe-generic-extras.  It's certainly on the todo list to get that repo updated, and volunteers are certainly welcome.

**Comment by zarthross** [comment]
@TheKinrar we've got this PR ready to go, just waiting on review: https://github.com/circe/circe/pull/1948.  Once we get that merged we will be able to cut the next release.

**Comment by kubukoz** [comment]
Hey there @zarthross, that PR looks merged, can we get that release now?

Let me know if I can help :)

**Comment by zarthross** [comment]
I think we will be able to put together the release this week.

**Comment by zarthross** [comment]
v0.14.2 is going out to maven now, feel free to let us know if you have any issues.  @zmccoy is working on release notes, we'll get those published in the next few days.

**Comment by kubukoz** [comment]
it's up! Thanks a lot :)
