### ISSUE TITLE
argonaut link and why

### ISSUE THREAD

**Issue by johnynek** [circe/circe#1937]
on the circe page: https://circe.github.io/circe/

 we see this:

> Why?
> 
> [Argonaut](http://argonaut.io/) is a great library. It’s by far the best JSON library for Scala, and the best JSON library on the > JVM. If you’re doing anything with JSON in Scala, you should be using Argonaut.
>
> circe is a fork of Argonaut with a few important differences.

1. that seems pretty outdated. It made sense when circe was a new library and cats was new. But today, I don't think this a very helpful description of the motivation of the library.
2. Even if it good, the link seems to be dead and redirect somewhere unrelated.

**Comment by zarthross** [comment]
Agreed.  We should remove that.

**Comment by zmccoy** [comment]
This was cleaned up with #1939.
