### ISSUE TITLE
circe-scodec 0.14.2 not published for Scala 3

### ISSUE THREAD

**Issue by armanbilge** [circe/circe#1958]
- https://repo1.maven.org/maven2/io/circe/circe-scodec_2.12/
- https://repo1.maven.org/maven2/io/circe/circe-scodec_2.13/
- https://repo1.maven.org/maven2/io/circe/circe-scodec_3/

h/t @ahjohannessen

**Comment by zarthross** [comment]
Thanks @armanbilge, we'll get that fixed up ASAP.  Thanks for letting us know!

**Comment by armanbilge** [comment]
Woops, seems that circe-refined has the same problem. Probably, all the modules should be audited :(

https://repo1.maven.org/maven2/io/circe/circe-refined_2.12/
https://repo1.maven.org/maven2/io/circe/circe-refined_2.13/
https://repo1.maven.org/maven2/io/circe/circe-refined_3/

**Comment by zarthross** [comment]
@armanbilge If you feel like taking the time to set that up, we'll be happy to accept it.

**Comment by armanbilge** [comment]
While I'm at it, thoughts on migrating the circe site to the sbt-typelevel-site plugin as well, which uses Laika? I laid out the arguments in https://github.com/typelevel/cats/issues/4143.

**Comment by zarthross** [comment]
Not opposed to that, but lets do that as a separate effort if we can.  I'd prefer to be able to evaluate it separately from the CI changes.

**Comment by zarthross** [comment]
`circe-scodec` and `circe-refined` for scala3 should be going out to maven now.  I'll close this after i confirm.

**Comment by zarthross** [comment]
Looks like it's out now.
