### ISSUE TITLE
circe-generic-extras not published for Scala 2.13

### ISSUE THREAD

**Issue by slandelle** [circe/circe#1960]
Hello,

Similar to #1958 I guess. See https://repo1.maven.org/maven2/io/circe/circe-generic-extras_2.13/.

```
[error]   Not found
[error]   not found: /home/runner/.ivy2/localio.circe/circe-generic-extras_2.13/0.14.2/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/io/circe/circe-generic-extras_2.13/0.14.2/circe-generic-extras_2.13-0.14.2.pom
```

**Comment by andreamarcolin** [comment]
Same for circe-optics apparently

```
[error]   not found: https://repo1.maven.org/maven2/io/circe/circe-optics_2.13/0.14.2/circe-optics_2.13-0.14.2.pom
```

**Comment by zmccoy** [comment]
@armanbilge Is correct.  We're planning on doing those releases after we're confirmed in a good spot with the circe release.  We're checking out some other issues to make sure we can move forward and proliferate that onward.

**Comment by zmccoy** [comment]
I'm going to leave this open though so other folk see this as well if they come in with questions :)

**Comment by zmccoy** [comment]
This has been published, but circe-generic-extras has no guarantees that it follows the same semver since if it releases a patch it gets 1 higher than the circe-core versioning.

**Comment by slandelle** [comment]
@zmccoy Thanks! Maybe it was a coincidence the version number was the same so far, how how the original author used to release. Anyway, we're now using distinct version for our build now so scala-steward can successfully push upgrades.

Thanks a lot!
