### ISSUE TITLE
v0.14.2 introduced significant performance degradation

### ISSUE THREAD

**Issue by lzm0** [circe/circe#1972]
We use Circe in several Scala cron jobs. Last week or so, we upgraded Circe from `v0.14.1` to `v0.14.2`, and some cron jobs took several times longer to complete.

We ran some profiling and found that https://github.com/circe/circe/pull/1617/ caused this performance reduction by introducing a new `cursorToDecodingFailure` function in `modules/core/shared/src/main/scala/io/circe/Decoder.scala` that takes linear time to run.

### `Demo.sc`
```Scala
import io.circe.Codec
import io.circe.generic.extras.Configuration
import io.circe.generic.extras.semiauto.deriveConfiguredCodec
import io.circe.parser.decode

import java.util.UUID
import scala.io.Source

case class Cat(
    id: UUID,
    friends: Seq[Cat] = Seq.empty
)

object Cat {
  implicit final val configuration: Configuration = Configuration.default.withDefaults
  implicit val personDecoder: Codec[Cat] = deriveConfiguredCodec
}

case class Dog(
    id: UUID,
    friends: Option[Seq[Dog]] = None
)

object Dog {
  implicit final val configuration: Configuration = Configuration.default.withDefaults
  implicit val personDecoder: Codec[Dog] = deriveConfiguredCodec
}

val fileSource = Source.fromFile("uuid-10k.json")
val fileContent = fileSource.getLines.mkString
fileSource.close()

val catStartTime = java.lang.System.currentTimeMillis()
decode[Seq[Cat]](fileContent)
println(s"Time taken for cats: ${java.lang.System.currentTimeMillis() - catStartTime} ms")

val dogStartTime = java.lang.System.currentTimeMillis()
decode[Seq[Dog]](fileContent)
println(s"Time taken for dogs: ${java.lang.System.currentTimeMillis() - dogStartTime} ms")
```
### `uuid-10k.json`
```
[{"id":"19b10dec-91fe-42ee-8da7-2cafe9529dad"},{"id":"2da8de7d-02fe-479c-8293-4bebbd24c4ef"}, ... ]
```

## Result
```
Time taken for cats: 3758 ms
Time taken for dogs: 154 ms
```
`Cat`s and `Dog`s are pretty similar. Surprisingly, one is significantly slower than the other. I believe many people use the style in the case class `Cat` to represent potentially empty list fields. This will cause problems in some production environments once they switch to `v0.14.2`.

**Comment by zarthross** [comment]
Thanks for the report.  That is certainly concerning.  I'll look into this as soon as I can.

**Comment by lzm0** [comment]
When `useDefaults` is set to true in the configuration, Circe is still trying to invoke `cursorToDecodingFailure`. This should not happen.

**Comment by zarthross** [comment]
@lzm0 Can you reverse the order processing for cat and dog?  Or perform 2 cats and 2 dogs taking only the 2nd number?  I'm concerned you are operating on a cold JVM and so the cat number is artificially inflated.

**Comment by lzm0** [comment]
You are right. In `v0.14.1`, they do not perform differently.
```
Time taken for cats: 392 ms
Time taken for dogs: 38 ms
Time taken for cats: 13 ms
Time taken for dogs: 30 ms
Time taken for cats: 13 ms
Time taken for dogs: 30 ms
Time taken for cats: 17 ms
Time taken for dogs: 29 ms
Time taken for cats: 13 ms
Time taken for dogs: 25 ms
Time taken for cats: 10 ms
Time taken for dogs: 9 ms
```
However, the same issue persists in `v0.14.2` when parsing 10k UUIDs.
```
Time taken for cats: 5045 ms
Time taken for dogs: 42 ms
Time taken for cats: 3503 ms
Time taken for dogs: 12 ms
Time taken for cats: 3289 ms
Time taken for dogs: 9 ms
Time taken for cats: 3200 ms
Time taken for dogs: 8 ms
Time taken for cats: 3207 ms
Time taken for dogs: 7 ms
Time taken for cats: 3006 ms
Time taken for dogs: 6 ms
Time taken for cats: 3021 ms
Time taken for dogs: 7 ms
Time taken for cats: 2950 ms
Time taken for dogs: 6 ms
```

**Comment by zarthross** [comment]
👍 Thanks for re-running that.  We have some PRs in progress to hopefully help with that.  See https://github.com/circe/circe/pull/1974

**Comment by sbuzzard** [comment]
We saw similiar performance degradation when we moved from 0.15.0-M1 to 0.14.2 for a very large payload (list of 25k items (where it went from a few seconds well over a minute).  It was for one particular payload - still working on minimizing .  We do have some decoders that use ".or" combinators so maybe error handling overhead internally is causing?  Will post a minimization here if I can.  I moved back to 0.15 M-1 in the meantime.

**Comment by armanbilge** [comment]
@sbuzzard you can try `publishLocal`ing  https://github.com/circe/circe/pull/1974, the OP said it fixed their issues in https://github.com/circe/circe/pull/1974#issuecomment-1179361889. Would be nice to setup auto-snapshotting here.

**Comment by sbuzzard** [comment]
> 

Oh, nice - doing too many things at the same time and completely spaced on that - thanks.  Will try it out.

**Comment by sbuzzard** [comment]
yep, fixed my issue as well., thx.
