### ISSUE TITLE
no v0.14.2 artifacts for circe-optics with 2.12

### ISSUE THREAD

**Issue by yanns** [circe/circe#2014]
circe optics was released with scala 2.12 in version 0.14.1: https://repo1.maven.org/maven2/io/circe/circe-optics_2.12/0.14.1/
But there's no artifacts for the release 0.14.2 for this scala version.

**Comment by yanns** [comment]
Actually there is also no artifacts for scala 2.13.

https://repo1.maven.org/maven2/io/circe/circe-optics_2.13/0.14.2/ is a 404.

**Comment by armanbilge** [comment]
circe-optics is publish independently with independent version numbers.


https://github.com/circe/circe-optics

**Comment by yanns** [comment]
Thanks for the quick info!
