### ISSUE TITLE
No artifact for circe-generic-extras v0.14.3

### ISSUE THREAD

**Issue by cipriandrei10** [circe/circe#2031]
There is no artifact published for circe-generic-extras v0.14.3 in https://mvnrepository.com/artifact/io.circe/circe-generic-extras

**Comment by armanbilge** [comment]
circe-generic-extras is published from a different repository, with completely independent versioning of this repository. You should not count on the version numbers matching circe core :)

https://github.com/circe/circe-generic-extras/

**Comment by cipriandrei10** [comment]
oh, I see, my bad. thank you! 

noticed this issue https://github.com/circe/circe-generic-extras/issues/242 as well, would be nice though to have all circe releases under same version

**Comment by zarthross** [comment]
https://github.com/circe/circe-generic-extras/releases/tag/v0.14.3
