### ISSUE TITLE
No artifact for circe-optics v0.14.3

### ISSUE THREAD

**Issue by cipriandrei10** [circe/circe#2032]
There is no artifact published for circe-optics v0.14.3 in https://mvnrepository.com/artifact/io.circe/circe-optics

**Comment by armanbilge** [comment]
circe-optics is published from a different repository, with completely independent versioning of this repository. You should not count on the version numbers matching circe core :)

https://github.com/circe/circe-optics

**Comment by cipriandrei10** [comment]
oh, I see, my bad. thank you!
