### ISSUE TITLE
Bincompat problem with derivation in 0.14.4 on Scala 3

### ISSUE THREAD

**Issue by ybasket** [circe/circe#2089]
Hey,
first of all: Thank you for the library and the huge step forward #1800 brought. I found an issue with bincompat though:
If code using generic derivation on Scala 3 was compiled against an earlier 0.14 version of circe (in my case `sttp-apispec`), using it together with the new 0.14.4 may throw a `NoSuchMethodError`:
```
java.lang.NoSuchMethodError: 'scala.collection.Iterable io.circe.DerivedEncoder.encodedIterable$(io.circe.DerivedEncoder, scala.Product)'
```

The reason for that is that `encodedIterable` was not `inline` and got removed in #1800 (`DerivedEncoder` was kept package-private, but not the methods). Similar goes for `DerivedDecoder`, it has also a bunch of methods that are now removed.

Looking forward, one could (probably) either bring those back for bincompat and remove them in 0.15 or accept the breakage and ideally add a warning to the release notes.

**Comment by ahjohannessen** [comment]
I got the same issue 👍 for the fix

**Comment by zarthross** [comment]
Thanks for letting us know and for submitting the PR, we are looking into it.
