### ISSUE TITLE
[Bug] discriminator fails on class hierarchies with more than one level. 

### ISSUE THREAD

**Issue by kailuowang** [circe/circe#2096]
The code somehow picked up the middle-level abstract type name as the value for the discriminator rather than the concrete type. 

Here is a test
```scala
  {
    given Configuration = Configuration.default.withDiscriminator("type")
    sealed trait GrandParent derives ConfiguredCodec
    object GrandParent:
      given Eq[GrandParent] = Eq.fromUniversalEquals

    sealed trait Parent extends GrandParent

    case class Child(a: Int) extends Parent

    test("Codec for hierarchy of more than 1 level with discriminator should encode and decode correctly") {
      val child: GrandParent = Child(1)
      val json = Encoder.AsObject[GrandParent].apply(child)
      val result = Decoder[GrandParent].decodeJson(json)
      assert(result === Right(child), result)
    }
  }
```

The decode result:
```
Left(
  value = DecodingFailure at : type Parent has no class/object/case named 'Parent'.
)
```
cc @Lasering, sorry to bother you again. 

Update: I submitted PR #2098  to fix.

**Comment by Lasering** [comment]
I think the current behavior is the correct one. The Codec is being derived for `GrandParent` not for `Parent`, hence `Child` has the discriminator set to `Parent` (because child is a Parent from the point of view of GrandParent). If you derive the Codec for Parent you will get the correct result.

I don't see a way of correctly implementing this because what is the correct nest level for which the discriminator should be applied?
  
  1. Always at the bottom level (Child in this case)
  2. Always at the level of the Codec (as it is currently)
  3. At an arbitrary level? If so how would you set the level?

**Comment by kailuowang** [comment]
The current one isn't correct because you lose the type information by using `Parent` instead of `Child`.   The basic identity law for `Encoder` `Decoder` is that you can have a round trip from the `runtime instance of the type` -> json  -> `runtime instance of the type`.  `encode` and `decode` should be symmetric. 

If you encode a `Child` instance without registering its concrete runtime type, i.e. `Child`, then you won't be able to decode the json back to a `Child` instance, hence the error we saw.  Basically, the discriminator value of `Parent` isn't sufficient - it's obvious when you have multiple sub-types of `Parent`. 

The correct way to implement the discriminator is one that preserves all runtime type information and is capable of obeying the identity law. 
Thus `always at the bottom level` is the correct way because it is the actual runtime type of the data.

**Comment by Lasering** [comment]
Deriving the Codec for Parent will make a successful round-trip:
```scala
given Configuration = Configuration.default.withDiscriminator("type")
sealed trait GrandParent derives ConfiguredCodec
sealed trait Parent extends GrandParent derives ConfiguredCodec
case class Child(a: Int) extends Parent

val child: Parent = Child(1)
val json = Encoder.AsObject[Parent].apply(child)
val result = Decoder[Parent].decodeJson(json)
// result will be Right(child)
// If you want you can then upcast result to be of type GrandParent,
// this solves the ambiguity when there are multiple sub-types of `GrandParent`
```


> Thus `always at the bottom level` is the correct way because it is the actual runtime type of the data.

How would you handle this?

```scala
given Configuration = Configuration.default.withDiscriminator("type")
sealed trait Root derives ConfiguredCodec

sealed trait Level1_1 extends Root
case class Foo() extends Level1_1

sealed trait Level1_2 extends Root
case class Foo() extends Level1_2
```

Both `Foo`s will have the same discriminator (`"type": "Foo"`), preventing you from decoding an instance of `Foo` to `Root`.

Also note that discriminator was implemented to be in parity with circe-generic-extras.

**Comment by kailuowang** [comment]
First of all, `circe-generic-extras` handles this situation correctly. I reported this because this is a regression.

> Deriving the Codec for Parent will make a successful round-trip

That's because `Parent` only has one level below, thus, `Encoder.AsObject[Parent]` used the bottom type `Child` as the discriminator, which is the correct value, it didn't use `Parent`. 
In most real use cases, you shouldn't need to derive one for each level. Only needed for the top level. 

> How would you handle this?

That code won't compile. You will have to declare the two classes in different namespaces.  The uniqueness of the type name is a completely different problem. The existing implementation suffers the same problem. I don't see how it's relevant to the problem at hand.

**Comment by Lasering** [comment]
I'm sorry for the major blunder of my previous post. I assumed circe-generic-extras could not handle this case.
