### ISSUE TITLE
Not found io.circe:circe-numbers_2.12:0.14.5

### ISSUE THREAD

**Issue by plokhotnyuk** [circe/circe#2106]
The sbt cannot find circe-core dependency:
```
[error] sbt.librarymanagement.ResolveException: Error downloading io.circe:circe-numbers_2.12:0.14.5
[error]   Not found
[error]   Not found
[error]   not found: /home/andriy/.ivy2/local/io.circe/circe-numbers_2.12/0.14.5/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/io/circe/circe-numbers_2.12/0.14.5/circe-numbers_2.12-0.14.5.pom
```
W/A is using `dependencyOverrides` with some older version for `circe-numbers_2.12` like [here](https://github.com/plokhotnyuk/jsoniter-scala/commit/85b0879f9afc267e1074021c81fce850fd2d7a36#diff-5634c415cd8c8504fdb973a3ed092300b43c4b8fc1e184f7249eb29a55511f91R206)

**Comment by armanbilge** [comment]
Hmm, are you sure? You mean this one? I can see it.
https://repo1.maven.org/maven2/io/circe/circe-numbers_2.12/0.14.5/circe-numbers_2.12-0.14.5.pom

**Comment by plokhotnyuk** [comment]
[Now it works fine](https://github.com/plokhotnyuk/jsoniter-scala/commit/3fca93d2f1190bfa79119ca01310817790366d40), probably I did the upgrade during the promotion of release
