### ISSUE TITLE
Bad encoding of Option in scala 2.12

### ISSUE THREAD

**Issue by gffuma** [circe/circe#2133]
Encoding an `Option` of a case class with a field `Option[Map]` fails on scala 2.12

```scala
import io.circe._, io.circe.generic.auto._, io.circe.parser._, io.circe.syntax._
case class A(
  m: Option[Map[String, String]],
)
val x = Option(A(m=None))
println(x.asJson.noSpaces)
```
On scala 2.12:
`{"m":[]}`
On scala 2.13 is ok:
`{ "m": null }`

**Comment by milespossing** [comment]
Did you ever get to the bottom of this? I'm experiencing exactly this behavior as well

**Comment by hamnis** [comment]
This only happens with auto encoders.
I'm guessing that there is a new Option encoder created by the auto macro and then this breaks.

If you use semiauto this works:

https://scastie.scala-lang.org/0otpykCGR26uz26ixhSEzA
