### ISSUE TITLE
Scala3 derivation incorrectly assumes collection type for generic class

### ISSUE THREAD

**Issue by hamnis** [circe/circe#2199]
```scala
// scala-cli --dep "io.circe::circe-core::0.14.6"
// Welcome to Scala 3.3.0 (17.0.8.1, Java OpenJDK 64-Bit Server VM).
// Type in expressions for evaluation. Or try :help.
                                                                                                                               
scala> import io.circe.*
                                                                                                                               
scala> case class Foo[A](value: A) derives Decoder
// defined case class Foo
                                                                                                                               
scala> case class Bar(int: Int)
// defined case class Bar
                                                                                                                               
scala> val instance = Foo(Bar(1))
val instance: Foo[Bar] = Foo(Bar(1))
                                                                                                                               
scala> import io.circe.syntax.*
                                                                                                                               
scala> instance.asJson
-- [E172] Type Error: ----------------------------------------------------------
1 |instance.asJson
  |               ^
  |No given instance of type io.circe.Encoder[Foo[Bar]] was found for parameter encoder of method asJson in class EncoderOps.
  |I found:
  |
  |    io.circe.Encoder.encodeIterable[Bar, Foo](
  |      io.circe.Encoder.importedEncoder[Bar](
  |        /* missing */summon[io.circe.export.Exported[io.circe.Encoder[Bar]]]),
  |    ???)
  |
  |But no implicit values were found that match type io.circe.export.Exported[io.circe.Encoder[Bar]].
  |
  |One of the following imports might make progress towards fixing the problem:
  |
  |  import io.circe.Encoder.AsArray.importedAsArrayEncoder
  |  import io.circe.Encoder.AsObject.importedAsObjectEncoder
  |  import io.circe.Encoder.AsRoot.importedAsRootEncoder
  |
1 error found
```

**Comment by MartinHH** [comment]
The reported behavior is not cause by `circe`. The (wrong) import suggestions are provided by [scala 3 import suggestions](https://www.scala-lang.org/blog/2020/05/05/scala-3-import-suggestions.html):

You try to call `instance.asJson` which requires an implicit (aka given) `Encoder[Foo[Bar]]`, but there is none in scope. So the compiler deliberately tries to come up with some suggestions for imports that might fix the problem. Apparently (so far), it is not very good at that as soon as the available implicits within the codebase become a bit more complex.

For a non-circe example, you could try the following in your repl session:

```
scala> val ls: List[Foo[Bar]] = Nil
val ls: List[Foo[Bar]] = List()
                                                                                                                                      
scala> ls.sorted
-- [E172] Type Error: ----------------------------------------------------------
1 |ls.sorted
  |         ^
  |No implicit Ordering defined for B..
  |I found:
  |
  |    scala.math.Ordering.comparatorToOrdering[B](
  |      /* missing */summon[java.util.Comparator[B]])
  |
  |But no implicit values were found that match type java.util.Comparator[B]
  |
  |where:    B is a type variable with constraint >: Foo[Bar]
  |.
  |
  |One of the following imports might make progress towards fixing the problem:
  |
  |  import cats.implicits.catsKernelOrderingForOrder
  |  import cats.instances.all.catsKernelOrderingForOrder
  |  import cats.instances.order.catsKernelOrderingForOrder
  |  import cats.kernel.Order.catsKernelOrderingForOrder
  |  import cats.kernel.instances.order.catsKernelOrderingForOrder
  |
1 error found
```
The suggestions involve a bunch of `Ordering`-related conversions, but none of them would provide a solution for the missing `Odering[Foo[Bar]]`.

(Notice that the wording is "One of the following imports **_might_ make progress towards fixing the problem**" - it is not even claiming that the import _will_ make progress.)

**Comment by hamnis** [comment]
sure, but Adding `case class Foo[A](value: A) derives Decoder` I would expect the derived macro to actually synthesize an instance for Foo. I do not understand why that does not report an error, since it should be unable to to that.

**Comment by MartinHH** [comment]
A. (This is probably not the point of your question, but...:) `Decoder` is for decoding json to objects, you're trying to encode and thus need an `Encoder` (or a `Codec` which is the combination of both). Derivation of `Encoder`s and `Codec` is only supported for `Encoder.AsObject`/`Codec.AsObject` - so let's do this:
```
scala> case class Foo[A](value: A) derives Encoder.AsObject
// defined case class Foo
```

B. At this point, since the type of `value` is generic, the derived Encoder cannot be synthezied completely (because the encoding of `value` depends on the type of `A`).
The synthesized code is rather equivalent to:
```
object Foo:
  given encodeFoo[A](using encodeA: Encoder[A]): Encoder[Foo[A]] =
    // ... (Encoder that will delegate encoding of value to encode A)
```
Thus, we'd will still get an error if we don't provide an `Encoder[Bar]`.

What will work (after you make `Foo` derive `Encoder.AsObject`) is this:
```
scala> case class Bar(int: Int) derives Encoder.AsObject
// defined case class Bar
                                                                                                                                                                                 
scala> val instance = Foo(Bar(1))
val instance: Foo[Bar] = Foo(Bar(1))
                                                                                                                                                                                 
scala> instance.asJson
val res0: io.circe.Json = {
  "value" : {
    "int" : 1
  }
}

```


> I do not understand why that does not report an error, since it should be unable to to that.

I'm not an expert for the internals of the Scala 3 `derives` mechanism, but (as already hinted above), derivation will be applied "partially" for generic types.

You can also try this with the `Eq` [example from the official docs](https://docs.scala-lang.org/scala3/reference/contextual/derivation.html#) - you can do `case class Foo[A](value: A) derives Eq`, and once you have that, you can `summon[Eq[Foo[Int]]]` because there is an instance of `Eq[Int]`, but you cannot `summon[Eq[Foo[String]]]` because there is no instance of `Eq[String]`.

**Comment by hamnis** [comment]
Oh my god I am an idiot. Yes of course. I was trying to help a colleague here and was just too engrossed in why they didn't get this to work. Obviously I need an encoder to encode.

Closing this issue.
