### ISSUE TITLE
Cannot derive Encoder/Decoder for a case class containing members with shapeless-tagged refinements.

### ISSUE THREAD

**Issue by liff** [circe/circe#220]
Even though this is apparently [a known limitation](https://gitter.im/travisbrown/circe?at=56d8968ab01413547d89f8b3), I'm opening an issue in hopes that it can get fixed in the future, or at least, to document the problem. Like @fthomas pointed out, alexarchambault/argonaut-shapeless#31 is likely an instance of the same issue.

The problem is that while the codecs for the refined types are generic over the `RefType` (i.e. `Refined` or `@@`) the derivation fails for a case class that has fields with `@@` as their `RefType`.

For example, this will fail to compile:

``` scala
import eu.timepit.refined.numeric.Positive
import io.circe.refined._
import io.circe.generic.semiauto._
import shapeless.tag.@@

case class Foo(i: Int @@ Positive)

object Foo {
  implicit val fooEncoder: Encoder[Foo] = deriveEncoder[Foo]
}
```

It works, as documented, with `Refined` instead of the tag:

``` scala
import eu.timepit.refined.api.Refined

case class Foo(i: Int Refined Positive)
```

Adding an explicit `Encoder` for the refined type also works:

``` scala
object Foo {
  implicit val positiveIntEncoder: Encoder[Int @@ Positive] = refinedEncoder
  implicit val fooEncoder: Encoder[Foo] = deriveEncoder[Foo]
}
```

Thus, as a workaround right now, if one wants to use refined types with `@@` one solution seems to be to explicitly materialize the Encoder/Decoder instances for any specific refined types in the companion or a nearby package object.

**Comment by fthomas** [comment]
It would be interesting to know if this has also been fixed by https://github.com/circe/circe/pull/617.

**Comment by liff** [comment]
@fthomas no, unfortunately: https://scastie.scala-lang.org/liff/QL1P7LGlTTGfdY7hwdJ17A

**Comment by hamnis** [comment]
Closing in cleanup run, If anyone cares about this, please comment and I'll reopen.
