### ISSUE TITLE
Invalid Json tree with `null` (java) values, NPE in printer

### ISSUE THREAD

**Issue by zorba128** [circe/circe#2221]
I spent quite a lot of time trying to figure out why I get
```
java.lang.NullPointerException: Cannot invoke "String.length()" because "value" is null
```
somewhere from inside circe json printer. 
Stack trace did not help much - json rendering to string happens as the very last stage in processing pipeline of async web server - so no context can be retrieved from there.

See sample below for illustration:
```
 val a = json"""{"v": null}""" // 1
  println(a.noSpaces) // 2

  val b = json"""{"v": ${null: String}}""" // 3
  println(util.Try { b.noSpaces }) // 4
  println(util.Try { b.toString()} ) // 5

  val c = json"""{"v": ${System.getProperty("MY_PROPERTY")}}""" // 6
  println(util.Try { c.noSpaces }) // 7

  val d = JsonObject("v" -> Json.fromString(null)).toJson // 8
  println(util.Try { c.noSpaces }) // 9
```

Long story short - I think its wrong that circe allows to successfully construct Json tree, that is actually invalid and causes basic operation of rendering json to string to fail with cryptic NPE.

I see two options:
1. make sure its impossible to construct `JString(null)` at all. Just throw `IllegalArgumentException` in the constructor/builder.
2. let Json.fromString() create JString/JNull depending on what was the input.

I'd actually vote for first solution - lets simply be strict. If you create string json node - then pass string and not some special `null` value. With that change, rather than getting exceptions in lines 4,5,7,9 one would get it in 3,6,8. It seems way better for me, cause this is the place where problem is to be solved.

I'm working on large scala/java project, and in java its really often to get unexpected `null` here and there. Due to programming error, due to bug in library, due to mired specs - but it happens. And it happened to me resulting in json tree successfully constructed, processed, passed through several layers - to fail on far end.
Note - such `Json` instance fails even when .toString is invoked. So everything including
```
val json = .... // something that unintentionally injects java `null` to JString.
try { process(json) }
catch { case NonFatal(e) => throw new InvalidInputException("Error processing input $json") }
```
will behave not the way one would expect (code above produces NPE rather than business error; with stacktrace that tells nothing about root cause of issue).

== added ==
I know in Scala one easily forgets about `null` existence - and I really love world without NPEs popping up out of nowhere.
I'm far from adding `require(xxx != null) for every argument of every method. But I somehow feel having core types representing json tree with that check would make library much safer.

And json building (manual, interpolation, whatever) is a place I'd consider as "high risk" - this is where data from outside world
enters our strongly typed, null-safe world.

mk.

**Comment by hamnis** [comment]
I strongly believe that we should not fix this. 

Users of Java libraries must always handle the possiblity of nullable values by wrapping them in `Option(javaValue)`.

You should always have an anti-corrpution scala wrapper for your java code, so these kinds of issues do not happen.

If we start opening up for this, then we have to add this guard everywhere, that is not a desirable place to be in.
