### ISSUE TITLE
Consider providing a history-to-selection-path printing helper

### ISSUE THREAD

**Issue by travisbrown** [circe/circe#224]
In #222 @tobias-johansson added a `Show` instance for `DecodingFailure` that provides a handy path representation of the history:

``` scala
DecodingFailure at .bar.baz.qux.a: String
DecodingFailure at .bar.baz.qux.b: Boolean
DecodingFailure at .bar.baz.i[2]: Int
```

I was just wondering whether it might make sense to factor out the path-printing part to something like a `def opsToPath(history: List[HistoryOp]): String` method on the `HistoryOp` companion object that would be usable in other contexts. For example, I could imagine Finch users wanting to prepare a custom error message from a `DecodingFailure` that would use the nice path part without the `DecodingFailure at…` context.

What do people think?

**Comment by tobias-johansson** [comment]
@travisbrown I think breaking this out is a good idea.
Originally I created a `Show[List[HistoryOp]]` in the `HistoryOp` companion object, but it felt a bit weird defining a Show for a specific type parametrization of List, and also potentially confusing having both that and the default `Show[List[A]]` from Cats available.
So a function `def opsToPath(history: List[HistoryOp]): String` sounds good

**Comment by hamnis** [comment]
Closing in cleanup run, If anyone cares about this, please comment and I'll reopen.
