### ISSUE TITLE
flaky test PointerInterpolatorSuite

### ISSUE THREAD

**Issue by hamnis** [circe/circe#2253]
==> X io.circe.pointer.literal.PointerInterpolatorSuite.The pointer string interpolater should work with arbitrary interpolated strings  0.218s munit.FailException: /home/runner/work/circe/circe/modules/pointer-literal/src/test/scala/io/circe/pointer/literal/PointerInterpolatorSuite.scala:67
66:    }
67:  }
68:

Failing seed: Qog3ld-wUt4pxd9v26eGjgOxH6rqZcekY3hDbU8ibDG=
You can reproduce this failure by adding the following override to your suite:

  override def scalaCheckInitialSeed = "Qog3ld-wUt4pxd9v26eGjgOxH6rqZcekY3hDbU8ibDG="

Falsified after 10 passed tests.
> Labels of failing property: 
Expected Right(/foo/~0/bar) but got Left(io.circe.pointer.PointerSyntaxError: Syntax error at 5; expected: token character)
> ARG_0: "~"
> ARG_0_ORIGINAL: "搳ᶈ쫽~1繕뺦ꭻ髯⺔蓵"

**Comment by hamnis** [comment]
another instance here:

==> X io.circe.pointer.literal.PointerInterpolatorSuite.The pointer string interpolater should work with arbitrary interpolated strings 0.08s munit.FailException: /home/runner/work/circe/circe/modules/pointer-literal/src/test/scala/io/circe/pointer/literal/PointerInterpolatorSuite.scala:63
62:
63:  property("The pointer string interpolater should work with arbitrary interpolated strings") {
64:    Prop.forAll(ScalaCheckInstances.genPointerReferenceString) { (v: String) =>

Failing seed: 1OjBrYKS0lJD-J7FkVohKcjGjrfy2vHrVIMFnxV8N9M=
You can reproduce this failure by adding the following override to your suite:

  override def scalaCheckInitialSeed = "1OjBrYKS0lJD-J7FkVohKcjGjrfy2vHrVIMFnxV8N9M="

Falsified after 61 passed tests.
> Labels of failing property: 
Expected Right(/foo/~0/bar) but got Left(io.circe.pointer.PointerSyntaxError: Syntax error at 5; expected: token character)
> ARG_0: "~"
> ARG_0_ORIGINAL: "㜸畫‪뿶Ρⰳ蟵뫋ꔀ긯⏈铌弃䔇偦醴悩쏔〖삄鸡᤾쳡㈢ꭇ僎欺꾚ᦿ䶬㒬声鞄㌥吘틉闆~0碨게盡㔝䞌"

**Comment by MartinHH** [comment]
See also #2160
