### ISSUE TITLE
Refined version update for JS and JVM

### ISSUE THREAD

**Issue by lpawlak1** [circe/circe#2267]
Hi team,

Based on links below I can see that refinedVersion has not been bumped due to bin compat concerns, are there any plans to bump it in near future? 

This would allow to move to Scala 3 in some projects as shapeless in 2.13 scala version is used in refined version 0.9.29 and they removed this dependency in 0.11.1

Thanks, Łukasz

https://github.com/circe/circe/pull/2047
https://github.com/circe/circe/pull/2231

**Comment by hamnis** [comment]
#2231 has already been merged.

**Comment by lpawlak1** [comment]
Hey,

based on this snippet from `build.sbt`

```scala
lazy val refined = circeCrossModule("refined")
  .settings(
    tlVersionIntroduced += "3" -> "0.14.3",
    libraryDependencies ++= {
      val refinedV =
        if (crossProjectPlatform.value == NativePlatform) refinedNativeVersion
        else refinedVersion
      Seq(
        "eu.timepit" %%% "refined" % refinedV,
        "eu.timepit" %%% "refined-scalacheck" % refinedV % Test
      )
    },
...
```

```scala
val refinedVersion = "0.9.29"
val refinedNativeVersion = "0.11.1"
  ``` 
  
  Refined was actually bumped only for NativePlatform, but not for JVMPlatform :/ 
  
  Is this possible to add version bump also for JVMPlatform? 😃

**Comment by hamnis** [comment]
oh, i didnt realize. Will have a look.

**Comment by hamnis** [comment]
will be done as part of #2276
