### ISSUE TITLE
Proposed design changes for decoding

### ISSUE THREAD

**Issue by travisbrown** [circe/circe#228]
I've discussed the idea outlined below with a few people (in person at the Typelevel summit last week, etc.), but it's somewhat relevant to the plans in #226, so I decided it's time to go ahead open an issue for it.

Paul Chiusano has a [blog post](https://pchiusano.github.io/2014-08-12/zippers-not-useful.html) where he argues that cursors aren't the right abstraction for things like JSON decoding. They're too powerful—they provide modification operations that don't make sense at all in the context of decoding and navigation operations (moving _up_ the tree) that are probably always a bad idea there.

So far I've stuck with Argonaut's cursor-based model for decoding because it's a simple solution if you want to be able to track history during decoding and already have a nice cursor implementation lying around. The full power of cursors is useful in non-decoding contexts, so we don't want to strip out the parts that are unnecessary for decoding, which means we'd need a new mechanism that looks a lot like a cursor without those parts. So far that hasn't seemed worth the effort.

I think that I'd like to make this change in circe 0.5. You'll still be able to construct decoders from `HCursor => Decoder.Result[A]`, but the preferred route will be to use a new algebra that provides a more limited set of navigation operations. You build up your decoder using these operations and then interpret it into one of several contexts:
- `Option` if you want fail-fast decoding with no history or position information.
- `Xor[DecodingFailure, ?]` for fail-fast decoding with history / positions.
- `ValidatedNel[DecodingFailure, ?]` for error accumulation with history / positions.

This has a handful of advantages. The first is just that as an abstraction it fits the problem more elegantly—it's less possible to construct nonsensical decoders (e.g. decoders that make modifications that will just be thrown away or decoders that snoop around higher up the document than the current focus).

The second advantage is that it supports potential optimizations that the current model doesn't. Most obviously, if you don't care about having position information to put in your error messages, you don't have to pay the cost of tracking history as your decoder moves around the document. It also may be possible to rearrange navigation operations to avoid unnecessary work (that's probably further down the line, though).

The goal would be to make this switch without breaking existing code (at least for a deprecation cycle), but it would be a major change, and some decoders you can write right now simply wouldn't be possible under the new model (only uselessly strange ones, I hope).

Does this seem reasonable for circe 0.6? Any objections or concerns?

**Comment by longcao** [comment]
We spoke about this offline at Typelevel Summit last week and I know I would be interested (hopefully others too) in what kind of optimizations would be possible here! Do I smell a new blog post?

All in all, it seems reasonable for an `0.5` cut. What would you call it if it's not so much a Cursor?

**Comment by arnihermann** [comment]
Sounds very nice to me. I've only needed fail-fast decoding without history on multiple occasions.

**Comment by tobias-johansson** [comment]
Both this proposal and #226 sound great

**Comment by travisbrown** [comment]
For what it's worth this is almost definitely happening in circe 0.10.0. I have an experiment that's 90%-ish source compatible, is slightly faster with like 30% fewer allocations, and supports the possibility of interpreters for non-circe ASTs or even stuff like BSON, so I'm pretty confident the idea is a good one.

**Comment by hamnis** [comment]
Closing in cleanup run, If anyone cares about this, please comment and I'll reopen.
