### ISSUE TITLE
Compilation order causing implicit search problem

### ISSUE THREAD

**Issue by ChetanBhasin** [circe/circe#235]
While working on a project I have encountered a really strange issue. The compilation order can effect the implicit decoder/encoder search in the program.

If a case class extending a selaed trait is not compiled before the call, scala compiler is not automatically able to find the dependency.
I tried commenting out the code where the call was made, compile using SBT, the uncomment the call and compile again on top of existing classes which have already been compiled — and it works.

So far, the workaround I have found is to use a multi-project build using SBT to make sure that the required classess which need to be converted to JSON are always compiled first (putting them in the project dependency).

This looks more like a problem on Scala compilers' side, however, I'm curious if there is something we can do about it at library level.

**Comment by antonkulaga** [comment]
I have the same nightmare =(

**Comment by travisbrown** [comment]
Does using `semiauto` instead of `auto` help?

**Comment by antonkulaga** [comment]
semiauto did not change anything for me by that time.

**Comment by ngbinh** [comment]
same thing happens to me.

**Comment by travisbrown** [comment]
Does anyone have a minimization of this problem that isn't equivalent to the code in the second point of the list of [warnings](https://github.com/travisbrown/circe#warnings-and-known-issues) in the README? I think it's pretty likely we're stuck with this (thanks, scalac), but I'd like to be sure.
