### ISSUE TITLE
Modernize Scala.js build

### ISSUE THREAD

**Issue by travisbrown** [circe/circe#259]
@ngbinh has done [some work](https://github.com/typelevel/cats/pull/954) on the Scala.js build for Cats that looks like it'd be valuable here as well (maybe we could even have Travis CI running the Scala.js builds!) but I know nothing about Scala.js build config and don't want to just cargo cult it.

If someone who knows / cares about Scala.js wants to help, that'd be awesome.

**Comment by ngbinh** [comment]
I can give it a shot!

**Comment by jonas** [comment]
As of Scala.js version 0.6.13 proposed settings are now [the defaults](https://www.scala-js.org/doc/project/js-environments.html) except for the batch mode:

> By default, `jsEnv` is set to use Node.js, which you need to install separately. If your application or one of its libraries requires a DOM, you will also need to install jsdom

**Comment by travisbrown** [comment]
I'm closing this since I think a lot of the work that's happened over the last seven months has brought us more or less up to speed.
