### ISSUE TITLE
Json diff

### ISSUE THREAD

**Issue by agourlay** [circe/circe#281]
It would be really handy for debugging and error reporting to have the possibility to compute the difference between two Json values.

I would love to migrate to Circe but I need this feature, therefore I am still using Json4s which has a diff API returning:
 `Diff(changed: JValue, added: JValue, deleted: JValue)` see implementation [here](https://github.com/json4s/json4s/blob/3.4/ast/src/main/scala/org/json4s/Diff.scala#L57)

Maybe there is already a way of achieving this easily?

Thank you for this nice library.

**Comment by travisbrown** [comment]
I've been meaning to provide something similar to this powered by [delta](https://github.com/stacycurl/delta), which already includes [a module for Argonaut](https://github.com/stacycurl/delta/blob/master/argonaut/src/test/scala/sjc/delta/argonaut/RFC6902JsonSpec.scala) that should be fairly straightforward to adapt for circe.

It doesn't provide exactly the same kind of diff as Json4s, though, but it has support for both [JSON Patch](https://tools.ietf.org/html/rfc6902) and a compressed representation, and I'd guess it shouldn't be too hard to adapt one of those formats to do what you need.

**Comment by agourlay** [comment]
Just wanted to share for the people interested in this feature that I was able to ```port``` the Json4s implementation to Circe.

It is not super good looking and does a bunch of ugly Option.get but it seems like it gets the job done.
 
Check this [PR](https://github.com/agourlay/cornichon/pull/76/files#diff-9bb98c6e70d073846c9f3856282b3119R7) for some code.

**Comment by guersam** [comment]
There's https://github.com/gnieh/diffson which will [support circe very soon](https://github.com/gnieh/diffson/pull/35).

**Comment by satabin** [comment]
> There's https://github.com/gnieh/diffson which will support circe very soon.

Support for circe was just merged. Version 2.1.0 with this support will be released next week.

**Comment by agourlay** [comment]
diffjson looks great, I will definitely try it 👍

**Comment by agourlay** [comment]
Coming back to you guys with some update.
I have been using successfully ```diffson``` as alternative and it is working great for me so far.

From my perspective this issue can be closed from the time being.
Thanks @satabin for the sweet lib 👍

**Comment by satabin** [comment]
Glad it helps. Do not hesitate to report bugs or ask for enhancements if you find anything.
