### ISSUE TITLE
Consider using Java 8+ classes in core

### ISSUE THREAD

**Issue by travisbrown** [circe/circe#318]
Recently there have been a few cases I've heard of of people needing `java.time` instances and not finding the ones in circe-java8. We could address this in documentation, but I'm tempted to bring these instances into circe-core without formally dropping Java <8 support. We'd just provide some very clear warnings indicating that calling the instance methods directly will result in access errors.

Pros:
- Easier discovery of `java.time` instances.
- No need for additional imports.
- We've got a lot of subprojects and getting rid of one would help clean things up a little.

Cons:
- We're exposing methods in our core API that we know won't work on Java 7.
- The warnings are additional documentation to maintain.

A related question is whether we'd want to use Java 8+ classes in places that aren't instances for Java 8+ types (like a `Decoder[ByteBuffer]`—see #193). I'm more hesitant to do this without dropping Java <8 support, but we could consider it.

**Comment by vkostyukov** [comment]
I wonder if there is a Java 7 & Java 8 compatible way of encoding/decoding Base 64 strings. Twitter's Util used to depend on Apache Commons version, but SO says there is this weird API that *I think* is supported in both versions (not sure how performant it is though):

```java
import javax.xml.bind.DatatypeConverter;

public class f{

   public static void main(String a[]){

      String str = new String(DatatypeConverter.printBase64Binary(new String("user:123").getBytes()));
      String res = DatatypeConverter.parseBase64Binary(str);
      System.out.println(res);
   }
}
```

**Comment by travisbrown** [comment]
`DatatypeConverter` runs us into Scala.js compatibility issues, though, since at least the last time I checked it wasn't supported (or `Base64`, for that matter).

**Comment by travisbrown** [comment]
This is done in [0.12.0-M3](https://github.com/circe/circe/releases/tag/v0.12.0-M3).
