### ISSUE TITLE
Feature request: support decoding with a normal cursor, not an HCursor

### ISSUE THREAD

**Issue by cb372** [circe/circe#329]
I'm doing some memory profiling of a high-traffic API that uses Circe to decode a lot of large JSON objects. I noticed that decoding allocates a large number of `HistoryOp$El` objects, which is causing the GC to really struggle, eventually leading to Full GC pain.

![screen shot 2016-07-25 at 11 28 30](https://cloud.githubusercontent.com/assets/106760/17098672/94873118-525b-11e6-9874-ad98c7ee2113.png)

Here you can see we have 2.7 million `HistoryOp$El` objects on the heap. At the time I took this snapshot, every single one of them was garbage waiting to be collected. 

For our use case, we don't care about having nice `DecodingFailure` messages (we're happy to just log the entire JSON object if it fails to decode), so we have no need to collect any history.

I'm not sure exactly how the API would look, but I'd love to have the option to use a normal `Cursor` in `Decoder` instead of an `HCursor`.

As a side note, `HCursor` stores its `history` as `List[HistoryOp]`, which makes the garbage problem even worse, as each `HistoryOp$El` instance also has a corresponding `$colon$colon` instance allocated for it. Would it be possible to use a less allocation-heavy collection type e.g. `Vector`?

**Comment by travisbrown** [comment]
@cb372 The proposal for 0.6.0 in #228 is a little more radical but should help here. I've done some initial experiments along those lines, and I'm hoping to get it implemented in August. Any feedback on the proposal would be much appreciated!

In the shorter term we could look at replacing that `List` with `Vector`…

**Comment by cb372** [comment]
Glad to hear you're already on the case! 

Your proposal sounds eminently sensible. I say go for it, and don't worry too much about maintaining backwards compatibility. I'm happy to accept a breaking change here.

**Comment by hamnis** [comment]
Closing in cleanup run, If anyone cares about this, please comment and I'll reopen.
