### ISSUE TITLE
Unwanted object encoding instances for tuples, lists, etc.

### ISSUE THREAD

**Issue by travisbrown** [circe/circe#36]
I've introduced an `ObjectEncoder[A]` type class that extends `Encoder[A]` but additionally guarantees that the generated JSON will be a JSON object. Argonaut doesn't provide this, but it's useful in many situations where you as the developer _know_ that the instance for a type has this property (meaning that `asObject` casts would just be noise and extra code to maintain).

`ObjectEncoder` is a way to share that knowledge with the compiler, while still having something that will work when people just want an `Encoder`.

The issue is that there are ADT / case class types like tuples and lists where the usual `Encoder` instances are not `ObjectEncoder`s. This means that if our generic derivation mechanism for ADTs and case classes provides `ObjectEncoder`s, we'll get those if we ask for them for e.g. tuples:

``` scala
scala> import io.circe._, io.circe.generic.auto._
import io.circe._
import io.circe.generic.auto._

scala> Encoder[(Int, String)].apply((1, "foo")).noSpaces
res3: String = [1,"foo"]

scala> ObjectEncoder[(Int, String)].apply((1, "foo")).noSpaces
res4: String = {"_2":"foo","_1":1}

scala> ObjectEncoder[List[Int]].apply(List(1, 2, 3)).noSpaces
res5: String = {"::":{"tl$1":[2,3],"head":1}}
```

I'm currently side-stepping this problem by having my generic derivation mechanism return plain old `Encoder` instances, but it'd be nice to have the more informative instances for case classes and ADTs.

**Comment by lukewyman** [comment]
@travisbrown I'd like to take this one if it's still available. Might be a bit of a stretch at my current skill level, but I think I understand the problem in a vague/abstract way.

**Comment by travisbrown** [comment]
@lukewyman The situation is likely to change soon in #164, largely because the new case object encoding style option means that the generically derived encoders no longer always return JSON objects:

```scala
scala> import io.circe.Encoder, io.circe.generic.auto._, io.circe.syntax._
import io.circe.Encoder
import io.circe.generic.auto._
import io.circe.syntax._

scala> sealed trait Base; case object Foo extends Base; case object Bar extends Base
defined trait Base
defined object Foo
defined object Bar

scala> (Foo: Base).asJsonConfigured[io.circe.generic.config.CaseObjectString]
res0: io.circe.Json = "Foo"
```

This has been one of the most requested configuration options, and the extra guarantees of the `ObjectEncoder` type class didn't seem useful enough not to provide it.

We'll keep `ObjectEncoder` around, but the fact that the default generic derivation mechanism isn't using it means that we won't have to worry about this issue as much.

**Comment by hamnis** [comment]
Closing in cleanup run, If anyone cares about this, please comment and I'll reopen.
