### ISSUE TITLE
Update benchmarks

### ISSUE THREAD

**Issue by cb372** [circe/circe#363]
Now that 0.5 is out, it would be good to put some up-to-date benchmarks on the site. Maybe even with pretty graphs!

I can run the benchmarks, although my poor old MacBook Air might melt 😄

**Comment by travisbrown** [comment]
👍 , I've just started them running on my desktop at home.

**Comment by travisbrown** [comment]
We don't have pretty graphs yet, but there are more recent results over at [circe-benchmarks](https://github.com/circe/circe-benchmarks).
