### ISSUE TITLE
Encoding/Parsing round trip equality failure for ScalaCheck-generated BigDecimals

### ISSUE THREAD

**Issue by amrhassan** [circe/circe#368]
I run into an issue sometimes when I check the equality of a ScalaCheck-generated `BigDecimal` encoded into a `Json` with the `Json` parsed back from the encoded JSON string of the same `BigDecimal`.

``` scala
import org.specs2._
import _root_.io.circe._
import _root_.io.circe.syntax._
import _root_.io.circe.parser._
import org.specs2.matcher.XorMatchers

class CirceSpec extends Specification with ScalaCheck with XorMatchers { def is = s2"""
  Serialized BigDecimal is equal to parsed number     $bigDecimalRoundTrip
  """

  def bigDecimalRoundTrip = prop { (n: BigDecimal) =>
    val encoded: Json = n.asJson
    parse(encoded.noSpaces) must beXorRight(encoded)
  }.set(minTestsOk=500)
}
```

The failure occurs with `BigDecimal` instances that are affected by [this issue](https://github.com/rickynils/scalacheck/issues/124) so I think it might be affecting the conversion to `numbers.BiggerDecimal` which is the type responsible for the equality check. 

This is produced using scalacheck-1.13.2 and circe-0.5.1.

**Comment by travisbrown** [comment]
I can't reproduce this:

```scala
scala> import io.circe.jawn.parse, io.circe.syntax._, org.scalacheck.Prop
import io.circe.jawn.parse
import io.circe.syntax._
import org.scalacheck.Prop

scala> val p = Prop.forAll { b: BigDecimal =>
     |   val encoded = b.asJson
     |   parse(encoded.noSpaces) == Right(encoded)
     | }
p: org.scalacheck.Prop = Prop

scala> p.check
+ OK, passed 100 tests.
```

…but am happy to reopen if it's still an issue.
