### ISSUE TITLE
Validate invalid fields

### ISSUE THREAD

**Issue by olafurpg** [circe/circe#374]
``` scala
@ import io.circe.generic.auto._
@ import io.circe.parser._
@ case class Foo(col: Option[Int])
@ val result = parse("""{ "typo": 2 }""").map(_.as[Foo])
result: cats.data.Xor[io.circe.ParsingFailure, io.circe.Decoder.Result[Foo]] = Right(Right(Foo(None)))
```

I'm curious to know, is there's a way for a decoder to validate that there's no invalid key like `typo` in this example? Phrased alternatively, is there a way to know after decoding whether there was an unused key/value in the json?

I'm hoping to use [circe-yaml](https://github.com/jeremyrsmith/circe-yaml) to read configuration for scalafmt. All the fields are optional (`Option[T]`) but I would like the decoder to fail if the user has entered a field that contains a typo.

I noticed there's a `validate` method on `Decoder[T]` but I don't see how it could help me in this scenario.

I'm using circe 0.5.2.

**Comment by travisbrown** [comment]
By default decoders don't consume fields as they use them, so this isn't trivial, but you can do something that works with `validate` and some boilerplate:

```scala
import io.circe._, io.circe.generic.semiauto.deriveDecoder

def validateKeys(allowed: Set[String])(c: HCursor): Boolean =
  c.focus.asObject.exists(_.fieldSet.subsetOf(allowed))

case class Foo(a: Int, b: String, c: Boolean)

implicit val decodeFoo: Decoder[Foo] =
  deriveDecoder[Foo].validate(validateKeys(Set("a", "b", "c")), "Foo: invalid fields")
```

And then:

```scala
scala> import io.circe.jawn.decode
import io.circe.jawn.decode

scala> decode[Foo]("""{ "a": 1, "b": "xyz", "c": false, "d": null }""")
res0: cats.data.Xor[io.circe.Error,Foo] = Left(DecodingFailure(Foo: invalid fields, List()))
```

The error message isn't great, though, and I agree that this is a use case that deserves better support. I'll think about what this should look like this week (and any ideas would be appreciated).

**Comment by olafurpg** [comment]
I was afraid this wouldn't be so trivial.

The `validate` workaround gets a lot tricker once you have 30 keys of which some are nested, contain arrays and so forth. Also, I think it's quite important that the error message points to the culprit field.

I'm have no idea if this is remotely possible, but one potential solution might be to encode into a `Decoder.Result[(Cursor, A)]` instead of `Decoder.Result[A]`. The cursor would be the accumulated result of deleting each json node that's consumed to produce the value `A`. After decoding you could run the cursor on the original input to see if the Json is empty.

**Comment by olafurpg** [comment]
Here's roughly what I had in mind:

```scala
    case class Foo(col: Option[Int])
    val d: Decoder[(ACursor, Foo)] = new Decoder[(ACursor, Foo)] {
      override def apply(c: HCursor): Result[(ACursor, Foo)] = {
        c.get[Option[Int]]("col").map { x =>
          (c.downField("col").delete.or(c.acursor), Foo(x))
        }
      }
    }

    for {
      json <- parse("""|
                       |{
                       |  "typo": 2
                       |}
                       |""".stripMargin)
      res <- json.as[(ACursor, Foo)](d)
    } yield {
      debug.elem(res._1.top)
    }
[debug] YamlSpec.scala:150        [res._1.top]: Some({
  "typo" : 2
})
[debug] YamlSpec.scala:149        [res._2]: Foo(None)
```

If it would be possible to automatically derive such a decoder then that would be amazing.

**Comment by travisbrown** [comment]
@olafurpg You could also do something like this:

```scala
import cats.data.{ StateT, Xor }
import io.circe.{ ACursor, Decoder, DecodingFailure }

def read[A: Decoder](k: String): StateT[Decoder.Result, ACursor, A] =
  StateT[Decoder.Result, ACursor, A] { c =>
    val field = c.downField(k)
    field.as[A].map((field.delete, _))
  }

def requireEmpty: StateT[Decoder.Result, ACursor, Unit] =
  StateT[Decoder.Result, ACursor, Unit] { c =>
    val fields = c.focus.flatMap(_.asObject).toList.flatMap(_.fields)
    if (fields.isEmpty) Xor.right((c, ())) else
      Xor.left(DecodingFailure(s"Leftovers: ${ fields.mkString(", ") }", c.history))
  }
```

And then:

```scala
scala> import cats.syntax.show._, io.circe.jawn.decode
import cats.syntax.show._
import io.circe.jawn.decode

scala> case class Foo(a: String, b: Int, c: Boolean)
defined class Foo

scala> implicit val decodeFoo: Decoder[Foo] = Decoder.instance { c => (
     |   for {
     |     a <- read[String]("a")
     |     b <- read[Int]("b")
     |     c <- read[Boolean]("c")
     |     _ <- requireEmpty
     |   } yield Foo(a, b, c)
     | ).runA(c.acursor) }
decodeFoo: io.circe.Decoder[Foo] = io.circe.Decoder$$anon$24@1c298cc

scala> decode[Foo](good)
res0: cats.data.Xor[io.circe.Error,Foo] = Right(Foo(xyz,1,true))

scala> decode[Foo](bad).leftMap(_.show).swap.foreach(println)
DecodingFailure at .a{!_/}.b{!_/}.c{!_/}: Leftovers: d, e
```

We could definitely make this easier with a `Decoder.fromState` and other helper methods, and we should be able to have instances like this derived.

**Comment by olafurpg** [comment]
@travisbrown Wow. That looks amazing. Took me a while to wrap my head around how the state monad works in this example.

I'll need to experiment a bit with this approach to see how it works with a large number of optional fields.  I may eventually choose to go with a manual decoder just for sake of flexibility.

> We could definitely make this easier with a Decoder.fromState and other helper methods, and we should be able to have instances like this derived.

I would definitely be interested see how that would look like. Any idea about a timeframe? I might be tempted to take a swing at it if given some pointers.

**Comment by travisbrown** [comment]
@olafurpg If you think about `Decoder` as `HCursor => Xor[DecodingFailure, A]`, then my `StateT` version is almost identical to yours with `(ACursor, Foo)`. :)

For generic derivation, one issue is that it's not immediately clear to me how to implement this approach with the usual inductively-build-up-instances-for-hlists technique. It'd be easy enough to change the current macro implementation, but my goal has been for that only to be a compile-time performance optimization, so that if the compiler gets better at recognizing inductive searches and caching instances, we can remove the macros.

Another question is whether this should be a configuration choice or an entirely different derivation mechanism.

I guess for now I'd be happy to add `Decoder.fromState`, etc., and then have an alternate macro-based deriver, but we can talk about it.

**Comment by olafurpg** [comment]
@travisbrown I think I'll begin with the manual approach and keep my eyes open for parts we could abstract over. Will keep you posted. Thanks a lot for your help!

**Comment by olafurpg** [comment]
In the end, I rolled my own inline/meta macro annotation to read a HOCON `Map[String, Any]` ([see discussion](https://github.com/olafurpg/scalafmt/issues/316)). This choice was undeniably biased by my eagerness to explore the new scala.meta based macro system.

It would be interesting to experiment with automatic derivation of circe decoders using scala.meta macros. Although, I understand there is a preference to separate serialization from the class definitions.

The nice thing about scala.meta macros is that they give a lot less ammunition to shoot yourself in the foot compared to scala.reflect macros.

Feel free to close this issue if you like.

**Comment by pfcoperez** [comment]
I was able to enable strict de-serialization with semi-auto derivation by providing an alternative to `deriveDecoder`:

https://github.com/pfcoperez/trycirce/blob/d64bc94db5fdf76750394153ffa8b5fadefaf70d/src/main/scala/org/pfcoperez/custom/circe/semiauto.scala#L13-L40

@travisbrown Would it be worth of developing this draft and contribute it to `io.circe.generic.extras`?

**Comment by LBsh** [comment]
Hi, 

recently while using the `withStrictDecoding` option I ran into a very interesting bug:

```scala
case class Foo(a: List[Int] = Nil)
case class Boo(b: Map[String, Foo])

implicit val customConfig: Configuration = Configuration.default.withDefaults.withStrictDecoding


val s = """
{"b": {"b1": {"a": [1,2,3]}, "b2": [{"random": "string"}]}}
"""

parse(s).valueOr(throw _).as[Boo]

res10: io.circe.Decoder.Result[Boo] = Right(Boo(Map(b1 -> Foo(List(1, 2, 3)), b2 -> Foo(List()))))
```

As one can see it doesn't seem to work well with defaults, as "b2" should be flagged as a wrong field here, but instead it reads "b2" as an instance of Foo with an empty list of int.

**Comment by travisbrown** [comment]
@LBsh That does look like a bug, but I think the underlying issue is a problem in `withDefaults`, not `withStrictDecoding` (e.g. you can drop the `.withStrictDecoding` and try `decode[Foo]("1")`).

Would you mind opening an issue in the [circe-generic-extras](https://github.com/circe/circe-generic-extras) repo, which is maintained and versioned separately now?

**Comment by hamnis** [comment]
Closing in cleanup run, If anyone cares about this, please comment and I'll reopen.
