### ISSUE TITLE
Document the misleading compilation errors with generic derivation

### ISSUE THREAD

**Issue by backuitist** [circe/circe#378]
Here is a simple example:

``` scala
import java.time.ZonedDateTime

case class Person(name: String, age: Int, date: ZonedDateTime)

import io.circe.syntax._
import io.circe.generic.auto._

Person("john", 12, ZonedDateTime.now()).asJson
```

Will produce `Error: could not find implicit value for parameter encoder: io.circe.Encoder[Person]`
Instead of the expected `could not find [...] io.circe.Encoder[ZonedDateTime]`

IMO the warning section of the documentation should start with this, as it is I guess the most common pitfall of the derivation mechanism.

**Comment by nafg** [comment]
It might be worth recommending https://github.com/tek/splain

Although the output could use explanation... something like this can be scary if you don't know what you're looking at:

```

**Comment by dacr** [comment]
Got the same issue :( any workaround ?

```scala
import io.circe.generic.extras.auto._
import io.circe._, io.circe.parser._, io.circe.syntax._, io.circe.java8._,  io.circe.java8.time._
import java.time._

ZonedDateTime.now.asJson
// res0: io.circe.Json = "2018-01-17T23:06:26.431+01:00[Europe/Paris]"

case class TestThis(ts:ZonedDateTime)

TestThis(ZonedDateTime.now).asJson
//<console>:56: error: could not find implicit value for parameter encoder: io.circe.Encoder[TestThis]
     
```

**Comment by dacr** [comment]
**No longer an issue !**
I've added this option as this is a cats requirement : `scalacOptions += "-Ypartial-unification" ` but this is not the solution.

After some investigation I've found that the issue is linked to the missing implicit circe configuration (try the following in the console using `:paste`) : 

DON'T WORK  : 
```
import io.circe.generic.extras.Configuration
import io.circe.generic.extras.auto._
import io.circe._, io.circe.parser._, io.circe.syntax._, io.circe.java8._,  io.circe.java8.time._
import java.time._

case class TestThis(ts:ZonedDateTime)
TestThis(ZonedDateTime.now).asJson
```

WORKS FINE : 
```
import io.circe.generic.extras.Configuration
import io.circe.generic.extras.auto._
import io.circe._, io.circe.parser._, io.circe.syntax._, io.circe.java8._,  io.circe.java8.time._
import java.time._

implicit val circeConfig:Configuration = Configuration.default

case class TestThis(ts:ZonedDateTime)
TestThis(ZonedDateTime.now).asJson
```

SO don't forget to add in the current scope an implicit circe configuration.

**Comment by nafg** [comment]
That's one of many possible causes, with generic-extras...
