### ISSUE TITLE
Another divergence checking nightmare

### ISSUE THREAD

**Issue by travisbrown** [circe/circe#390]
This issue is a minimization of #386—thanks much to @dzikowski for the original report.

The problem shows up in situations like this:

``` scala
import io.circe.Encoder
import io.circe.syntax._
import io.circe.generic.auto._

object Foo {
  case class Bar(i: Int)
  object Bar {
    implicit val encodeBar: Encoder[Bar] = Encoder[Int].contramap(_.i)
  }
}

case class Bars(values: Seq[Foo.Bar])
```

And then:

``` scala
scala> List(Bars(List(Foo.Bar(1)))).asJson.noSpaces
res0: String = {"::":[{"values":[1]}]}
```

This doesn't happen if `Bars` is defined in the same object as `Bar`, or if `Bar` is moved out of `Foo`, or if `Bars` is defined separately (e.g. two `:paste`s in the REPL). It also doesn't happen if `Bars` is explicitly given a derived instance with `deriveEncoder`.

The problem is that the divergence checker is bailing when trying to find the `Bars` encoder in `encodeTraversableOnce[Bars, List]`, because the derivation mechanism needs to use `encodeTraversableOnce` again for `Bars#values`. I have no idea why this only happens in the nested case, but the divergence checker's notions of "bigger" and "smaller" have always been a mystery to me.

If we had a Shapeless dependency in circe-core this would be trivial—we'd just put a `Lazy` in `encodeTraversableOnce` and we're done. That's not really an option, though.

The only workaround I can think of is to copy-paste all generic instances where this could happen from both `Encoder` and `Decoder` into `auto` (user-defined generic contexts _should_ be fine, I think—at least they are in the simple cases I've tried). This works, but it's really, really unsatisfying, and any other suggestions would be greatly appreciated.

**Comment by milessabin** [comment]
FYI, you could have a "soft" dependency on `shapeless.Lazy` using the technique employed in [export-hook](https://github.com/milessabin/export-hook/blob/master/core/src/main/scala/export/export.scala#L499-L507).

**Comment by travisbrown** [comment]
@milessabin But I've held out against macros in circe-core for soooo long. 😦

**Comment by milessabin** [comment]
Ahh ... sorry, I thought this was an issue relating to the new macros in recent circe releases.

**Comment by travisbrown** [comment]
This problem seems to have resolved itself in recent circe releases, although I'm not 100% sure why at the moment. We'll need to take some time to confirm that the issue is resolved with new tests, but then I'll close this (and hopefully also #444 and #386).

**Comment by travisbrown** [comment]
Confirmed that this is resolved in all current Scala version on master.
