### ISSUE TITLE
circe-generic macros do not work with `"-Ywarn-unused-import"` scalac flag

### ISSUE THREAD

**Issue by ngbinh** [circe/circe#401]
For any scala project with `"-Ywarn-unused-import"` turns on, this code will not compile:

``` scala
@JsonCodec
case class A(a: Int)
```

with error `could not find Lazy implicit value of type io.circe.generic.encoding.DerivedObjectEncoder[A]`

**Comment by travisbrown** [comment]
What versions (Scala, circe) are you on? I just set up a minimal project and I'm not seeing an error.

**Comment by ngbinh** [comment]
I am on Scala `2.11.8` and latest circe `0.5.3`. Will try to come up with a minimal reproduce

**Comment by travisbrown** [comment]
Closing but am happy to reopen if it's still an issue.
