### ISSUE TITLE
Generic derivation fails for sealed hierarchy living in a file with a lower-case name

### ISSUE THREAD

**Issue by backuitist** [circe/circe#434]
This is happening with circe 0.5.4 and scala 2.11.8.
I've created a simple repo to reproduce this: https://github.com/backuitist/circe-test

**Comment by travisbrown** [comment]
Okay, that's really weird. Here's a minimization that's not circe-specific:
```scala
// build.sbt
scalaVersion := "2.12.0"
libraryDependencies += "com.chuusai" %% "shapeless" % "2.3.2"

// project/build.properties
sbt.version = 0.13.13

// foo.scala
sealed trait Foo
case object Bar extends Foo

// Test.scala
object Test { shapeless.Generic[Foo] }
```

This won't compile, but if you rename `foo.scala` to `Foo.scala` and `sbt clean compile` it works just fine.

To make things even more horrifying, you can also leave `foo.scala` as it is and rename `Test.scala` to `test.scala` and it'll work.

Same thing happens on 2.10.6 and 2.11.8.

Unfortunately I don't really know what to say besides "don't do that", @backuitist.

**Comment by dwijnand** [comment]
Looks like a bug in the incremental compiler..

```
$ scalac -cp ~/.ivy2/cache/com.chuusai/shapeless_2.12/bundles/shapeless_2.12-2.3.2.jar foo.scala Test.scala

$ scalac -version
Scala compiler version 2.12.0 -- Copyright 2002-2016, LAMP/EPFL and Lightbend, Inc.
```

**Comment by djspiewak** [comment]
Mac or Linux?

**Comment by travisbrown** [comment]
@djspiewak Not sure about @backuitist, but I'm on a Mac at the moment. Trying on Linux now…

**Comment by backuitist** [comment]
I'm on a Mac

**Comment by dwijnand** [comment]
I'm on Mac, with a case-insensitive FS:

```
16:16:05 $ touch foo.scala

16:16:08 $ touch Foo.scala

16:16:09 $ l
.
└── [   0]  foo.scala

0 directories, 1 file
```

**Comment by travisbrown** [comment]
Same thing on Linux.

**Comment by milessabin** [comment]
It's SI-7046. scalac sorts source files by (path) name. So filename can affect type checking order.

**Comment by backuitist** [comment]
Do you think https://github.com/scala/scala/pull/5284 will fix that?

**Comment by dwijnand** [comment]
Ah...

```
$ scalac -cp ~/.ivy2/cache/com.chuusai/shapeless_2.12/bundles/shapeless_2.12-2.3.2.jar \
  Test.scala foo.scala
Test.scala:1: error: could not find implicit value for parameter gen: shapeless.Generic[Foo]
object Test { shapeless.Generic[Foo] }
                               ^
one error found
```

**Comment by travisbrown** [comment]
@backuitist I just confirmed that this works with TLS, so yes, it should.

**Comment by travisbrown** [comment]
This is out-of-scope for circe, but we've now got docs about workarounds via #644.
