### ISSUE TITLE
Switch to sbt-microsites

### ISSUE THREAD

**Issue by travisbrown** [circe/circe#438]
I think we should use @47deg's [sbt-microsites](https://github.com/47deg/sbt-microsites) to build the project site. The transition is likely to look pretty similar to [the one for Cats](https://github.com/typelevel/cats/pull/1369), since the current circe site is largely based on the previous Cats one.

**Comment by darienmt** [comment]
I could help with that. I am not familiar with the plugin, but I am familiar with jekyll.

**Comment by jonas** [comment]
@travisbrown This can be closed I believe

**Comment by travisbrown** [comment]
@jonas Yep, thanks. Fixed in #438.
