### ISSUE TITLE
Issue with deriveEnumerationDecoder

### ISSUE THREAD

**Issue by cb372** [circe/circe#445]
I tried to use the new `deriveEnumerationDecoder` on an enum that was auto-generated by ScalaPB from a protobuf schema, but it fails to compile:

```
[error] /Users/chris.birchall/code/circe-scalapb-enum-issue/src/test/scala/CirceSpec.scala:11: could not find Lazy implicit value of type io.circe.generic.extras.decoding.EnumerationDecoder[protobuf.event.EventType]
[error]     implicit val decoder: Decoder[EventType] = deriveEnumerationDecoder[EventType]
[error]                                                                        ^
[error] one error found
```

Minimal reproduction here: https://github.com/cb372/circe-scalapb-enum-issue

The generated code looks pretty similar to the example given in the 0.6.0-RC1 release notes, so I'm not sure why this doesn't work. I thought it might be SI-7046 related, but I've tried with TLS to no avail.

Here's the generated code for the enum:

```scala
sealed trait EventType extends com.trueaccord.scalapb.GeneratedEnum {
  type EnumType = EventType
  def isQueued: Boolean = false
  def isDelivered: Boolean = false
  def isOpened: Boolean = false
  def isUnrecognized: Boolean = false
  def companion: com.trueaccord.scalapb.GeneratedEnumCompanion[EventType] = EventType
}

object EventType extends com.trueaccord.scalapb.GeneratedEnumCompanion[EventType] {
  implicit def enumCompanion: com.trueaccord.scalapb.GeneratedEnumCompanion[EventType] = this
  @SerialVersionUID(0L)
  case object QUEUED extends EventType {
    val value = 0
    val index = 0
    val name = "QUEUED"
    override def isQueued: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object DELIVERED extends EventType {
    val value = 1
    val index = 1
    val name = "DELIVERED"
    override def isDelivered: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object OPENED extends EventType {
    val value = 2
    val index = 2
    val name = "OPENED"
    override def isOpened: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case class Unrecognized(value: Int) extends EventType {
    val name = "UNRECOGNIZED"
    val index = -1
    override def isUnrecognized: Boolean = true
  }
  
  lazy val values = scala.collection.Seq(QUEUED, DELIVERED, OPENED)
  def fromValue(value: Int): EventType = value match {
    case 0 => QUEUED
    case 1 => DELIVERED
    case 2 => OPENED
    case __other => Unrecognized(__other)
  }
  def descriptor: com.google.protobuf.Descriptors.EnumDescriptor = EventProto.descriptor.getEnumTypes.get(0)
}
```

**Comment by travisbrown** [comment]
The issue here is the `Unrecognized` case class, since this mechanism requires all constructors to be case objects. This restriction is mentioned briefly in the release notes ("If we had any case classes in our `Suit` ADT, the derivation would fail to compile"), but should be documented better.

The restriction isn't set in stone—I just wanted to provide a version of the functionality that didn't require a lot of fiddly decisions to be made. If we support case classes, do they get represented as `{ "Unrecognized": { "value": 0 } }` or just `{ "value": 0 }`? Do they get derived instances or do you have to provide those separately?

**Comment by cb372** [comment]
I see. Sorry, I did read that sentence in the release notes, but totally forgot about it.

For now I'm happy to write my decoders manually, as I only have 3 or 4 enum types. In the long term it might be nice to support case classes as well as case objects, but I understand the desire to avoid overcomplicating things.

**Comment by travisbrown** [comment]
Closing for now as out of scope.
