### ISSUE TITLE
Build all circe jars as OSGi bundles

### ISSUE THREAD

**Issue by jrudnick** [circe/circe#452]
It would be nice to be able to leverage circe jars in the context of OSGi bundles, for use within OSGi-ready applications.

I haven't looked much into this, but perhaps this is of use? https://github.com/sbt/sbt-osgi

**Comment by travisbrown** [comment]
To be honest it's been years since I've personally used OSGi, but I'd be happy to see this get done. The [scodec family of projects](https://github.com/scodec) is probably a good place to look for models.

**Comment by hamnis** [comment]
Closing in cleanup run, If anyone cares about this, please comment and I'll reopen.
