### ISSUE TITLE
JSON encoding of case classes with the same name in different packages

### ISSUE THREAD

**Issue by sbrunk** [circe/circe#454]
I'm working with a large collection of case classes that extend a sealed trait. In order to avoid naming collisions these case classes are grouped into different objects (they could also be grouped in packages).

For instance I have an object of type Tabs.OnCreated and another of type Windows.OnCreated. The JSON representation only contains the simple class name though, so it's impossible to distinguish the two types. The decoder just creates an instance of the first type.

I know this is probably a very special case. Still I'm wondering if there's a way to support that kind of structure in Circe. I guess we'd need something like the full class name as discriminator in the JSON representation.

Minimal example below:

```scala
import io.circe.parser.decode
import io.circe.syntax._
import io.circe.generic.auto._

sealed trait Event
object Tabs { // could also be package tabs, same result
  case class OnCreated(id: String) extends Event
}
object Windows {
  case class OnCreated(id: String) extends Event
}

object CirceEval extends App {
  val tabOnCreated: Event = Tabs.OnCreated("tab created")
  val tabOnCreatedJson = tabOnCreated.asJson.toString()
  val decodedTabEvent = decode[Event](tabOnCreatedJson)
  println(tabOnCreatedJson)
  println(decodedTabEvent)
  println(decodedTabEvent.map(_.getClass))

  val windowOnCreated: Event = Windows.OnCreated("window created")
  val windowOnCreatedJson = windowOnCreated.asJson.toString()
  val decodedWindowEvent = decode[Event](windowOnCreatedJson)
  println(windowOnCreatedJson)
  println(decodedWindowEvent)
  println(decodedWindowEvent.map(_.getClass))
}
```
Output:
```
{
  "OnCreated" : {
    "id" : "tab created"
  }
}
Right(OnCreated(tab created))
Right(class CirceEval$Tabs$OnCreated)

{
  "OnCreated" : {
    "id" : "window created"
  }
}
Right(OnCreated(window created))
Right(class CirceEval$Tabs$OnCreated)
```

**Comment by markschaake** [comment]
I've just been bit by this same issue. In my case I'm getting a runtime exception because my similarly-named case classes have a different field name.

```scala
Welcome to Scala 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_112).
Type in expressions for evaluation. Or try :help.

scala> import io.circe._, io.circe.syntax._, io.circe.generic.semiauto._
import io.circe._
import io.circe.syntax._
import io.circe.generic.semiauto._

scala> sealed trait FooBar
defined trait FooBar

scala> object Foo {
  case class ItHappened(by: String, fooId: String) extends FooBar
}
     | defined object Foo

scala> object Bar {
  case class ItHappened(by: String, barId: String) extends FooBar
}
     | defined object Bar

scala> object JsonProtocol {
  implicit val fooBarDecoder: Decoder[FooBar] = deriveDecoder
  implicit val fooBarEncoder: Encoder[FooBar] = deriveEncoder
}
     | defined object JsonProtocol

scala> import JsonProtocol._

scala> val foo: FooBar = Foo.ItHappened("foo", "foo")
foo: FooBar = ItHappened(foo,foo)

scala> val bar: FooBar = Bar.ItHappened("foo", "foo")
bar: FooBar = ItHappened(foo,foo)

scala> val fooJs = foo.asJson
fooJs: io.circe.Json =
{
  "ItHappened" : {
    "by" : "foo",
    "fooId" : "foo"
  }
}

scala> val barJs = bar.asJson
barJs: io.circe.Json =
{
  "ItHappened" : {
    "by" : "foo",
    "barId" : "foo"
  }
}

scala> fooJs.as[FooBar]
res2: io.circe.Decoder.Result[FooBar] = Right(ItHappened(foo,foo))

scala> barJs.as[FooBar]
res3: io.circe.Decoder.Result[FooBar] = Left(DecodingFailure(Attempt to decode value on failed cursor, List(DownField(fooId), DownField(ItHappened))))

scala>
```

I took a glance at the generic [Deriver](https://github.com/circe/circe/blob/f04aab29ca1a0af5481de668db7d3067565af1b1/modules/generic/shared/src/main/scala/io/circe/generic/Deriver.scala) and could not grok (sorry). I was thinking a solution could be to add macros for deriving encoder/decoder with a user-specified identifier instead of defaulting to the simple class name. Something like:

 ```scala
object JsonProtocol {
  implicit val (fooItHappenedEncoder, fooItHappenedDecoder): Decoder[Foo.ItHappened] = deriveGenericCodec[FooBar](id = "Foo.ItHappened")
  implicit val (barItHappenedEncoder, barItHappenedDecoder): Decoder[Bar.ItHappened] = deriveGenericCodec[FooBar](id = "Bar.ItHappened")
  implicit val fooBarEncoder: Encoder[FooBar] = deriveEncoder
}
```

Then presumably the JSON would look like this for `Foo.ItHappened` and `Bar.ItHappened`, respectively :

```json
{
  "Foo.ItHappened" : {
    "by" : "foo",
    "fooId" : "foo"
  }
}
```

```json
{
  "Bar.ItHappened" : {
    "by" : "foo",
    "barId" : "foo"
  }
}
```

**Comment by travisbrown** [comment]
Thanks for the report, @sbrunk and @markschaake, and sorry for letting this sit so long (sometimes notifications slip by me, so feel free to bump). I'll take a look today.

**Comment by travisbrown** [comment]
I'd be inclined not to provide special support for this case, since Shapeless's generic representation doesn't include the necessary information, and since there are potentially lots of ways the discriminator key could be chosen. Writing explicit instances for the top level isn't too bad:

```scala

import cats.syntax.functor._
import io.circe.{ Decoder, Encoder, Json }
import io.circe.generic.auto._
import io.circe.parser.decode
import io.circe.syntax._

sealed trait Event

object Tabs {
  case class OnCreated(id: String) extends Event
}

object Windows {
  case class OnCreated(id: String) extends Event
}

object Event {
  implicit val encodeEvent: Encoder[Event] = Encoder.instance {
    case e @ Tabs.OnCreated(_)    => Json.obj("Tabs.OnCreated"    -> e.asJson)
    case e @ Windows.OnCreated(_) => Json.obj("Windows.OnCreated" -> e.asJson)
  }

  private val decodeT = Decoder[Tabs.OnCreated].prepare(_.downField("Tabs.OnCreated"))
  private val decodeW = Decoder[Windows.OnCreated].prepare(_.downField("Windows.OnCreated"))

  implicit val decodeEvent: Decoder[Event] = decodeT.or(decodeW.widen[Event])
}
```

What do you think?

**Comment by markschaake** [comment]
@travisbrown the workaround I ended up using essentially does the same thing. Not a big issue for me since the workaround is pretty straightforward. I'd say don't bother if adding support would take a considerable effort. BTW, thanks for such an awesome library!

**Comment by sbrunk** [comment]
I went with mangling name of the enclosing object i.e. ```TabsOnCreated```, ```WindowsOnCreated``` etc. which is a bit ugly but allows me to keep using fully automatic derivation. Thanks for looking into it.

**Comment by travisbrown** [comment]
I'm going to go ahead and close this since I don't want to stray too far from Shapeless's generic representation for the basic case, and since master now supports transforming the constructor name via implicit configuration after #648 / #684.
