### ISSUE TITLE
specialized Encoder\Decoder macro

### ISSUE THREAD

**Issue by Odomontois** [circe/circe#468]
In my project for types in some module I'm implementing only `Encoder`s
There're 20% encoders written manually and other 80%  are via `deriveEncoder`.
For each of those 80% I'm making a small companion object containing a single `implicit ObjectEncoder[...]` definition.
It would be nice if there were specialized `@JsonEncoder` and `@JsonDecoder` macro annotations making such code a little bit more readable

**Comment by travisbrown** [comment]
This is available in master via #631 and #681.
