### ISSUE TITLE
Reconsider the collection type in the JSON array representation

### ISSUE THREAD

**Issue by travisbrown** [circe/circe#475]
Right now circe represents JSON arrays as a case class wrapping a `Seq[Json]`, with `List[Json]` used by default for Jawn-parsed arrays, as well as throughout the API.

`List` fits nicely with the current cursor implementation, where a cursor into a JSON array is represented zipper-style with a list of values to the left (moving away from the cursor) and a list to the right. This representation is great for operations that involve a lot of modifications, but it's inefficient when all you're doing is navigating (which is almost always the case when using cursors for decoding).

I'm experimenting with introducing a new array cursor implementation that just maintains an index into a `Vector`. This has the usual disadvantages (compared to an appropriate use of lists) when you're making changes, but it's much, much lighter and faster for decoding applications (literally twice the throughput of 0.6.0 in our decoding benchmarks).

The problem is that we need to change the representation of JSON arrays for this to make sense—otherwise we have to do a lot of converting back and forth between `List` and `Vector`. So I'm proposing that we switch to using `Vector` for working with JSON arrays everywhere (in the `JArray` case class, in `Json#fold`, `ArrayEncoder`, etc.).

What do people think?

**Comment by vkostyukov** [comment]
My vote shouldn't probably be counted (as I'm not using Circe at work), but I've done some similar changes in one of the Finagle's internal components in the past (`List` -> `Vector`). Vectors are great for all sort of things: random access, iterating over with `.iterator`. Coupled with `VectorBuilder`s (a mutable builder that can yield a `Vector` in `O(1)`) they promote quite time/space-efficient solutions.

**Comment by emilypi** [comment]
@travisbrown I've actually recently come across this issue, and I agree with the suggestion - `List` fits well in here as a default. Encouraging the use of `Array`, however "correct" it may be in the context of JSON parsing, should be frowned upon. The fix, however, is minimal, and I would be incredibly stoked to see `circe` take this on board.

**Comment by hamnis** [comment]
Closing in cleanup run, If anyone cares about this, please comment and I'll reopen.
