### ISSUE TITLE
Add an fs2 module

### ISSUE THREAD

**Issue by travisbrown** [circe/circe#484]
This would probably look similar to circe-streaming but would use [fs2](https://github.com/functional-streams-for-scala/fs2) instead of [iteratee.io](http://iteratee.io).

**Comment by fsvehla** [comment]
Is there also interest in a version for Monix observables?

**Comment by fommil** [comment]
looks like I may have need of a `Pipe[F, Byte, T]` and (maybe) a `Pipe[F, T, Byte]` which would be constructed if there is an implicit (circe equivalent of) `JsonReader[T]` around. Or would it be better to provide `Pipe[F, Byte, JsonValue]` and then a separate `Pipe[F, JsonValue, T]`?

**Comment by fommil** [comment]
ah, looks like @fsvehla already did the latter! `Pipe[F, Chunk[Byte], Json]` (although I think fs2 may need to chunk up the bytes in that case)

**Comment by travisbrown** [comment]
This is now available [in a separate repo](https://github.com/circe/circe-fs2) in the circe org.
