### ISSUE TITLE
Compatibility with JSON dialects

### ISSUE THREAD

**Issue by tindzk** [circe/circe#487]
It should be possible to specify a dialect/compatibility level. For example, JVM's Long numbers could be represented as strings to support larger numbers. Conversely, if the developer only uses Circe to process JavaScript-generated JSON, decoding should fail if a long is expected, but string found.

See also #393.

**Comment by travisbrown** [comment]
Thanks, @tindzk. What I'm imagining is something like a `strictNumeric` object (probably inside of `Decoder`) that would contain instances for numeric types that fail on JSON string values (without trying to parse them, which is the default behavior). Does that sound reasonable?

I'm not sure I'll get around to this myself before 0.7, but I'd be happy to review any contributions.

**Comment by tindzk** [comment]
Sounds good. It would allow adding support for further options, such as encoding objects as lists instead of dictionaries. We may also consider a setting to encode `Option` values as lists (like uPickle) for further space reductions.

**Comment by hamnis** [comment]
Closing in cleanup run, If anyone cares about this, please comment and I'll reopen.
