### ISSUE TITLE
Fix or document `sbt test`

### ISSUE THREAD

**Issue by mxl** [circe/circe#503]
Following the [discussion](https://gitter.im/circe/circe?at=584e6d0ebe9d43bc634cad21) in Gitter.

Currently it fails with:
```
sbt.ResolveException: unresolved dependency: com.typesafe.play#play-json_2.12;2.3.10: not found
unresolved dependency: io.argonaut#argonaut_2.12;6.1: not found
unresolved dependency: io.github.netvl.picopickle#picopickle-core_2.12;0.2.1: not found
unresolved dependency: io.github.netvl.picopickle#picopickle-backend-jawn_2.12;0.2.1: not found
...
sbt.ResolveException: unresolved dependency: com.typesafe.akka#akka-actor_2.12;2.3.9: not found
unresolved dependency: io.spray#spray-httpx_2.12;1.3.3: not found
unresolved dependency: io.spray#spray-routing-shapeless2_2.12;1.3.3: not found
unresolved dependency: io.spray#spray-testkit_2.12;1.3.3: not found
```

**Comment by jensraaby** [comment]
I've got the same issue at the moment with IntelliJ.

IntelliJ and sbt (only for the benchmark module) appear to be looking for 2.12 artefacts that don't exist.

I actually get different errors to the above:

```
[info] Resolving jline#jline;2.14.1 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.typesafe.play#play-json_2.12;2.3.10: not found
[warn] 	:: io.argonaut#argonaut_2.12;6.1: not found
[warn] 	:: io.github.netvl.picopickle#picopickle-core_2.12;0.2.1: not found
[warn] 	:: io.github.netvl.picopickle#picopickle-backend-jawn_2.12;0.2.1: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.typesafe.play:play-json_2.12:2.3.10 (/Users/raabyj01/Projects/circe/circe/build.sbt#L425)
[warn] 		  +- io.circe:circe-benchmark_2.12:0.7.0-SNAPSHOT ()
[warn] 		io.argonaut:argonaut_2.12:6.1 (/Users/raabyj01/Projects/circe/circe/build.sbt#L425)
[warn] 		  +- io.circe:circe-benchmark_2.12:0.7.0-SNAPSHOT ()
[warn] 		io.github.netvl.picopickle:picopickle-core_2.12:0.2.1 (/Users/raabyj01/Projects/circe/circe/build.sbt#L425)
[warn] 		  +- io.circe:circe-benchmark_2.12:0.7.0-SNAPSHOT ()
[warn] 		io.github.netvl.picopickle:picopickle-backend-jawn_2.12:0.2.1 (/Users/raabyj01/Projects/circe/circe/build.sbt#L425)
[warn] 		  +- io.circe:circe-benchmark_2.12:0.7.0-SNAPSHOT ()
[trace] Stack trace suppressed: run 'last benchmark/*:update' for the full output.
[error] (benchmark/*:update) sbt.ResolveException: unresolved dependency: com.typesafe.play#play-json_2.12;2.3.10: not found
[error] unresolved dependency: io.argonaut#argonaut_2.12;6.1: not found
[error] unresolved dependency: io.github.netvl.picopickle#picopickle-core_2.12;0.2.1: not found
[error] unresolved dependency: io.github.netvl.picopickle#picopickle-backend-jawn_2.12;0.2.1: not found
```

**Comment by jensraaby** [comment]
I've tried swapping some of the libraries in question to 2.12-compatible versions, and hardcoding the picopickle version to 2.11, but that then causes other issues

```diff
-      "com.typesafe.play" %% "play-json" % "2.3.10",
-      "io.argonaut" %% "argonaut" % "6.1",
+      "com.typesafe.play" %% "play-json" % "2.6.0-M1",
+      "io.argonaut" %% "argonaut" % "6.2-RC2",
       "io.spray" %% "spray-json" % "1.3.2",
-      "io.github.netvl.picopickle" %% "picopickle-core" % "0.2.1",
-      "io.github.netvl.picopickle" %% "picopickle-backend-jawn" % "0.2.1",
+      "io.github.netvl.picopickle" % "picopickle-core_2.11" % "0.3.1",
+      "io.github.netvl.picopickle" % "picopickle-backend-jawn_2.11" % "0.3.1",
       "org.scalatest" %% "scalatest" % scalaTestVersion % "test",
```

```
[info] Set current project to circe (in build file:/Users/raabyj01/Projects/circe/circe/)
[error] Modules were resolved with conflicting cross-version suffixes in {file:/Users/raabyj01/Projects/circe/circe/}benchmark:
[error]    com.chuusai:shapeless _2.12, _2.11
[error]    org.spire-math:jawn-parser _2.12, _2.11
[error]    org.typelevel:macro-compat _2.12, _2.11
[trace] Stack trace suppressed: run 'last benchmark/*:update' for the full output.
[error] (benchmark/*:update) Conflicting cross-version suffixes in: com.chuusai:shapeless, org.spire-math:jawn-parser, org.typelevel:macro-compat
```

**Comment by travisbrown** [comment]
@jensraaby Is that on the most recent master? As of yesterday the benchmark project is no longer aggregated.

I'd be fine with removing picopickle from the benchmarks if it's not having a 2.12 build is going to cause problems like this. I'd also happily accept a PR updating the Play JSON and Argonaut versions. :)

**Comment by jensraaby** [comment]
Yes I was using the latest master, on IntelliJ 2016.3.1. Annoyingly when you import an SBT project it tries to load all the dependencies before it will actually open anything. 

I managed to run locally when removing picopickle and updating the versions, but I'm not sure if there would be another way to just mark the benchmarks as only applicable with Scala 2.11/2.10?

**Comment by travisbrown** [comment]
Okay, `sbt test` and `sbt update` should just work after #521, #528, etc.

**Comment by worldwar2008** [comment]
libraryDependencies ++= Seq(
  "io.circe" % "circe-core_2.10" % "0.7.0",
  "io.circe" % "circe-generic_2.10" % "0.7.0",
  "io.circe" % "circe-parser_2.10" % "0.7.0"
)
How to sole this problem?


Error:Error while importing SBT project:
...
	at sbt.Classpaths$$anonfun$60.apply(Defaults.scala:1090)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[error] Conflicting cross-version suffixes in: com.chuusai:shapeless
[error] Use 'last' for the full log.

**Comment by travisbrown** [comment]
@worldwar2008 Do you have an explicit dependency on Shapeless (specifically on an earlier version than circe's 2.3.2)?
