### ISSUE TITLE
JsonCodec with apply() in companion object

### ISSUE THREAD

**Issue by tymm** [circe/circe#505]
```
@JsonCodec
case class Test(foo: String)

object Test {
  def apply(foo: String): Test =
    new Test(foo)
}
```
results in `could not find Lazy implicit value of type io.circe.generic.decoding.DerivedDecoder[Test]`

I'm not sure if this is a bug or intended.
In either case I think it is useful to write about this since I couldn't find anything regarding this behavior.

My current solution for fixing this is to move `apply` to another companion object:
```
object TestFactory {
  def apply(foo: String): Test =
    new Test(foo)
}
```

**Comment by kevinmeredith** [comment]
Could you please give the full code, i.e. which `import`'s you're including, @tymm, to reproduce your issue?

**Comment by hamnis** [comment]
Closing in cleanup run, If anyone cares about this, please comment and I'll reopen.
