### ISSUE TITLE
Add Iso between JsonObject and Map[String, Json]

### ISSUE THREAD

**Issue by julien-truffaut** [circe/circe#512]

**Comment by travisbrown** [comment]
Hmm, this wouldn't really be an isomorphism, though, since part of the contract of `JsonObject` is that it preserves order.

**Comment by julien-truffaut** [comment]
ah ok, I didn't know it was preserving order. Maybe we can define a `Iso[JsonObject, ListMap[String, Json]]` ?

**Comment by hamnis** [comment]
Closing in cleanup run, If anyone cares about this, please comment and I'll reopen.
