### ISSUE TITLE
Move benchmarks against other libraries to a separate project

### ISSUE THREAD

**Issue by travisbrown** [circe/circe#525]
See #521 for context:

> Hmm, I'm starting to think that the benchmarks against other libraries should live in their own project. This would be nice in a lot of ways: it's easier for people to contribute new benchmarks representing libraries or use cases they care about, it lets us keep our most dependency-heavy module out of the core repo, it puts a nicer boundary between the internal (e.g. generically derived vs. explicit instances) and external benchmarks, etc.

So the idea is that all benchmarks against other JSON libraries would live in a new circe/circe-benchmarks repository, and only the internal benchmarks would stay in this repo.

**Comment by jensraaby** [comment]
I don't know how timely I would be, but I'm willing to start working on this. 

Initially I suppose there needs to be a new repo, then a lift-and-shift of the original benchmark module and associated SBT & Travis config.

**Comment by travisbrown** [comment]
@jensraaby Yep, it'd look pretty similar to what @n4to4 did for #514.

**Comment by jensraaby** [comment]
I've started a new repo with just the benchmark project here: https://github.com/jensraaby/circe-benchmark

It's not ready for prime time yet, as I can't figure out why the benchmarks don't run on "sbt test" on my box. Perhaps it's another Scala version issue.

**Comment by travisbrown** [comment]
Thanks, @jensraaby, looks great! I'll clone it to the circe org and add you as an owner.

**Comment by travisbrown** [comment]
Okay, it's up: https://github.com/circe/circe-benchmarks

I've called it circe-benchmarks because that seems better for a stand-alone project (and is probably what I'd call the module in circe if I were naming it today—to be honest I'm not sure I remember why I went with the singular). I'm happy to reconsider this if something thinks it's really bad.

**Comment by travisbrown** [comment]
Okay, with #528 this is done. Thanks @jensraaby!
