### ISSUE TITLE
Byte Array Printer

### ISSUE THREAD

**Issue by ImLiar** [circe/circe#536]
There is a discussion in finch https://github.com/finagle/finch/issues/676 about printing JSON straight into byte array, skipping string transformation.
I assume this performance-oriented feature could be useful in many projects besides finch.

Should it be a part of circe ecosystem? Just as another subproject printer.

**Comment by travisbrown** [comment]
👍, I [definitely think we should add this](https://github.com/finagle/finch/issues/676#issuecomment-271087926). I guess the simplest approach would be to add a method that accepts a `PrintWriter` and then define `pretty` in terms of that. I'll take a look this morning.

**Comment by ImLiar** [comment]
Glad to see this as a part of M2! I think it's okay to close this issue now.
