### ISSUE TITLE
sorting keys when encoding json

### ISSUE THREAD

**Issue by simao** [circe/circe#556]
I need generate a checksum for my encoded json. To get a stable signature, I need to sort the keys before the checksum, so that other parties can checksum the json and get the same checksum. See http://wiki.laptop.org/go/Canonical_JSON

Is there a way to guarantee keys will be sorted when using circe?

**Comment by travisbrown** [comment]
The `JsonObject` representation will preserve insertion order, whether you build the object with `empty` and `add` or with `from` or `fromIterable` (note though that `fromMap` doesn't preserve order), and the default printers will respect that order (unless you explicitly set `preserveOrder` to `false`, in which case the serialization order is undefined).

There isn't a direct way to sort the key-value pairs in a `JsonObject`, but it's pretty trivial to call `toVector` on the `JsonObject`, sort the vector, and then reinsert in the proper order with `JsonObject.fromIterable`.

Does that work for you?

**Comment by simao** [comment]
This is the object I am trying to serialize:

```
  case class RootRole(_type: String,
                      keys: Map[KeyId, ClientKey],
                      roles: Map[String, Role],
                      version: Int)
```

I have encoders in scope for all of these types, but how can I gurantee that those `Map` will have the sorted order? I am currently not using `JsonObject` directly. So I should call `asJson` and manipulate that `Json` object? 

Thanks

**Comment by travisbrown** [comment]
The most idiomatic way to handle this would be to use a custom encoder:

```scala
import io.circe.{ Encoder, Json, KeyEncoder }
import io.circe.syntax._

case class KeyId(id: Long)

case class RootRole(
  _type: String,
  keys: Map[KeyId, String],
  roles: Map[String, String],
  version: Int
)

object RootRole {
  private def keysToJson(keys: Map[KeyId, String]): Json = Json.fromFields(
    keys.toVector.sortBy(_._1.id).map {
      case (k, v) => k.id.toString -> v.asJson
    }
  )

  private def rolesToJson(roles: Map[String, String]): Json = Json.fromFields(
    roles.toVector.sortBy(_._1).map {
      case (k, v) => k -> v.asJson
    }
  )

  implicit val encodeRootRole: Encoder[RootRole] = Encoder.instance {
    case RootRole(t, k, r, v) => Map(
      "_type"   -> t.asJson,
      "keys"    -> keysToJson(k),
      "roles"   -> rolesToJson(r),
      "version" -> v.asJson
    ).asJson
  }
}
```

And then:

```scala
scala> RootRole("foo", Map(KeyId(100) -> "bar", KeyId(1) -> "baz"), Map.empty, 1)
res0: RootRole = RootRole(foo,Map(KeyId(100) -> bar, KeyId(1) -> baz),Map(),1)

scala> res0.asJson
res1: io.circe.Json =
{
  "_type" : "foo",
  "keys" : {
    "1" : "baz",
    "100" : "bar"
  },
  "roles" : {

  },
  "version" : 1
}
```

You could also define a custom `Map` encoder, or a wrapper case class for the maps with a custom instance that sorts before encoding, and then just use generic derivation for the `RootRole` instances. One of those options might make sense if you have a lot of case classes like this, but in general I'd suggest the approach above.

**Comment by simao** [comment]
Hi Travis,

Ah yeah this looks very good. I do have lots of classes like this, so I will look into defining custom encoders for those. With the code you just wrote I think I'll be able to sort this out.

Thanks a lot!

**Comment by travisbrown** [comment]
Closing since we've got workarounds and since we don't want to change the default behavior.

**Comment by NicolasRouquette** [comment]
I know this issue is closed; I stumbled on it searching for support for Canonical Json.

Here's how I generalized @travisbrown' answer:

```

  def canonicalJsonObject(jobj: JsonObject): JsonObject = {
    JsonObject.fromIterable(jobj.toVector.sortBy(_._1).map { case (k,j) => k -> canonicalJson(j) })
  }

  def canonicalJson(j: Json): Json = j.fold[Json](
    jsonNull = Json.Null,
    jsonBoolean = (x: Boolean) => Json.fromBoolean(x),
    jsonNumber = (x: JsonNumber) => Json.fromJsonNumber(x),
    jsonString = (x: String) => Json.fromString(x),
    jsonArray = (x: Vector[Json]) => Json.fromValues(x),
    jsonObject = (x: JsonObject) => Json.fromJsonObject(canonicalJsonObject(x))
  )
```

As long as the `Json` structures are reasonably shallow, the mutual recursion above should be reasonably safe.

**Comment by simao** [comment]
Hi,

Here is how I ended up generalizing it:

```
object CanonicalJson {

  implicit class ToCanonicalJsonOps(value: Json) {
    def canonical: String = generate(value).noSpaces
  }

  private def generate(value: Json): Json =
    value.arrayOrObject[Json](
      value,
      array => Json.fromValues(array.map(generate)),
      obj =>
        JsonObject.fromIterable {
          obj
            .toList
            .map { case (k, v) =>
              k -> generate(v)
            }.sortBy(_._1)
        }.asJson
    )
}
```

But yeah, there is the same recursion there.

**Comment by umbreak** [comment]
From the @NicolasRouquette sample, if you want the `jsonArray` to recursively apply the ordering defined in `canonicalJsonObject` you would have to change this line `jsonArray = (x: Vector[Json]) => Json.fromValues(x)` to this `jsonArray = (x: Vector[Json]) => Json.fromValues(x.map(canonicalJson))`

The `canonicalJson` method will then look like: 

```scala
def canonicalJson(j: Json): Json = j.fold[Json](
    jsonNull = Json.Null,
    jsonBoolean = (x: Boolean) => Json.fromBoolean(x),
    jsonNumber = (x: JsonNumber) => Json.fromJsonNumber(x),
    jsonString = (x: String) => Json.fromString(x),
    jsonArray = (x: Vector[Json]) => Json.fromValues(x.map(canonicalJson)),
    jsonObject = (x: JsonObject) => Json.fromJsonObject(canonicalJsonObject(x))
  )
```

**Comment by rajamony** [comment]
Thank you @NicolasRouquette and @umbreak. One additional piece is needed to make sure that the values inside an array are also sorted. The following appears to do the trick:
```
    jsonArray = (x: Vector[Json]) => Json.fromValues(x.map(canonicalJson).sortBy(_.toString)),
```
