### ISSUE TITLE
Make Codecov less enthusiastic about failing the build

### ISSUE THREAD

**Issue by travisbrown** [circe/circe#572]
As discussed in #571, Codecov sometimes fails builds unnecessarily. I think we just need to add a `.codecov.yaml` file to raise the threshold for what counts as a failure. I'd be happy to have this be quite high (like 5%), given that we'll still get the report and major changes can be addressed in code review.

**Comment by milessabin** [comment]
I think we're experiencing this problem in shapeless too.

**Comment by n4to4** [comment]
Let me take a look
