### ISSUE TITLE
emap/emapTry/prepare on Decoder[Option[T][ seem to break derived decoders 

### ISSUE THREAD

**Issue by TrustNoOne** [circe/circe#578]
Sorry if the title could be misleading. 
I basically cannot call emap or emapTry on a `Decoder.decodeOption[T]` without breaking derived decoders. 

Let's say I have an `implicit val uselessDec = Decoder.decodeOption(Decoder.decodeString).map(_ => None)`, that is a pretty useless decoder that always decodes to None regardless of the presence/absence of the string itself. 
`uselessDec` works properly, but if I change the `map` to `emap(_ => Right(None))` or `emapTry(_ => Success(None))` I always get `Attempt to decode value on failed cursor` **in derived decoders when the field is missing**  

Shouldn't `map(_ => x)`, `emap(_ => Right(x))` and `emapTry(_ => Success(x))` have identical behaviour? They actually do, but something breaks when a derived decoder uses the different versions

EDIT: the same happens with `decodeOption(decodeString).prepare(identity)`  or with `withErrorMessage("")`. It looks like only `map` is working

Here is a small example (it's in ammonite but it happens in normal code as well):

```scala
Welcome to the Ammonite Repl 0.8.2
(Scala 2.12.1 Java 1.8.0_112)
@ import $ivy.`io.circe::circe-parser:0.7.0`
import $ivy.$
@ import $ivy.`io.circe::circe-generic:0.7.0`
import $ivy.$
@ import io.circe._
import io.circe._
@ import io.circe.parser.decode
import io.circe.parser.decode
@ import scala.util.Success
@ val okDec = {
      import io.circe.generic.semiauto._
      implicit val decodeOptionStringAlwaysNone: Decoder[Option[String]] =
        Decoder.decodeOption(Decoder.decodeString).map(_ => None)
      deriveDecoder[Test]
  }
okDec: Decoder[Test] = io.circe.generic.decoding.DerivedDecoder$$anon$1@14da7be4
@ val brokenDec1 = {
      import io.circe.generic.semiauto._
      implicit val decodeOptionStringAlwaysNone: Decoder[Option[String]] =
        Decoder.decodeOption(Decoder.decodeString).emapTry(_ => Success(None))
      deriveDecoder[Test]
  }
brokenDec1: Decoder[Test] = io.circe.generic.decoding.DerivedDecoder$$anon$1@4cb61157
@ val brokenDec2 = {
      import io.circe.generic.semiauto._
      implicit val decodeOptionStringAlwaysNone: Decoder[Option[String]] =
        Decoder.decodeOption(Decoder.decodeString).emap(_ => Right(None))
      deriveDecoder[Test]
  }
brokenDec2: Decoder[Test] = io.circe.generic.decoding.DerivedDecoder$$anon$1@2d176711
@
@ decode[Test]("{}")(brokenDec1)
res9: Either[Error, Test] = Left(DecodingFailure(Attempt to decode value on failed cursor, List(DownField(x))))
@ decode[Test]("{}")(brokenDec2)
res10: Either[Error, Test] = Left(DecodingFailure(Attempt to decode value on failed cursor, List(DownField(x))))
@ decode[Test]("{}")(okDec)
res11: Either[Error, Test] = Right(Test(None))
```

**Comment by travisbrown** [comment]
Fixed in #582.
