### ISSUE TITLE
JSON key manipulation

### ISSUE THREAD

**Issue by awouda** [circe/circe#579]
Hi,

I'm having a hard time to have the keys generated in all lowercase. 

I know I can use the forProductN method, but as we have very large case classes ( > 22 properties) , I wonder if there is generic way of setting the casing of generated keys for all fields of all case classes.

tia

Alex

**Comment by jilen** [comment]
[This](http://stackoverflow.com/questions/37583877/transform-all-keys-from-underscore-to-camel-case-of-json-objects-in-circe/37585818#37585818) may help , Note this is for legacy circe version,

**Comment by travisbrown** [comment]
@awouda If you're on circe 0.6+, the new generic-extras module supports arbitrary transformations for field names in generic derivation—see the [release notes here](https://github.com/circe/circe/releases/tag/v0.6.0-RC1) for some discussion and examples.

**Comment by awouda** [comment]
Thanks, 

I'm using now
`  val withLowerCaseKeys: String ⇒ String =  _.toLowerCase

  implicit val customConfig: Configuration = Configuration.default.copy(transformKeys = withLowerCaseKeys)`

But the keys are still camelCase. I need all keys (from the root of the doc / case class) to be lowercased, so maybe I need a discriminator, but how to set that on the root level?

**Comment by travisbrown** [comment]
@awouda Do you have a complete working example that shows the problem? The problem may be that your configuration needs to be in implicit scope at the site where the encoders or decoders are used, not where you define your case classes.

**Comment by entangled90** [comment]
@awouda do you imported `io.circe.generic-extras.semiauto._/auto._` instead of `io.crice.generic.seminauto._/auto._` ?

**Comment by travisbrown** [comment]
Closing as non-reproducible.
