### ISSUE TITLE
Encoder should remove None: Option[T] values

### ISSUE THREAD

**Issue by mikaelstaldal** [circe/circe#584]
It would be nice if the Encoder would remove the key/value completely when the type is `Option[T]` and the value is `None`. Currently, it encodes None to JSON null.

(Json4s works this way.)

This code:
```
  case class Test(foo: String, bar: Option[String])
  implicit val testEncoder: Encoder[Test] = deriveEncoder
  println(Test("FOO", None).asJson.noSpaces)
```
currently prints:
```
{"foo":"FOO","bar":null}
```

I would like it to be:
```
{"foo":"FOO"}
```

**Comment by vpavkin** [comment]
@mikaelstaldal you should just use a custom `Printer` with `dropNullKeys = true`.
By default it's `true`.

**Comment by mikaelstaldal** [comment]
Ah, that works. But it seems like `dropNullKeys` by default is `false`?

This is also something that is missing from documentation.

**Comment by vpavkin** [comment]
yes, it's false :) I made a mistake and fixed the comment afterwards

**Comment by ckozak** [comment]
What was the reason to make `dropNullKeys = false` by default? It seems that not putting nulls is more common among other libraries.

**Comment by bergmark** [comment]
I commented on this elsewhere, so a quick repeat:

My take is that the printer should not modify the actual JSON format. This is something each `Encoder` should decide for itself. Inevitably there will be a case where you want to combine the two options for different types, AFAICT that's not possible at the moment.

**Comment by Mahoney** [comment]
Could nested options be interpreted differently? For
```case class Foo(bar: Option[Option[String])```
```Foo(None)``` = ```{}```
```Foo(Some(None)``` = ```{"bar": null}```
```Foo(Some("actual data")``` = ```{"bar": "actual data"}```

**Comment by naderghanbari** [comment]
I agree that the `Printer` should not touch the JSON by default but I also agree that the `Printer` should have the power to make the result nicer if you want to. This could help in some cases where the actual value might be really `null` (Java interop). So in other words I think the `Printer` is fine as is.

I think the encoder, though, should drop `None` values by default and not encode them as `null`. It should, however, encode genuine `null` values as `null` and not drop them. This is probably what you'd expect if you are a Scala developers (or a functional programmer in general). 

Similar to `dropNullKeys = false` I think the encoder configuration can have something like `dropNone = true`.

**Comment by travisbrown** [comment]
Now that we have dropNullValues on both the printer and Json I think we can close this.
