### ISSUE TITLE
Less import statements

### ISSUE THREAD

**Issue by jilen** [circe/circe#590]
To use circe I always need to import
```scala
io.circe._
io.circe.generic.auto._
io.circe.parser._
io.circe.optics.JsonPath._
```
Is there a single `import`  rules them all ?

**Comment by travisbrown** [comment]
Not currently, but we could consider adding something like a circe-all module that would allow a `circe.all._` import.

**Comment by travisbrown** [comment]
Closing as `won't fix`, especially now that we have alternatives to generic derivation and it's not entirely clear what a good set of default `all` imports would be.
