### ISSUE TITLE
NPE when serializing case class with fields set to NULL

### ISSUE THREAD

**Issue by haggy** [circe/circe#598]
Repro:

```scala
import io.circe.generic.auto._
import io.circe.syntax._

case class StringFieldsSetToNull(field1: String, field2: String)
val n = StringFieldsSetToNull(null, "foo")

n.asJson.noSpaces // <-- This causes NPE since field1 is null
```

The error:
```
java.lang.NullPointerException
	at io.circe.Printer.printJsonString(scratch_117.scala:168)
	at io.circe.Printer.printJsonAtDepth(scratch_117.scala:227)
	at io.circe.Printer.printJsonObjectAtDepth(scratch_117.scala:200)
	at io.circe.Printer.printJsonAtDepth(scratch_117.scala:230)
	at io.circe.Printer.pretty(scratch_117.scala:240)
	at io.circe.Json.noSpaces(scratch_117.scala:103)
	at #worksheet#.get$$instance$$res0(scratch_117.scala:7)
	at #worksheet#.#worksheet#(scratch_117.scala:22)
```

Now I don't think this needs to be "fixed" in the sense that Circe knows how to gracefully handle it. I just think circe should have better logging of what field (if possible) is null when it shouldn't be and of course avoid NPE's wherever possible. 

Apologies if there's already an issue for this. I couldn't find one. Let me know if you need any other info.

**Comment by knutwalker** [comment]
Using `null` directly is quite unusual for Scala and libraries often treating it like it doesn't exist (or rather, is used). More explanation also in https://github.com/circe/circe/issues/538#issuecomment-271174626.

**Comment by haggy** [comment]
@knutwalker I agree that you would not want to pass in null explicitly, that was just done for the most simply repro case. My issue was a little different in that we had data coming in via JSON but we have a client that uses a different json lib (`json4s` with jackson backend in this case) which allowed the JSON null to map directly to a `NULL` in the case class for that field. Because of that, a case class with a null field was passed into `asJson` and subsequently `noSpaces`. 

The odd thing is that the serialization methods from `Json -> String` treat null differently than the transformer from cass class `T -> Json`. In the repro case above, `n.asJson` works fine. It is only a problem when you try to then call `noSpaces` on that `Json` instance.

**Comment by travisbrown** [comment]
@haggy `n.asJson` "works" because the NPE won't happen until the null string is dereferenced. This matches the behavior of the standard library:

```scala
scala> val strings = List("foo", null)
strings: List[String] = List(foo, null)

scala> strings.size
res0: Int = 2

scala> strings.head
res1: String = foo

scala> strings.map(_.length)
java.lang.NullPointerException
  at .$anonfun$res2$1(<console>:13)
  at .$anonfun$res2$1$adapted(<console>:13)
  at scala.collection.immutable.List.map(List.scala:276)
  ... 31 elided
```

 In general I'd recommend policing nulls as close to the boundary of your program as possible, which I guess in this case would be at the point you get the data from json4s (or the client using it).

It's just not really feasible to have circe encoders make sure there aren't any nulls anywhere in the data they're serializing—it would mean a lot of extra code to maintain and some extra runtime cost (and even then it wouldn't work in all situations).

**Comment by rpless** [comment]
@travisbrown I asked @haggy to post a reproducer after we say this behavior. I'm sorry for the noise, I wasn't aware (but should have guessed) that this was a design decision. I am in favor of closing this issue. I am also happy to submit a PR to the docs that shows this exception and the rationale for why it occurs.

@haggy The repro from `T -> Json` makes sense cause its a Scala (Java) null and not a JSON null. 
We should either go full circe (for several reasons including this one) or start doing some of the shapeless magic to check for nulls that we were talking about today.

**Comment by haggy** [comment]
Cool thanks all for the quick responses. Moral of the story.. stop using `json4s` ;)

**Comment by haggy** [comment]
All questions answered so closing this out.

**Comment by RicoGit** [comment]
Adding `withNull(Json.Null)` before converting `Json -> String` fix NPE. Maybe it'll help somebody.
 `n.asJson.withNull(Json.Null).noSpaces` - works fine
