### ISSUE TITLE
Configuration documentation

### ISSUE THREAD

**Issue by laverboy** [circe/circe#599]
There doesn't seem to be any documentation around the configuration options.

I was trying to add a type field to my encoded json and had to piece bits together from the release notes, a blog entry and ask a question on gitter.

Are there any plans to add this? Thanks

**Comment by asoltysik** [comment]
Working on this one.

**Comment by hamnis** [comment]
Closing in cleanup run, If anyone cares about this, please comment and I'll reopen.
