### ISSUE TITLE
Make Encoder.forProductN methods actually use… ProductN

### ISSUE THREAD

**Issue by travisbrown** [circe/circe#630]
Currently all the `Encoder.forProductN` methods take a function from the type that we're defining an `Encoder` for to a tuple with the appropriate arity. I don't see any reason not to allow the more general `Source => ProductN[...]`, which would make definitions simpler for case classes (no more `(User.unapply _).andThen(_.get)` stuff) and would also help with e.g. Scrooge-generated types.

**Comment by lvicentesanchez** [comment]
I could help with this one, I would just need a bit more of context.

**Comment by travisbrown** [comment]
Thanks @lvicentesanchez! Essentially I think (hope?) it'll just be changing tuples to `Product` in the code gen and making sure nothing breaks.

**Comment by lvicentesanchez** [comment]
@travisbrown that should be easy, I re-read the ticket after my commit and I realise that all the information needed was already in the ticket. I will give it a go when I get home.

**Comment by lvicentesanchez** [comment]
@travisbrown I tried yesterday and found a problem. If I replace the tuples of `ProductN` of the right arity, examples like the `WrappedStringOptional` don't compile, you need to do something like `Encoder.forProduct1(o => Tuple1(o))`. I can avoid that by doing something like this,

```
val outputType = if (arity != 1) s"Product$arity[${`A..N`}]" else `A..N`
```

and the forProductN definition would be rewritten this way:

```
final def forProduct$arity[${`A..N`}, Source]($memberNames)(f: Source => $outputType)
```

So... no `Product1`. That makes possible to define encoders for case classes like this:

```
Encoder.forProductN(CaseClass3.unapply)
```
If you are happy with this solution I can submit a PR.

**Comment by lvicentesanchez** [comment]
And just after sending the message... everything compiles, but it seems that there is a problem with some JS tests.

**Comment by lvicentesanchez** [comment]
So... SBT bit me, the managed classes were not discarded and that's why everything was still compiling before I removed all target folders:
```
[error] /home/luis/development/repositories/github/bigcentech/circe/modules/tests/jvm/target/scala-2.12/src_managed/test/io/circe/ProductCodecSuite.scala:89: type mismatch;
[error]  found   : Option[(String, String, String, String, String, String, String)]
[error]  required: Product7[?,?,?,?,?,?,?]
[error]       Encoder.forProduct7("s0", "s1", "s2", "s3", "s4", "s5", "s6")(Cc7.unapply)
```
So... this actually makes more sense as I failed to see how using `ProductN` would make case classes defintions easier. You would have to replace them by `Option[ProductN[...]]`, but I'm not qualified to make that decision.

**Comment by travisbrown** [comment]
Yeah, the fact that there's no `Option`-less version of `unapply` for case classes is a perennial pain in the ass, and this change isn't going to help with that, unfortunately.

**Comment by travisbrown-stripe** [comment]
@lvicentesanchez You're right, I was overly optimistic in the issue statement, but I still think this is worthwhile since it's semantically more accurate, doesn't change usage, and helps out for cases like Scrooge-generated types. Do you mind pushing your branch? I'd be happy to rebase, etc.

**Comment by lvicentesanchez** [comment]
Sure. I can do that when I get back home or early tomorrow.

**Comment by travisbrown** [comment]
Done in #673.
