### ISSUE TITLE
JsonDiff

### ISSUE THREAD

**Issue by darkfrog26** [circe/circe#633]
I know this was discussed in #281, but referenced within that ticket was this code: https://github.com/agourlay/cornichon/blob/c2e0974ac2a27dc973e0a3ffdc8520ea55b6effe/src/main/scala/com/github/agourlay/cornichon/json/JsonDiff.scala

I know for more advanced functionality diffson is a very useful tool, but for basic diff'ing it is overkill and adds needless complexity.  As shown in the above code basic diff'ing can be accomplished with a fairly minimal amount of Circe code.  I'd like to propose the above be introduced as a very light-weight solution for anyone wanting basic diff support in Circe without the requirement of a third-party library.

It could be incorporated as-is (which I've done in my own project with minimal modifications) or the basic concepts could be introduced in a more Circe-esque way.

**Comment by hamnis** [comment]
Use [diffson](https://github.com/gnieh/diffson) for this
