### ISSUE TITLE
Automatic derivation of a configured encoder/decoder fails for a newtype in a case class

### ISSUE THREAD

**Issue by tarao** [circe/circe#641]
`io.circe.generic.extras.AutoDerivation` fails to find an encoder/decoder for a case class with a field of `shapeless.newtype.Newtype[]`.

It was not failing before v0.8.0.  I confirmed that the following code doesn't compile in Scala 2.12.2/2.11.11 with circe v0.8.0/v0.9.0-SNAPSHOT but does compile in Scala 2.12.2/2.11.11 with circe v0.7.1.

```scala
  import io.circe.{Decoder, Encoder}
  import io.circe.generic.extras.auto._
  import shapeless.newtype
  import shapeless.syntax.unwrapped._

  type URL = newtype.Newtype[String, URL.Tag]
  object URL {
    trait Tag

    def apply(url: String): URL = newtype(url)
  }

  case class Item(url: URL)

  implicit val encoder: Encoder[URL] =
    Encoder[String].contramap(_.unwrap)

  implicit val decoder: Decoder[URL] =
    Decoder[String].map(URL(_))

  Encoder[Item]
```

```
<console>:48: error: could not find implicit value for parameter instance: io.circe.Encoder[Item]
         Encoder[Item]
                ^
```

I investigated by myself and suspect that it fails to find [`Keys.Aux[]`](https://github.com/circe/circe/blob/e78cce6d0308b252d8210d5be32cbd89b9039b96/modules/generic-extras/src/main/scala/io/circe/generic/extras/encoding/ConfiguredObjectEncoder.scala#L18) but I'm not sure because I'm not a shapeless expert.

**Comment by travisbrown** [comment]
Sorry I didn't catch this earlier, but the issue here is just that the configurable generic derivation in generic-extras no longer provides a default configuration in 0.8.0. Adding the following will fix the issue:

```scala
import io.circe.generic.extras.defaults._
```

See the [release notes](https://github.com/circe/circe/releases/tag/v0.8.0-RC1) for details.

The error message is unfortunately pretty useless, and if someone wants to take a shot at improving it, I'd happily review, but it's not a priority for me right now, so I'm going to close this issue.

**Comment by tarao** [comment]
Thanks for replying!

Actually, I knew about the default configuration implicit value but it seems that I missed it when I tried to make a minimum reproducing example.  As you said, I confirmed that the example compiles with the configuration, so this was not describing my problem.  I will investigate further to find what the actual problem was and will report it when I find something.  Thanks anyway!

**Comment by tarao** [comment]
Now I could reproduce the problem with importing `io.circe.generic.extras.defaults._`. #688 describes the problem.
