### ISSUE TITLE
automatic encoder fails with fields with names like `a-b`

### ISSUE THREAD

**Issue by stew** [circe/circe#665]
It seems like when I have a case class with similarly named fields, I can get encoders which don't work correctly:

     import io.circe._, io.circe.generic.semiauto._                                                  | package healthyswitchy
     import io.circe.syntax._                                                                        |
                                                                                                     | import io.circe._
     case class Foo(a: Int, b: Int, `a-c`: Int)                                                      | import io.circe.generic.extras._
                                                                                                     |
     object TestCirce extends scala.App {                                                            | sealed trait UpDown
                                                                                                     | case object Up extends UpDown
       implicit val fooEncoder: Encoder[Foo] = deriveEncoder                                         | case object Down extends UpDown
       println(Foo(a=1,b=2,`a-c`=3).asJson)                                                          |
     }                                                                                               | object UpDown {

The output I get when running this:

    [info] Running TestCirce
    {
      "a" : 1,
      "b" : 3,
      "a-c" : 2
    }

Note that the values of `b` and `a-c` have switched.

**Comment by ceedubs** [comment]
Even without circe in the picture, note that something perplexing is also happening with the generated `toString`:

```scala
scala> case class Foo(a: Int, b: Int, `a-c`: Int)   
defined class Foo                                   

scala> val foo = Foo(1, 2,3)                        
foo: Foo = Foo(1,3,2)                               

scala> foo.a                                        
res0: Int = 1                                       

scala> foo.b                                        
res1: Int = 2                                       

scala> foo.`a-c`                                    
res2: Int = 3
```

**Comment by travisbrown** [comment]
Yeah, this is incredibly weird, and `LabelledGeneric` gets it wrong as well:

```scala
scala> case class Foo(a: Int, b: Int, `a-c`: Int)
defined class Foo

scala> val foo1 = Foo(1, 2, 3)
foo1: Foo = Foo(1,3,2)

scala> val foo2 = Foo(a = 1, b = 2, `a-c` = 3)
foo2: Foo = Foo(1,3,2)

scala> shapeless.LabelledGeneric[Foo].to(foo1)
res0: Int with shapeless.labelled.KeyTag[Symbol with shapeless.tag.Tagged[String("a")],Int] :: Int with shapeless.labelled.KeyTag[Symbol with shapeless.tag.Tagged[String("b")],Int] :: Int with shapeless.labelled.KeyTag[Symbol with shapeless.tag.Tagged[String("a-c")],Int] :: shapeless.HNil = 1 :: 3 :: 2 :: HNil
```

Weirdly enough it looks like it could be vaguely related to [this bug I ran into last weekend](https://twitter.com/travisbrown/status/873538401043140608).

**Comment by ceedubs** [comment]
@rossabaker shed some light on this:

```scala
scala> Foo(1, 2, 3).productIterator.toList
res4: List[Any] = List(1, 3, 2)
```

**Comment by ceedubs** [comment]
Another coworker noticed that the default ammonite pretty printer does not seem to be impacted by this, which I found curious.

```
Welcome to the Ammonite Repl 0.7.7
(Scala 2.11.8 Java 1.8.0_131)
@ case class Foo(a: Int, b: Int, `a-c`: Int) 
defined class Foo
@ val foo = Foo(1,2,3) 
foo: Foo = Foo(1, 2, 3)
@ foo.productIterator.foreach(println) 
1
3
2
```

**Comment by travisbrown** [comment]
For what it's worth [circe-derivation](https://github.com/travisbrown/circe-derivation) gets it right:

```scala
scala> case class Foo(a: Int, b: Int, `a-b`: Int)
defined class Foo

scala> io.circe.derivation.deriveEncoder[Foo].apply(Foo(1, 2, 3)).noSpaces
res0: String = {"a":1,"b":2,"a-b":3}
```

**Comment by vkostyukov** [comment]
It looks like scalac generates a wrong order for members in `productElement`. Here is the output for `-Xprint:jvm`:

```scala
 <synthetic> def productElement(x$1: Int): Object = {
      case <synthetic> val x1: Int = x$1;
      (x1: Int) match {
        case 0 => scala.Int.box(iw$Foo.this.a())
        case 1 => scala.Int.box(iw$Foo.this.a-c())
        case 2 => scala.Int.box(iw$Foo.this.b())
        case _ => throw new IndexOutOfBoundsException(scala.Int.box(x$1).toString())
      }
    };
```

**Comment by SethTisue** [comment]
looks like https://github.com/scala/bug/issues/8831

**Comment by travisbrown** [comment]
I'm going to close this as out-of-scope for circe since we're just inheriting the behavior from Shapeless, and since there are a number of viable workarounds.
