### ISSUE TITLE
Auto derivation of an Either 

### ISSUE THREAD

**Issue by danbills** [circe/circe#672]
See [gist](https://gist.github.com/danbills/a6fe54d7e89c7e3e232fcab69a6f6fe8).

Unless I'm missing something it seems that auto-deriving a decoder for Either isn't working.

I'm currently using a workaround of circe-shapeless and coproduct but that is suboptimal with only 2 potential types.

**Comment by danbills** [comment]
Either is expecting a Right or Left as in 

```scala
scala> Hi(Right("foo")).asJson
res7: io.circe.Json =
{
  "s" : {
    "Right" : {
      "b" : "foo"
    }
  }
}
```

**Comment by travisbrown** [comment]
@danbills It's worth noting that that's kind of just an accident of `auto`, and you probably will generally want to use `Decoder.decodeEither` or `Decoder#or` to create explicit `Either` decoders.

**Comment by danbills** [comment]
I was able to produce the expected behavior by declaring the following decoder for Either[A,B]:

```scala
implicit def j[A,B](implicit a: Decoder[A], b: Decoder[B]): Decoder[Either[A,B]] = 
    new Decoder[Either[A, B]] {
      final def apply(c: HCursor): Result[Either[A, B]] = {
        val d = a split b
        val l = d(Left(c))
        val r = d(Right(c))
        if (l.isLeft) r else l
      }
    }
```

**Comment by danbills** [comment]
or even simpler:

```scala
implicit def h[A,B](implicit a: Decoder[A], b: Decoder[B]): Decoder[Either[A,B]] = {
        val l: Decoder[Either[A,B]]= a.map(Left.apply)
        val r: Decoder[Either[A,B]]= b.map(Right.apply)
        l or r
    }
```

**Comment by nafg** [comment]
Forget about derivation, why not have it out of the box (like Option)?

**Comment by Mondlicht1** [comment]
> Forget about derivation, why not have it out of the box (like Option)?

 Likely due to potential ambiguity. Could cause hard-to-track unexpected behavior if it's an implicit decoder.
