### ISSUE TITLE
Rename dropNullKeys

### ISSUE THREAD

**Issue by travisbrown** [circe/circe#678]
I hate this name for the `Parser` configuration option. It's inherited from Argonaut, and unfortunately I didn't change it immediately. It just doesn't make sense—you're dropping null-valued fields, not keys. Keys don't really have anything to do with it.

I'd prefer `dropNullValues` or `dropNullValueFields`. This change would affect a lot of code, and unfortunately it can't easily be done across a deprecation cycle since the most common usage is `.copy(dropNullKeys = true)`. Migration would be a simple `sed`, though, and I don't want to get stuck with a nonsense name forever just because I didn't fix it early enough.

What do people think about making this change before 1.0?

**Comment by bergmark** [comment]
How about just `dropNulls`?

**Comment by travisbrown** [comment]
Done in #702.
