### ISSUE TITLE
Decoder.state.decodeField[Option[_]] moves cursor on None

### ISSUE THREAD

**Issue by kshakir** [circe/circe#708]
Thanks for your patience if I'm missing something.

I'm still new to `circe`… and `cats`… and `shapeless`… and have never tried pure haskell-- but I was trying to put together a generic version of #375 and tripped over a case where `Decoder.state.decodeField[Option[_]]` seems to move the cursor even when the value is `None`.

```scala
import io.circe.Decoder
import io.circe.parser._
import cats.instances.either._

case class Foo(a: Option[String], b: Int)

implicit val decodeFoo: Decoder[Foo] = Decoder.fromState(
  for {
    a <- Decoder.state.decodeField[Option[String]]("a")
    b <- Decoder.state.decodeField[Int]("b")
    _ <- Decoder.state.requireEmpty
  } yield Foo(a, b)
)

val good =
  """|{
     |  "a": "hello",
     |  "b": 1
     |}
     |""".stripMargin

val shouldBeGood =
  """|{
     |  "b": 1
     |}
     |""".stripMargin

println(decode[Foo](good))
println(decode[Foo](shouldBeGood))
```

outputs

```scala
Right(Foo(Some(hello),1))
Left(DecodingFailure(Attempt to decode value on failed cursor, List(DownField(a))))
```

I managed to copy the original [`decodeField`](https://github.com/circe/circe/blob/v0.8.0/modules/core/shared/src/main/scala/io/circe/Decoder.scala#L819-L829) to a modified [`decodeFieldOption`](https://github.com/broadinstitute/clio/blob/d1d35bf98bf379c257bb495ab426141a340c227f/clio-server/src/main/scala/org/broadinstitute/clio/util/json/StateDecoder.scala#L72-L86) that seems to work for our purposes. However it's not a PR as I'm not sure if it's "category-theory" correct. I'm still searching for a good underscore book/video to explain `StateT`, `Kleisli`, etc.

**Comment by travisbrown** [comment]
Hmm, good catch. Your workaround looks fine to me, although I'd prefer `decodeField` to work with `Option` out of the box. I'll take a look as soon as possible.
