### ISSUE TITLE
Failure with typelevel compiler and induction heuristics

### ISSUE THREAD

**Issue by Astrac** [circe/circe#710]
Given this example:

```
case class Id[T](value: String)

object Id {
  implicit def idEncoder[T]: Encoder[Id[T]] = Encoder[String].contramap[Id[T]](_.value)
}

case class Foo(x: String)
case class Foobar(id: Id[Foobar], foo: Foo)

object Foobar {
  implicit val fooEncoder: Encoder[Foo] = deriveEncoder
  implicit val foobarEncoder: Encoder[Foobar] = deriveEncoder
}
```

This compiles fine on lightbend scala and typelevel scala but if I enable `-Yinduction-heuristics` in the latter this suddenly fail at the derivation of `Encoder[Foobar]`. 

If I change the `Foobar` object to:

```
object Foobar {
  implicit val fooEncoder: Encoder[Foo] = deriveEncoder
  implicitly[Encoder[Id[Foobar]]]
  implicit val foobarEncoder: Encoder[Foobar] = deriveEncoder
}
```

then it doesn't fail on the `foobarEncoder` but crashes the typelevel compiler triggering this bug:

https://www.bountysource.com/issues/46109047-compiler-error-with-yinduction-heuristics

This version manage to compile fine instead:

```
object Foobar {
  implicit val fooEncoder: Encoder[Foo] = deriveEncoder
  implicit val foobarIdEncoder: Encoder[Id[Foobar]] = implicitly
  implicit val foobarEncoder: Encoder[Foobar] = deriveEncoder
}
```

**Comment by travisbrown** [comment]
Thanks for the report! My current goal is to have all tests passing on TLC with options like `-Yinduction-heuristics` enabled by the 0.10.0 release, but I'm not sure it'll happen by 0.9.0.

**Comment by hamnis** [comment]
Closing in cleanup run, If anyone cares about this, please comment and I'll reopen.
