### ISSUE TITLE
Unexpected decoding errors when using forProduct* decoders and optional fields

### ISSUE THREAD

**Issue by netvl** [circe/circe#721]
Consider this code:
```scala
import io.circe._
import io.circe.generic.auto._

object Test extends App {
  case class First(_notify: Option[Second])
  case class Second(value: Option[Vector[String]])

  implicit val firstDecoder: Decoder[First] = Decoder.forProduct1("notify")(First.apply)

  val input =
    """
      |{
      |  "notify": {
      |    "value": ["a", "b"]
      |  }
      |}
    """.stripMargin

  val json = parser.parse(input).fold(throw _, identity)
  println(json.as[First].fold(throw _, identity))
}
```

This code fails with the following exception:
```
Exception in thread "main" DecodingFailure(CNil, List(DownField(value), DownField(notify)))
```

If I remove either option in the case classes definitions,, or if I avoid `forProduct1` and rely on the automatic derivation (although in this case the JSON input has to be changed appropriately), then everything works as expected. Funny thing, if I add an explicit decoder with `forProduct1` for `Second`, I get a NullPointerException:
```
Exception in thread "main" java.lang.NullPointerException
	at io.circe.Decoder$$anonfun$decodeOption$1.apply(Decoder.scala:652)
	at io.circe.Decoder$$anonfun$decodeOption$1.apply(Decoder.scala:650)
	at io.circe.Decoder$$anon$27.tryDecode(Decoder.scala:341)
	at io.circe.ACursor.as(ACursor.scala:336)
	at io.circe.ACursor.get(ACursor.scala:343)
	at io.circe.ProductDecoders$$anon$1.apply(ProductDecoders.scala:12)
	at io.circe.Json.as(Json.scala:97)
```

This bug affected me when I tried to map the `notify` field in the input JSON object to the `_notify` field in my own case class, while keeping everything else derived automatically.

**Comment by travisbrown** [comment]
@netvl What version are you on? That code works as written for me on both 0.8.0 and 0.9.0-M1, and I'm not sure what could cause that to happen on earlier versions.

For the NPE, I'm guessing the issue involves the initialization order of vals in an `App` object, but if you can post a reproduction I'm happy to take a look.

**Comment by anushaML** [comment]
@netvl Adding an explicit decoder for second works for me:

```
implicit val secondDecoder: Decoder[Second] = Decoder.forProduct1("value")(Second.apply)
implicit val firstDecoder: Decoder[First] = Decoder.forProduct1("notify")(First.apply)
```

**Comment by netvl** [comment]
Indeed, this is strange. I tried running the example again, and it worked. And yes, the NPE thing certainly did happen because I used `val` instead of `lazy val`.
