### ISSUE TITLE
Discriminator does not have effect when deriving sealed trait

### ISSUE THREAD

**Issue by fr3akX** [circe/circe#726]
There's a problem with semiautomatic derivations with discriminator when deriving sealed trait.
```
object Adt {
  sealed trait Result
  case class SimpleResult(res: String) extends Result
  case class ResultWrapper(res: Result)
}

object Codec extends AutoDerivation {
  import io.circe.generic.semiauto._

  implicit val configuration: Configuration = Configuration.default
    .withDiscriminator("type")
    .withSnakeCaseConstructorNames
    .withSnakeCaseMemberNames

  implicit val encWrap: Encoder[Result] = deriveEncoder[Result]
}

object Application extends App {
  import Codec._

  val unwrappedEncoded = {
    val r: Result = SimpleResult("this is result")
    r.asJson.spaces2
  }

  println(s"Unwrapped Encoded: $unwrappedEncoded")
}
```

results into: 
```
{
  "SimpleResult" : {
    "res" : "this is result"
  }
}
```

but expected result is: 
```
{
    "res" : "this is result",
    "$type" : "simple_result"
  }
```
if I wrap result in ResultWrapper, result is correct.

**Comment by scalway** [comment]
example copied to scalafiddle https://scalafiddle.io/sf/8XAonaP/0

**Comment by scalway** [comment]
Ok... You have wrong import. This is next fiddle that shows what is changed!
https://scalafiddle.io/sf/8XAonaP/2

**Comment by fr3akX** [comment]
@scalway thnx

**Comment by feoktant** [comment]
@fr3akX , @scalway could you show right imports? I faced with the same issue, but link doesn't work

**Comment by fr3akX** [comment]
@feoktant 
`import io.circe.generic.extras._`

**Comment by ruioliveiras** [comment]
After some trouble with the same issue discribed here, i found the sollution. 
`import io.circe.generic.semiauto._`  != 
`import io.circe.generic.extras.semiauto._`

Example if you want to use: 
`implicit lazy val config: Configuration = Configuration.default
    .withDiscriminator("type")`

You must import `import io.circe.generic.**extras**.semiauto._` 
and use it like this: `implicit lazy val codec: Codec[Foo] = deriveConfiguredCodec[Foo]`
