### ISSUE TITLE
Should deprecated ACursor.fields have same type in 0.9?

### ISSUE THREAD

**Issue by lukestephenson** [circe/circe#736]
In 0.8 it is defined as:
```
def fields: Option[Vector[String]]
```
In 0.9 it is defined as:
```
@deprecated("Use keys", "0.9.0")
final def fields: Option[Iterable[String]] = keys
```

While this looks innocent enough, it can cause client applications to break.  For example, we had a Decoder which expects a single json key defined as:
```
cursor.fields match {
  case Some(Vector(fieldName)) => ...
  case fields => Left(DecodingFailure(s"Expected to only have one field: $fields", cursor.history))
}
```

When upgrading to 0.9, this broke the decoder because `fields` contained something other than a `Vector` so the pattern match always failed.  The compiler doesn't pick this up, and the pattern match is still valid, even though it will always result in the failure case.

I realise this is a breaking change, but wonder if the breaking change should have been limited to the new `keys` function leaving `fields` honouring it's original contract.  Would be as simple as replacing with:
```
@deprecated("Use keys", "0.9.0")
final def fields: Option[Vector[String]] = keys.map(_.toVector)
```

**Comment by travisbrown** [comment]
Agreed—making the change in the deprecated method as well isn't ideal, and I'm happy to make a breaking change to switch it back in 0.9.0-RC1. If you'd like to open a PR that'd be great—otherwise I should be able to get to it by tomorrow night.

**Comment by lukestephenson** [comment]
I'm going to have a stab at submitting a PR as the change is simple.

Having some trouble getting the project to build though:
```
coursier.ResolutionException: 1 not found
    /Users/luke.stephenson/.sbt/preloaded/org.scala-lang.modules/scala-parser-combinators_2.12/1.0.4/bundles/scala-parser-combinators_2.12.jar
```

**Comment by lukestephenson** [comment]
I got the project to build by removing coursier from the plugins.  PR submitted to fix.
