### ISSUE TITLE
Adaptive JSON object size estimator for binary printers

### ISSUE THREAD

**Issue by vkostyukov** [circe/circe#738]
Circe's `reuseWriters` printing option is great and we need something similar for binary printing. One idea is to predict the size of the printing object so we can allocate an ultimate destination buffer in one shot (no need to copy-and-grow iterations).

Netty uses this [AdaptiveRecvByteBufAllocator](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/AdaptiveRecvByteBufAllocator.java) to achieve the very same goal. We can use it for inspiration.

I'd be happy to give it a try.

**Comment by travisbrown** [comment]
Sure, sounds good to me!
