### ISSUE TITLE
Handle deriving from case classes where "type" is a needed parameter

### ISSUE THREAD

**Issue by tripl3dogdare** [circe/circe#743]
I'm attempting to decode a bit of JSON into a case class (using auto), but unfortunately, one of the fields of the JSON I'm working with is `type`. This presents a problem, as `type` is a reserved keyword in Scala - how should I handle this?

**Comment by travisbrown** [comment]
You can escape the member name with backticks—e.g.:

```scala
scala> import io.circe.generic.auto._, io.circe.jawn.decode
import io.circe.generic.auto._
import io.circe.jawn.decode

scala> case class Foo(value: Int, `type`: String)
defined class Foo

scala> decode[Foo]("""{ "value": 100, "type": "MyFoo" }""")
res0: Either[io.circe.Error,Foo] = Right(Foo(100,MyFoo))
```

This isn't circe-specific (it'll work for any keyword in any case class), but circe's generic derivation will handle it correctly.

**Comment by tripl3dogdare** [comment]
Thanks! Wasn't sure if that would work properly in this case, since I didn't recall if the backticks were part of the method signature or not.

**Comment by travisbrown** [comment]
@tripl3dogdare No, they're gone by then:

```scala
  public java.lang.String type();
    descriptor: ()Ljava/lang/String;
    flags: ACC_PUBLIC
    Code: ...
```

…but more importantly they're not included in the labels that we get from Shapeless's `LabelledGeneric`, which are carried over verbatim (even when the actual JVM method signature is escaped by the Scala compiler):

```
scala> case class Qux(`type`: String, `!@^!*&@^`: Int)
defined class Qux

scala> shapeless.LabelledGeneric[Qux]
res6: shapeless.LabelledGeneric[Qux]{type Repr = String with shapeless.labelled.KeyTag[Symbol with shapeless.tag.Tagged[String("type")],String] :: Int with shapeless.labelled.KeyTag[Symbol with shapeless.tag.Tagged[String("!@^!*&@^")],Int] :: shapeless.HNil} = shapeless.LabelledGeneric$$anon$1@1419dc59
```
