### ISSUE TITLE
Fresh clone and library dependency resolution error(sbt and intellij)

### ISSUE THREAD

**Issue by mahendrapk** [circe/circe#748]
I have other sbt projects and all seem to work fine. `Circe` failed to open in intellij and sbt with following message:

coursier.ResolutionException: Encountered 4 error(s) in dependency resolution:
  org.scala-sbt:global-plugins;sbtVersion=0.13;scalaVersion=2.10:0.0:
    not found:
      https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
      https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
      /Users/abcdefghk/.ivy2/local/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
      https://repo1.maven.org/maven2/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
      /Users/abcdefghk/.sbt/preloaded/org.scala-sbt/global-plugins/0.0/ivys/ivy.xml
      /Users/abcdefghk/.sbt/preloaded/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
      http://download.eclipse.org/jgit/maven/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
  org.scala-sbt:global-plugins;sbtVersion=0.13;scalaVersion=2.10:0.0:
    not found:
      https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
      https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
      /Users/abcdefghk/.ivy2/local/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
      https://repo1.maven.org/maven2/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
      /Users/abcdefghk/.sbt/preloaded/org.scala-sbt/global-plugins/0.0/ivys/ivy.xml
      /Users/abcdefghk/.sbt/preloaded/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
      http://download.eclipse.org/jgit/maven/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
  org.scala-sbt:global-plugins;sbtVersion=0.13;scalaVersion=2.10:0.0:
    not found:
      https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
      https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
      /Users/abcdefghk/.ivy2/local/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
      https://repo1.maven.org/maven2/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
      /Users/abcdefghk/.sbt/preloaded/org.scala-sbt/global-plugins/0.0/ivys/ivy.xml
      /Users/abcdefghk/.sbt/preloaded/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
      http://download.eclipse.org/jgit/maven/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
  org.scala-sbt:global-plugins;sbtVersion=0.13;scalaVersion=2.10:0.0:
    not found:
      https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
      https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
      /Users/abcdefghk/.ivy2/local/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
      https://repo1.maven.org/maven2/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
      /Users/abcdefghk/.sbt/preloaded/org.scala-sbt/global-plugins/0.0/ivys/ivy.xml
      /Users/abcdefghk/.sbt/preloaded/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
      http://download.eclipse.org/jgit/maven/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
[error] (*:coursierResolution) coursier.ResolutionException: Encountered 4 error(s) in dependency resolution:
[error]   org.scala-sbt:global-plugins;sbtVersion=0.13;scalaVersion=2.10:0.0:
[error]     not found:
[error]       https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
[error]       https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
[error]       /Users/abcdefghk/.ivy2/local/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
[error]       https://repo1.maven.org/maven2/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
[error]       /Users/abcdefghk/.sbt/preloaded/org.scala-sbt/global-plugins/0.0/ivys/ivy.xml
[error]       /Users/abcdefghk/.sbt/preloaded/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
[error]       http://download.eclipse.org/jgit/maven/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
[error]   org.scala-sbt:global-plugins;sbtVersion=0.13;scalaVersion=2.10:0.0:
[error]     not found:
[error]       https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
[error]       https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
[error]       /Users/abcdefghk/.ivy2/local/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
[error]       https://repo1.maven.org/maven2/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
[error]       /Users/abcdefghk/.sbt/preloaded/org.scala-sbt/global-plugins/0.0/ivys/ivy.xml
[error]       /Users/abcdefghk/.sbt/preloaded/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
[error]       http://download.eclipse.org/jgit/maven/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
[error]   org.scala-sbt:global-plugins;sbtVersion=0.13;scalaVersion=2.10:0.0:
[error]     not found:
[error]       https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
[error]       https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
[error]       /Users/abcdefghk/.ivy2/local/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
[error]       https://repo1.maven.org/maven2/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
[error]       /Users/abcdefghk/.sbt/preloaded/org.scala-sbt/global-plugins/0.0/ivys/ivy.xml
[error]       /Users/abcdefghk/.sbt/preloaded/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
[error]       http://download.eclipse.org/jgit/maven/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
[error]   org.scala-sbt:global-plugins;sbtVersion=0.13;scalaVersion=2.10:0.0:
[error]     not found:
[error]       https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
[error]       https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
[error]       /Users/abcdefghk/.ivy2/local/org.scala-sbt/global-plugins/scala_2.10/sbt_0.13/0.0/ivys/ivy.xml
[error]       https://repo1.maven.org/maven2/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
[error]       /Users/abcdefghk/.sbt/preloaded/org.scala-sbt/global-plugins/0.0/ivys/ivy.xml
[error]       /Users/abcdefghk/.sbt/preloaded/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom
[error]       http://download.eclipse.org/jgit/maven/org/scala-sbt/global-plugins_2.10_0.13/0.0/global-plugins-0.0.pom

**Comment by travisbrown** [comment]
@mahendrapk Hmm, I wonder if this is a coursier thing. Can you reproduce it if you remove the coursier line in `project/plugins.sbt`? Thanks for reporting.

**Comment by mahendrapk** [comment]
Thanks for looking into it. I removed the **- "-addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-RC11")"** 

It still failed with - "coursier.ResolutionException: Encountered 4 error(s) in dependency resolution:"

Attached full error trace.
[circe-sbt-error-trace.txt](https://github.com/circe/circe/files/1285004/circe-sbt-error-trace.txt)

**Comment by alexarchambault** [comment]
Maybe try bumping the coursier version in `project/project/plugins.sbt`.

**Comment by mahendrapk** [comment]
Thanks. 

Bumped up coursier in project/project/plugins.sbt from **"1.0.0-RC1"** to **"1.0.0-RC10"**

sbt project import went past earlier posted errors. For "compile" it errored out as follows:

[error] (java8/*:update) coursier.ResolutionException: 1 not found
[error]     /Users/abcdefgh/.sbt/preloaded/org.scala-lang.modules/scala-parser-combinators_2.12/1.0.4/bundles/scala-parser-combinators_2.12.jar
[error] (optics/*:update) coursier.ResolutionException: 1 not found
[error]     /Users/abcdefgh/.sbt/preloaded/org.scala-lang.modules/scala-parser-combinators_2.12/1.0.4/bundles/scala-parser-combinators_2.12.jar
[error] (streaming/*:update) coursier.ResolutionException: 1 not found
[error]     /Users/abcdefgh/.sbt/preloaded/org.scala-lang.modules/scala-parser-combinators_2.12/1.0.4/bundles/scala-parser-combinators_2.12.jar
[error] (testing/*:update) coursier.ResolutionException: 1 not found
[error]     /Users/abcdefgh/.sbt/preloaded/org.scala-lang.modules/scala-parser-combinators_2.12/1.0.4/bundles/scala-parser-combinators_2.12.jar
[error] (refined/*:update) coursier.ResolutionException: 1 not found
[error]     /Users/abcdefgh/.sbt/preloaded/org.scala-lang.modules/scala-parser-combinators_2.12/1.0.4/bundles/scala-parser-combinators_2.12.jar
[error] (genericExtras/*:update) coursier.ResolutionException: 1 not found
[error]     /Users/abcdefgh/.sbt/preloaded/org.scala-lang.modules/scala-parser-combinators_2.12/1.0.4/bundles/scala-parser-combinators_2.12.jar
[error] (shapes/*:update) coursier.ResolutionException: 1 not found
[error]     /Users/abcdefgh/.sbt/preloaded/org.scala-lang.modules/scala-parser-combinators_2.12/1.0.4/bundles/scala-parser-combinators_2.12.jar
[error] (tests/*:update) coursier.ResolutionException: 1 not found
[error]     /Users/abcdefgh/.sbt/preloaded/org.scala-lang.modules/scala-parser-combinators_2.12/1.0.4/bundles/scala-parser-combinators_2.12.jar
[error] (benchmark/*:update) coursier.ResolutionException: 1 not found
[error]     /Users/abcdefgh/.sbt/preloaded/org.scala-lang.modules/scala-parser-combinators_2.12/1.0.4/bundles/scala-parser-combinators_2.12.jar
[error] (scodec/*:update) coursier.ResolutionException: 1 not found
[error]     /Users/abcdefgh/.sbt/preloaded/org.scala-lang.modules/scala-parser-combinators_2.12/1.0.4/bundles/scala-parser-combinators_2.12.jar
[error] (literal/*:update) coursier.ResolutionException: 1 not found
[error]     /Users/abcdefgh/.sbt/preloaded/org.scala-lang.modules/scala-parser-combinators_2.12/1.0.4/bundles/scala-parser-combinators_2.12.jar
[error] (generic/*:update) coursier.ResolutionException: 1 not found
[error]     /Users/abcdefgh/.sbt/preloaded/org.scala-lang.modules/scala-parser-combinators_2.12/1.0.4/bundles/scala-parser-combinators_2.12.jar
[error] (numbers/*:update) coursier.ResolutionException: 1 not found
[error]     /Users/abcdefgh/.sbt/preloaded/org.scala-lang.modules/scala-parser-combinators_2.12/1.0.4/bundles/scala-parser-combinators_2.12.jar

**Comment by alexarchambault** [comment]
@mahendrapk That should be `RC11`, not `RC10`.
