### ISSUE TITLE
Consider removing split and product methods on decoders

### ISSUE THREAD

**Issue by travisbrown** [circe/circe#760]
`Decoder` has a couple of methods that were inherited from Argonaut that I don't think are widely used (at least I don't remember ever using them or seeing them used):

```scala
def split[B](decodeB: Decoder[B]): Either[HCursor, HCursor] => Decoder.Result[Either[A, B]]
def product[B](decodeB: Decoder[B]): (HCursor, HCursor) => Decoder.Result[(A, B)]
```
I'd like to remove them for a couple of reasons.

The first is that the method name `product` in the Cats world typically suggests the semantics of `Decoder#and` (which I'd like to deprecate as `and` and rename `product`).

The second reason is that these methods are pretty trivial to define yourself: `a.product(b)` is just `a.kleisli *** b.kleisli`, and if Cats's `Choice` had `+++` (I'm not sure why it doesn't) `a.split(b)` would just be `a.kleisli +++ b.kleisli`.

Alternatively we could rename them to free up `product` and be a little more idiomatic (probably something like `split => splitTagged` and `product => split`, although that's obviously confusing as hell and I'm open to alternative suggestions). I'd rather just get them out of the API, though.

**Comment by wedens** [comment]
> if Cats's Choice had +++ (I'm not sure why it doesn't) 

It's defined in [ArrowChoice](https://github.com/typelevel/cats/blob/v1.0.1/core/src/main/scala/cats/arrow/ArrowChoice.scala#L33)

**Comment by travisbrown** [comment]
Done in #798.
