### ISSUE TITLE
[Question] Partial decode when errors are present (ala GraphQL)

### ISSUE THREAD

**Issue by inakianduaga** [circe/circe#779]
The motivation of this issue is to recover as much data as possible from a decode even in the presence of errors. A real use case is having a GraphQL api, and decoding data from a backend: In the current circe implementation, if the backend introduced a breaking change compared to our expected data structure (case classes), the whole circe decoding will fail, as such we will be forced to return an error for that resolver, when maybe in reality only a certain field in the whole backend response is actually broken and we can correctly parse the rest of the data.

The idea would be to follow GraphQL approach to resolution errors (think resolution analogous to decode):

http://facebook.github.io/graphql/October2016/#sec-Errors-and-Non-Nullability

When circe attempts to decode a JSON tree, if there is an error at some node, it would backtrack until the closest parent that has the response wrapped in an Option. Then it would null that parent (i.e `None`, preserving type safety), and add that node to the error tracker so we know about it. The final response would be a `Left` that contains both the error and the decoded json instance.

This can then be easily fed into GraphQL resolvers and returned as a [PartialValue](http://sangria-graphql.org/learn/#actions) so we can provide the user as much data as possible, while retaining knowledge about the errors.

**Comment by eirirlar** [comment]
There's Patchless and similar stuff out there.

**Comment by hamnis** [comment]
Closing in cleanup run, If anyone cares about this, please comment and I'll reopen.
