### ISSUE TITLE
Generic extras encoders with Scalaz tags

### ISSUE THREAD

**Issue by brendanmaguire** [circe/circe#784]
The example code:

```
import scalaz.Tag
import scalaz.@@

import io.circe.Encoder
import io.circe.generic.extras.Configuration
import io.circe.generic.extras.semiauto._


object SimpleSnake extends App {
  sealed trait FooIdTag
  sealed trait BarIdTag

  type FooId = String @@ FooIdTag
  type BarId = String @@ BarIdTag

  case class Simple(
    fooId: FooId,
    barId: BarId
  )

  implicit val customConfig: Configuration = Configuration.default.withSnakeCaseKeys.withDefaults

  implicit val fooIdEncoder: Encoder[FooId] = Encoder.encodeString.contramap(Tag.unwrap)
  implicit val barIdEncoder: Encoder[BarId] = Encoder.encodeString.contramap(Tag.unwrap)

  implicit val simpleEncoder: Encoder[Simple] = deriveEncoder[Simple]
}
```

raises the following compilation error:

```
[error] snake.scala:23: could not find Lazy implicit value of type io.circe.generic.extras.encoding.ConfiguredObjectEncoder[SimpleSnake.Simple]
[error]   implicit val simpleEncoder: Encoder[Simple] = deriveEncoder[Simple]
```

But if I remove one of the attributes in Simple, leaving just one, it works.

I'm not sure if this is a bug or I'm missing something, but it seems strange to me that it works with a single attributes but not multiple.

It works fine with `shapless.tag.@@` instead of `scalaz.@@` also.

**Comment by tarao** [comment]
It looks quite similar to #688 that you have no problem with a single field.  As far as I know, `scalaz.@@` and `shapeless.newtype` do something similar.  I think it's a bug but I have no idea what is going on.

**Comment by brendanmaguire** [comment]
I will close this due to lack of activity. Someone can comment to reopen if required.
