### ISSUE TITLE
Support kebab-case style member name transformation

### ISSUE THREAD

**Issue by tlangs** [circe/circe#789]
It would be nice to handle kebab-case transformations as easily as snake_case transformations are.

```scala
Configuration.default.withSnakeCaseMemberNames
```
is provided, but it would be helpful to also provide
```scala 
Configuration.default.withKebabCaseMemberNames
```

**Comment by travisbrown** [comment]
Done in #790—thanks @tlangs !

**Comment by tlangs** [comment]
Happy to contribute!
