### ISSUE TITLE
extras.semiauto.deriveEnumerationEncoder not work with 'val' field overridden

### ISSUE THREAD

**Issue by cwei-bgl** [circe/circe#792]
Hi, there is an error when I used 'val' field overridden below. I am using circle 0.9.0-M2.

sealed trait SuperType {
  def name: String
}
object SuperType {
  object SubType1 extends SuperType {
    override def name: String = "type1"
    //override val name: String = "type1" //not work when using 'val'
  }
  object SubType2 extends SuperType {
    override def name: String = "type2"
    //override val name: String = "type2" //not work when using 'val'
  }
}

implicit val superTypeEncoder = deriveEnumerationEncoder[SuperType]

I can get around it by using 'def' instead of 'val' at the moment. Thanks.

Cheng

**Comment by travisbrown** [comment]
Thanks for the report!

**Comment by travisbrown** [comment]
The problem here is that all of circe-generic is built on Shapeless's `LabelledGeneric` instances, and Shapeless does not provide instances when the `val` is present:
```scala
sealed trait SuperType { def name: String }
object SuperType {
   object SubType1 extends SuperType { def name: String = "type1" }
   object SubType2 extends SuperType { val name: String = "type2" }
}
```
And then:
```scala
scala> shapeless.LabelledGeneric[SuperType.SubType1.type]
res0: shapeless.LabelledGeneric[SuperType.SubType1.type]{type Repr = shapeless.HNil} = shapeless.LabelledGeneric$$anon$1@3e8417fb

scala> shapeless.LabelledGeneric[SuperType.SubType2.type]
<console>:28: error: could not find implicit value for parameter lgen: shapeless.LabelledGeneric[SuperType.SubType2.type]
       shapeless.LabelledGeneric[SuperType.SubType2.type]
                                ^
```
You might want to open an issue about this on the Shapeless side, and if Shapeless ever starts providing instances in these cases, everything should just work on the circe side.
