### ISSUE TITLE
Json instances from same source are not equal

### ISSUE THREAD

**Issue by NeQuissimus** [circe/circe#793]
I think this is just an inconsistency between `decode` followed by `asJson` and using `parse`.

Basically, I have a class that takes a `String`, decodes it into a case class, validates some values and then returns a `Json` object (for further processing, irrelevant).
I wrote a test against this and encountered what is either a bug or an inconsistency that I was simply not expecting.

It comes down to this code (using circe 0.8.0):

```scala
case class Foo(bar: String, baz: Option[Int])
val s = """{"bar": "Hello World"}"""
Json.eqJson.eqv(decode[Foo](s).right.get.asJson, parse(s).getOrElse(Json.Null))
```

The result will be `false` despite both `Json` objects having been created from the same exact input.
I believe this is similar to #585 except the "workaround" is a custom printer; I am not involving a printer at all in my case (I have non-deterministic field ordering on the original input, so the printer would not help me).

This is what the individual `Json` objects look like:

```scala
@ decode[Foo](s).right.get.asJson 
res16: Json = JObject(
  MapAndVectorJsonObject(Map("baz" -> null, "bar" -> JString("Hello World")), Vector("bar", "baz"))
)

@ parse(s).getOrElse(Json.Null) 
res17: Json = JObject(MapAndVectorJsonObject(Map("bar" -> JString("Hello World")), Vector("bar")))
```

I would think that the `"baz" -> null` in the first `Map` is the issue here...

**Comment by travisbrown** [comment]
In general you can't expect a JSON value to round-trip through decoding, although I agree this case is a little annoying. Here's a less problematic one:

```scala
scala> import io.circe.Json, io.circe.generic.auto._, io.circe.jawn._, io.circe.syntax._
import io.circe.Json
import io.circe.generic.auto._
import io.circe.jawn._
import io.circe.syntax._

scala> import cats.syntax.either._
import cats.syntax.either._

scala> case class Foo(bar: String)
defined class Foo

scala> val doc = """{"bar": "Hello World", "something": "whatever"}"""
doc: String = {"bar": "Hello World", "something": "whatever"}

scala> decode[Foo](doc).right.get.asJson
res0: io.circe.Json =
{
  "bar" : "Hello World"
}

scala> parse(doc).getOrElse(Json.Null)
res1: io.circe.Json =
{
  "bar" : "Hello World",
  "something" : "whatever"
}
```

There are infinitely many JSON values that map to the same `Foo`, so we can't guarantee that parsing and decoding followed by encoding will agree.

In your case there are two JSON values that map to the same `Foo`, which is what makes it feel worse (to me, at least), but I still don't think there's anything we can reasonably do about it.

Does that sound reasonable?

**Comment by NeQuissimus** [comment]
FWIW, this is a complete "workaround" (taken from #585 and friends)

```scala
object JsonHelper {
  import io.circe._

  def canonicalJsonObject(jobj: JsonObject): JsonObject = {
    JsonObject.fromIterable(jobj.toVector.sortBy(_._1).map { case (k, j) => k -> canonicalJson(j) })
  }

  def canonicalJson(j: Json): Json = j.fold[Json](
    jsonNull = Json.Null,
    jsonBoolean = (x: Boolean) => Json.fromBoolean(x),
    jsonNumber = (x: JsonNumber) => Json.fromJsonNumber(x),
    jsonString = (x: String) => Json.fromString(x),
    jsonArray = (x: Vector[Json]) => Json.fromValues(x.map(canonicalJson)),
    jsonObject = (x: JsonObject) => Json.fromJsonObject(canonicalJsonObject(x))
  )

  // https://github.com/circe/circe/issues/793
  def cleanJson(j: Json): Json = {
    val printer = Printer.noSpaces.copy(dropNullKeys = true)
    val noNull = parse(printer.pretty(j)).toOption.get
    canonicalJson(noNull)
  }
}
```

I still disagree with the `Eq` instance returning false :)

**Comment by travisbrown** [comment]
My feeling is that we should have a new canonical equality method that doesn't consider field order or null-valued fields (but that it not be used for either universal equality or the `Eq` instance).

**Comment by NeQuissimus** [comment]
I could see that, as an alternative way of comparing `Json` objects...

**Comment by travisbrown** [comment]
See #797.
