### ISSUE TITLE
default values for fields that do not exist

### ISSUE THREAD

**Issue by antonkulaga** [circe/circe#799]
It is quite common when the web service instead of assigning some default value to the field just does not include it into the JSON output. In many REST APIs about a half of the fields are like that, that is why I have to put a huge amount of Option to my case classes. It will be very useful to allow to assign custom default values to fields in case classes in case if those fields do not exist in the output without the need to write one's own decoder or wrap half of the case class in Options.

**Comment by travisbrown** [comment]
@antonkulaga Does the `useDefaults` configuration in circe-generic-extras work for you?

**Comment by antonkulaga** [comment]
@travisbrown have not tried it yet, it was not in the docs until recently. Will let you know when I will try

**Comment by travisbrown** [comment]
Closing for now, please reopen if `useDefaults` didn't work.
