### ISSUE TITLE
orNull isn't inferred in interpolator

### ISSUE THREAD

**Issue by darkfrog26** [circe/circe#800]
```scala
val name: Option[String] = ...
val emails: Option[List[String]] = ...
json"""
      {
       "name": ${name.orNull},
       "emails": ${emails.orNull}
      }
    """
```

gets the following compile-time error:
`diverging implicit expansion for type io.circe.Encoder[A0] starting with method encodeMapLike in object Encoder`

**Comment by travisbrown** [comment]
Thanks for the report, and sorry I haven't followed up sooner (I did take a look, but didn't get anywhere or have anything to report). Closing but let's track this in #881.
