### ISSUE TITLE
Automatic derivation fails for List in 0.9.0

### ISSUE THREAD

**Issue by ochrons** [circe/circe#819]
The changes in codec macro derivation in 0.9.0 breaks when using `List` and its `::` class.

Error introduced in https://github.com/circe/circe/commit/5193b5b8bcc3910535d036f09adee259493c7cb8

For example this fails to compile:
```scala
import io.circe._, io.circe.generic.auto._, io.circe.parser._, io.circe.syntax._

sealed trait Foo
case class Bar(xs: List[String]) extends Foo
case class Qux(i: Int, d: Option[Double]) extends Foo

val foo: Foo = Qux(13, Some(14.0))

val json = foo.asJson.noSpaces
```
with
`ERROR: requirement failed: circeGenericInrBindingFor:: is not a valid identifier`

**Comment by ochrons** [comment]
This only happens with full auto derivation, semiauto and JsonCodec work fine.

**Comment by travisbrown** [comment]
@ochrons Thanks again for the report. This seems to be Scala.js-specific, and I'm guessing it's related to this [Scala.js issue](https://github.com/scala-js/scala-js/issues/1790), which is kind of frustrating, but the effect is bad enough that I think we should work around it here. I don't think I'll have time this morning, but I'll publish an 0.9.1 with a fix as soon as possible.

**Comment by BenFradet** [comment]
Is is just a matter of turning `::` in the label into something alphanumeric (e.g. `Cons`)? If so happy to open a PR.

**Comment by BenFradet** [comment]
I tried the above without success, at least at runtime, compiling went fine.

@travisbrown any indication on how to proceed?

**Comment by sjrd** [comment]
When you do `TermName(s"circeGenericInrBindingFor$label")`, you should call `.encodedName` on it to encode all invalid characters the same way scalac does. Same thing everywhere you construct `Name`s out of arbitrary strings.

**Comment by BenFradet** [comment]
@sjrd cool thanks, I'll try that out.
