### ISSUE TITLE
AbstractMethodError when parsing

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [circe/circe#823]
I'm using circe 0.9.0 inside SBT 0.13.x code and Scala 2.10.

```
projectDependencies ++= 
	Seq(
		"io.circe" %% "circe-core",
		"io.circe" %% "circe-parser",
		"io.circe" %% "circe-optics"
	).map(_ % "0.9.0")
```
This is my code:
```
val json = "{.....}"
val result = parse(json)
```
and it throws an exception:
```
java.lang.AbstractMethodError: io.circe.jawn.CirceSupportParser$$anon$1$$anon$4.add(Ljava/lang/String;)V
```
It this a bug or am I doing something wrong?

**Comment by travisbrown** [comment]
It seems likely that the issue here is that you have another dependency that's transitively pulling in a different version of either circe-jawn or Jawn itself. Is this possible?

**Comment by DavidPerezIngeniero** [comment]
Thanks for the answer.  I'm using circe for SBT code utility and I use circe not in my projects dependencies `./build.sbt`, but in `./project/build.sbt`.

I have few dependencies there.
In my main SBT file (`./build.sbt`), I know other JSON parsers are used.

I'm sure any subproject doesn't use `circe`.
I've run the dependenciesGraph task, and I don't see any `jawn`.

**Comment by DavidPerezIngeniero** [comment]
In the interactive `consoleProject` of my project, I can see that Jawn is in the class path:
```
scala> Class.forName("jawn.AsyncParser")
res0: Class[_] = class jawn.AsyncParser
```

In addition, I can see that in the directory `~/.sbt/boot/scala-2.10.6/org.scala-sbt/sbt/0.13.16/` I have:
- jawn-parser_2.10-0.6.0.jar

It is the only jawn*.jar that exists.

**Comment by DavidPerezIngeniero** [comment]
Modified my `project/build.sbt` in this way:
```
projectDependencies ++= Seq(
	"org.spire-math" %% "jawn-parser" % "0.11.0",
	"org.spire-math" %% "jawn-ast" % "0.11.0") ++
	Seq(
		"io.circe" %% "circe-core",
		"io.circe" %% "circe-parser",
		"io.circe" %% "circe-optics"
	).map(_ % "0.9.0")
```

but I continue to experience the same problem. :-(

**Comment by Timunas** [comment]
I'm having exactly the same problem. Any progress on this?

**Comment by WassTrifi** [comment]
your are probably using an sbt plugin as dependency in your project.
`jawn-parser_2.10-0.6.0.jar` is added to the classPath when the sbtPlugin  setting is enabled  `sbtPlugin := true`. This is a dependency of `json4s` library ...
To fix this conflict you can override the old version of  `jawn-parser` in your `build.sbt`: 

```scala
dependencyOverrides ++= Set("org.spire-math" % "jawn-parser_2.11" % "0.11.1")
```

you can check loaded dependencies  with the sbt command: 
```
> show update 
```

**Comment by joan38** [comment]
I get this in SBT `1.2.3` and circe `0.10.0` and @WassTrifi's fix is not working :(

**Comment by travisbrown** [comment]
Closing this as a "multiple Jawns / wrong Jawn on the classpath" issue, please reopen if it's something else.

**Comment by leobenkel** [comment]
What was the fix here ? I am encountering the same issue. Trying to add `circe` to my sbt plugin.

**Comment by travisbrown** [comment]
@leobenkel This should work fine with the latest circe versions, since they depend on Jawn versions that have moved the package to `org.typelevel.jawn`. Otherwise I think the workaround is to use circe-jackson instead of circe-jawn or circe-parser.

**Comment by leobenkel** [comment]
I have circe `0.11.1` in my build.sbt :

```
  "io.circe"       %% "circe-core"    % circeVersion,
  "io.circe"       %% "circe-generic" % circeVersion,
  "io.circe"       %% "circe-parser"  % circeVersion
```
But I still get 
```
[info] [error] java.lang.AbstractMethodError: Method io/circe/jawn/CirceSupportParser$.facade()Ljawn/Facade; is abstract
```

How do I need to modify my `build.sbt` to not use `circle-jawn` ?
