### ISSUE TITLE
Make ScalaFiddle-powered site publish

### ISSUE THREAD

**Issue by travisbrown** [circe/circe#831]
ScalaFiddle-ification got merged in #820 / #830 (thanks @ochrons!), but when I try to update the Pages site I get [this error](https://help.github.com/articles/page-build-failed-unknown-tag-error/):

> The page build failed for the `gh-pages` branch with the following error:
> The tag `scalafiddle` on line 29 in `quickstart.md` is not a recognized Liquid tag. For more information, see https://help.github.com/articles/page-build-failed-unknown-tag-error/.

GitHub suggests the following:

> Plugins are a common source of unrecognized tags. Since GitHub doesn't support most plugins, a common workaround is to build locally and include the results in the Pages repository. 

…which sounds kind of miserable. If someone has a better way to use ScalaFiddle with GH Pages I'd appreciate any ideas.

**Comment by ochrons** [comment]
I think you just have to change this setting `ghpagesNoJekyll := true` to disable Markdown processing on the github side. sbt-microsites has already fully generated the HTML, but there is that one `quickstart.md` still hanging around due to it being used within the main doc page.

**Comment by travisbrown** [comment]
Fixed in #835.
