### ISSUE TITLE
how to make JSON decoding throw an error for superfluous elements in JSON input

### ISSUE THREAD

**Issue by hansschl** [circe/circe#848]
Hi!
How can I make the Circe JSON decoding stricter such that whenever it encounters an element (in the JSON input string) that is _not_ in the target class X (`decode[X](string)`) it throws an error. Currently, with the default settings (circe 0.9.1), superfluous elements are silently ignored. 
For me (in my application) superfluous elements are an input error, so I need the error to be thrown by circe.
Thanks!

**Comment by travisbrown** [comment]
@hansschl #375 provides functionality that makes it possible to do this kind of thing fairly conveniently, but we don't currently have this supported by generic derivation, so you do have write out the instances yourself. It's something I'd like to support in circe-derivation someday, but hasn't been a priority for me there so far.

**Comment by hansschl** [comment]
@travisbrown #375 looks good and convenient -- thank you!
Unfortunately I don't figure how to combine that approach with Option fields. According to #708 Option's (together with #375) should work out-of-the-box, but they don't yet. Hence I can not use #375.

**Comment by travisbrown** [comment]
@hansschl Can you give an example?

**Comment by hansschl** [comment]
@travisbrown Sure: I've tried the #708 example (with circe 0.9.1).
In that example, decoding should work for `good` and `shouldBeGood`, although it does only for `good`.

**Comment by kevinmeredith** [comment]
> For me (in my application) superfluous elements are an input error

Could you please say more? I'm interested to understand how superfluous elements should result in an error for your application.

**Comment by daddykotex** [comment]
I saw two reasons for this.

1.  Jackson supports this so this could be to be retrocompatible
2.  A specific element of the json is missing because there's a typo in the payload

For point 2, consider this example:

Application is expecting the following payload (this is typescript): 
```typescript
{
   key: string,
   elements: Array<string> | null,
}
```

The user sends this:
```json
{
   "key": "my-new-thing",
   "elenents": [ "v1", "v2" ]
}
```
At this point the user did not receive an error, because the `elements` part of the payload is optional and `elenents` which is not a valid part of the payload is just discarded. Of course this is a user error, but if the user does not get an error, he might be frustrated not to see his elements in the UI (or wherever he should see them)

**Comment by kevinmeredith** [comment]
I ask the following to learn more, not claim a solution by any means. 

Why can't you, per your example, make `elements` a required field then?

**Comment by daddykotex** [comment]
> I ask the following to learn more, not claim a solution by any means.

yeah, I answered just to share what I knew 😃 

> Why can't you, per your example, make elements a required field then?

Well, that's another perfectly valid solution in my opinion. One reason you might not be able to do that is that you have to support older clients, and `elements` is something new in the payload.

**Comment by hansschl** [comment]
@kevinmeredith Indeed the above is what I had in mind: that there are (intentional) optional elements that could be misspelled in an input JSON document. And I want to make sure that my parser consumes everything that is in the document. Currently I don't see a way to have Circe throw an error in case there is some information left in the input document that is not parsed and converted to my case class instances.

**Comment by travisbrown** [comment]
I think that between #375, #1117, and #1148 we can consider this closable. Please re-open if you have use cases that aren't currently supported.
