### ISSUE TITLE
ErrorAccumulatingUnmarshaller from akka-http-json lib no longer applying validations in 0.9.2

### ISSUE THREAD

**Issue by yurique** [circe/circe#865]
We have some Decoders with attached validations like this:

```
implicit val decodeSomething = deriveDecoder[Something].validate(..., ...)
```

And we use this for our akka-http routes (https://github.com/hseeberger/akka-http-json):
```
trait AkkaHttpCirceSupport extends BaseCirceSupport with ErrorAccumulatingUnmarshaller
```

And after updating to 0.9.2 that validation is no longer applied.

Switching to `FailFastCirceSupport` makes the validation run again. It's probably related to https://github.com/circe/circe/pull/838/files, but I'm not sure.

Reverting to `0.9.1` makes `ErrorAccumulatingUnmarshaller` run validations again.

I put together a couple of tests showing this here: https://github.com/yurique/akka-http-json-fail/tree/validation-fail (validation-fail branch)

`sbt test` fails in one of the cases; changing circe to `v0.9.1` makes them pass.

I'm not sure if this is related to circe or to `akka-http-json` lib. 

/cc @hseeberger

**Comment by mwielocha** [comment]
+1

**Comment by travisbrown** [comment]
Confirmed—this slipped by in #838. Publishing a fix this afternoon.

**Comment by travisbrown** [comment]
Okay, [0.9.3](https://github.com/circe/circe/releases/tag/v0.9.3) is on its way to Maven Central. Thanks much for the report, and apologies for the inconvenience (I promise to be more vigilant about code review in the future!).

**Comment by mwielocha** [comment]
Thanks so much!

**Comment by yurique** [comment]
Thank you!
