### ISSUE TITLE
Support encoding effects, and decoding effects beyond Either..?

### ISSUE THREAD

**Issue by benhutchison** [circe/circe#877]
The general forms of a transformation of a type `A` to/from Json is:
```
trait Encoder[[M[_], A]] { def apply(a: A): M[Json] }

trait Decoder[M[_], A] { def apply(json: Json): M[A] }
```

`M` denotes the effects that the translation can have. In circe today, the possible effects are hardcoded; for decode, `M` = `Either[Error, ?]`  and for encode `M` = `Id` (the empty effect).

I recently came across a genuine "in-the-wild" use case where I needed other effects present, and so couldn't use Circe. Here's the story..

I've been maintaining a json serialization library [Prickle](https://github.com/benhutchison/prickle) for some time. I was evaluating whether I could deprecate it and consolidate onto Circe. But there's a key feature of Prickle which would need to be reimplemented over Circe, and that is its [optimization of shared objects in a serialized data graph](https://github.com/benhutchison/prickle#support-for-shared-objects).

Optimizing shared/repeating data in the traversal involves keeping track of whether the Encoder/Decoder has seen them before. That is, both encode and decode operations become a _stateful_. We know that stateful computations can be well represented using state monads, eg a `State[Encoding, ?]` effect.

However, the present design of Circe doesn't allow library users to "BYO effects". This is turn limits it's ability to scale to more complex and tricky use cases like the one described above.

OTOH, I appreciate that for many users, the simplicity of a narrower, more easily understood interface with pre-defined effects is ideal for their needs.

The above `Encoder`/`Decoder` interfaces generalize the existing interfaces. If there is ever a major redesign, or "2.0", of Circe, please consider adopting the more general interfaces as base traits, and exposing the current interfaces as sub-traits.

**Comment by nartamonov** [comment]
It also helps in cases when we are decoding some domain object with the help of a smart constructor with validation logic inside, where validation is represented by `cats.data.Validated` effect or `ZIO` or something else, for example:

```scala
import zio.ZIO

case object UserProfile private (birthdate: LocalDate)

object UserProfile {
  def apply(birthdate: LocalDate): ZIO[Clock,ValidationError,UserProfile] = {
    // ... check that user age is more than 18 years.
  }

  // Currently it is impossible to write such decoder using smart constructor
  implicit val decodeUserProfile: Decoder[UserProfile] = ???
}
```

I have a similar problem in my current project and don't know how to solve it.

**Comment by okouyad** [comment]
What is the status of this ?

**Comment by benhutchison** [comment]
AFAICT, it requires a ground-up rewrite of Circe to fix. 

By coupling to a concrete effect type `Either` throughout the Circe API, rather than an abstract interface (like `ApplicativeError`/`MonadError`), there's no space for other effects in the decode operation.

**Comment by hamnis** [comment]
Closing in cleanup run, If anyone cares about this, please comment and I'll reopen.

**Comment by vkorenev** [comment]
I have another use case for `trait Encoder[[M[_], A]] { def apply(a: A): M[Json] }`. I'd like to perform some IO when encoding.
For example, I have some case classes where one or fields contains User ID (Long). For each occurrence of a user, the JSON should look like
```json
"user" : {
  "id" : 1234,
  "name" : "John Doe"
}
```
where name is looked up in LDAP.
My preferrable solution would be writing a custom encoder for some `UserId` type (newtype wrapper around `Long`) where I can do some IO.
