### ISSUE TITLE
[generic extras] Default value of Option type will be ignored

### ISSUE THREAD

**Issue by ryamaguchi0220** [circe/circe#878]
Hi, The following code returns `Right(Foo(a, None))`　
but, I expect `Right(Foo(a, Some(0)))`

Is this a bug, or am I doing something wrong?

```
import io.circe.generic.extras.auto._
import io.circe.generic.extras.Configuration

implicit val customConfig: Configuration = Configuration.default.withDefaults

case class Foo(a: String = "a", b: Option[Int] = Some(0))
io.circe.parser.decode[Foo]("{}")
```

My dependencies.
```
"io.circe" %% "circe-core" % "0.9.3"
"io.circe" %% "circe-generic" % "0.9.3"
"io.circe" %% "circe-parser" % "0.9.3"
"io.circe" %% "circe-generic-extras" % "0.9.3"
```

Thanks.

**Comment by ryamaguchi0220** [comment]
I found out that if use `io.circe.Decoder#decodeJson` instead of `io.circe.parser.decode`, default value of Option type won't be ignored.
```
import io.circe.generic.extras.auto._
import io.circe.generic.extras.Configuration
import io.circe.{ Decoder, Json }

implicit val customConfig: Configuration = Configuration.default.withDefaults
case class Foo(a: String = "a", b: Option[Int] = Some(0))
val decoder = implicitly[Decoder[Foo]]
decoder.decodeJson(Json.fromString("{}"))
```

**Comment by travisbrown** [comment]
For the record, I think I would probably consider this a bug, but it's a somewhat complex one, because the default is used when _decoding a member fails_, but decoding an optional member that's not there doesn't fail. I'd like to see a fix for this, but I'm not sure it'll happen before 0.10.0.

**Comment by ryamaguchi0220** [comment]
This can be avoided by defining a custom decoder. However, if this is fixed it will be helpful not to need to define a custom decoder.

**Comment by niij** [comment]
This is an issue for me as well. Is it possible to add an option to `Configuration` like `withDefaultsForOptions`?
