### ISSUE TITLE
Marshal Akka HTTP RequestEntity with human-readable newlines

### ISSUE THREAD

**Issue by evbo** [circe/circe#879]
Hi,

I am trying to use json strings with newlines and am marshalling them for a client POST request using this (un)marshaller as follows: http://codegists.com/code/akka-http-circe-example/

This works, but I don't like how I have to escape newlines:
```
val query = "{\n getFruit(id: 1) {\n name\n }\n }\n"
val entity = Marshal(Query(query)).to[RequestEntity]
```

I'd like to instead marshal with the following json that supports literal newlines:

```
val query = """{
  getFruit(id: 1) {
    name
  }
}"""
val entity = Marshal(Query(query)).to[RequestEntity]
```

but this results in an invalid json string (with `//#` values for each literal newline):
```
println(Query(query)).asJson.pretty(Printer.noSpaces))
query: String = 
"{ //1
getFruit(id: 1) {//2
family//3
}//4
}//5"
```

Is there a setting for the printer to replace newline characters with escaped newlines without those line numbers included? My marshal currently uses `Printer.noSpaces`.

**Comment by evbo** [comment]
This is a work around:
```
val query = """{
  getFruit(id: 1) {
    name
  }
}""".replaceAll("//\\d+", "")
```

**Comment by hamnis** [comment]
Closing in cleanup run, If anyone cares about this, please comment and I'll reopen.
