### ISSUE TITLE
Support for ScalaJS 1.0

### ISSUE THREAD

**Issue by randm-ch** [circe/circe#898]
Hi! ScalaJS 1.0.0-M3 is out [since Febuary](https://www.scala-js.org/news/2018/02/01/announcing-scalajs-1.0.0-M3). Are there any plans yet to provide a build for this version? I assume this depends on [cats#2195](https://github.com/typelevel/cats/issues/2195)? Thanks!

**Comment by travisbrown** [comment]
Right, my policy is to support all Scala versions that Cats cross-builds for within roughly a week of the Cats release.

**Comment by travisbrown** [comment]
I'm going to close these issues that are blocked by dependencies (since they aren't actionable and have less value as reminders now that Scala Steward keeps us updated).
