### ISSUE TITLE
Support for Quill-like renaming 

### ISSUE THREAD

**Issue by letalvoj** [circe/circe#908]
We map huge jsons to case classes. We have like 15 fields there. Unfortunatelly they come from rather dirty source with _mostly_ snake case named fields. Sometimes there are special characeters and therefore we need to rename a field or two.

Unfortunatelly renaming in circe is pain. It'd be nice if there was a [quill-like custom schema](http://getquill.io/#quotation-schema-schema-customization) functionality implemented.

```scala
case class Event(logTime:Long, machineId:Option[String], ...)

object Event{
  implicit eventDecoder = deriveDecoder[Event](_.logTime -> "_log_time_ms", _.machineId -> "srcMachineId")
}
```

That'd be extremely helpful.

**Comment by letalvoj** [comment]
I have a hard time googling it then the top results are like [this obscure](https://stackoverflow.com/questions/40306107/rename-json-fields-with-circe) and the [official documentation](https://circe.github.io/circe/) does not tell much.

Well, after you replied I found some mentiones in [release notes](https://github.com/circe/circe-derivation/releases). I'll try to dig deeper.

If you could please point me to some more complete source of info it'd be helpful. But otherwise please close this issue.

**Comment by letalvoj** [comment]
Again thanks for the reply. You probably can close the issue.

**Comment by letalvoj** [comment]
Well, your [design principles](https://github.com/circe/circe/blob/master/DESIGN.md) quotes
> programs should be invariant under rename refactoring ...

Which does not hold for the `String => String` approach. The best I can get is
```scala
deriveEncoder[Event](replaceWith(
  nameOf[Event](_.id) -> "_event_id"
  nameOf[Event](_.eventType) -> "_type_id"
))
```

which is not really nice and it's pain to write. Also, imagine that the class name was longer (which it actually is), like `SomeMoreVerboseEvent`.

**Comment by hamnis** [comment]
Closing in cleanup run, If anyone cares about this, please comment and I'll reopen.
