### ISSUE TITLE
Incorrect example in Semi-automatic Derivation

### ISSUE THREAD

**Issue by se7entyse7en** [circe/circe#911]
The example shown in Semi-automatic Derivation page when using `forProductN` helper methods is incorrect (https://circe.github.io/circe/codecs/semiauto-derivation.html#forproductn-helper-methods). The name of the object must be the same of the case class. I think that this might be obvious for experienced scala users, but as a newbie I spent some time before understanding why it wasn't working.

**Comment by travisbrown** [comment]
Ah, good catch! This version will work, if you import `UserCodec._` explicitly, and it has some uses (e.g. if you don't have a circe dependency in the module where you define your case class), but I definitely agree that in this context it's just confusing.

Want to open a PR to change the object name, @se7entyse7en?

**Comment by se7entyse7en** [comment]
@travisbrown yup, I've just opened the PR. :)
