### ISSUE TITLE
Auto derivation not work with newtype(tagged type)

### ISSUE THREAD

**Issue by jilen** [circe/circe#919]
[Example](https://scastie.scala-lang.org/556BEk9DTieylhbwa6ELBg)

```scala
type &[A, B] = A with B



type GE10

def tagged[A, B](a: A) = a.asInstanceOf[A & B]

case class Foo(i: Int & GE10)

implicit def decodeGE10[A: Decoder](implicit N: Numeric[A]): Decoder[A & GE10] = new Decoder[A & GE10]{
  def apply(c: HCursor) = {
    c.as[A].ensure(DecodingFailure(s"not >= 10", c.history))(i => N.gteq(i, N.fromInt(10))).map(i => tagged[A, GE10](i))
  }
}


implicitly[Decoder[Int & GE10]] // Ok


implicitly[Decoder[Foo]] // compile failed

```

Above example not working

**Comment by felixbr** [comment]
It works if you provide
```implicit val decodeFoo: Decoder[Foo] = Decoder[Int & GE10].map(Foo.apply)``` 
I assume you want it to work with `deriveDecoder` though, which seems to fail.

**Comment by hamnis** [comment]
Closing in cleanup run, If anyone cares about this, please comment and I'll reopen.
