### ISSUE TITLE
union or/and diff method for JsonObject

### ISSUE THREAD

**Issue by asoltysik** [circe/circe#933]
```scala
final def union(that: JsonObject): JsonObject = JsonObject.fromMap(this.toMap ++ that.toMap)

final def diff(that: JsonObject): JsonObject = JsonObject.fromMap(this.toMap -- that.toMap.keySet)
```

Would these be useful addition or unnecessary? `union` would be probably more useful/common. Names for familiarity with std, although `merge` could be also a good name for `union`.

**Comment by sanjivsahayamrea** [comment]
With `union` and nested key/values won't the `that.toMap` key/values overwrite the key/values from `this.toMap` ? 

Ideally `JsonObject` needs a `deepMerge` function similar to `Json`

**Comment by hamnis** [comment]
Closing in cleanup run, If anyone cares about this, please comment and I'll reopen.
