### ISSUE TITLE
Status of macro paradise in Scala 2.13 series

### ISSUE THREAD

**Issue by SethTisue** [circe/circe#975]
the [circe 0.10 release notes](https://github.com/circe/circe/releases/tag/v0.10.0) say:

> The Macro Paradise compiler plugin is not currently available for 2.13.0-M4, which means that @JsonCodec and the related annotations in circe-generic-extras will not work on 2.13. When (or if) the plugin is published for 2.13.0-M4 it should work as expected with this release.

Macro paradise was folded into scalac itself as of 2.13.0-M4; see https://github.com/scala/scala/releases/tag/v2.13.0-M4 ("Instead of using the plugin, macro annotations can be enabled with the `-Ymacro-annotations` flag") and https://github.com/scala/scala/pull/6606

**Comment by travisbrown** [comment]
Ah, thanks! Will try this for the tests I disabled.

**Comment by SethTisue** [comment]
since you were able to publish for M5, I assume you sorted this out, and perhaps the ticket can be closed?
