### ISSUE TITLE
JavaTimeDecoders/JavaTimeEncoders are package-private

### ISSUE THREAD

**Issue by adamw** [circe/circe#976]
After updating to 0.10.0, there's no longer a `TimeInstances` trait (in `circe-java8`). This seems to be replaced by `JavaTimeDecoders` and `JavaTimeEncoders`. However, they are now package-private.

I used to have a single `Json` object which extended `AutoDerivation`, `TimeInstaces` and provided some custom encoders for my application-specific types. That way, all I needed to do to use json was a single `import Json._`.

Maybe it would be possible to make those non-package-private again?

**Comment by travisbrown** [comment]
Hmm, yes, will get a fix together—thanks.

**Comment by adamw** [comment]
Awesome, thanks! :)

**Comment by adamw** [comment]
If it would make things easier I can prepare a (rather simple) PR that would change the visibility, unless you have some other design in mind? (I could attempt to work on this as well :) )

**Comment by travisbrown** [comment]
@adamw I'd been thinking of splitting circe-java8 into its own repo but hadn't gotten around to it yet, and now I'm not sure that's the best idea. If you want to open a PR I'd appreciate it, but otherwise will get to it this week.

**Comment by adamw** [comment]
I did a super-simple PR (https://github.com/circe/circe/pull/995), let me know if it's enough :)

**Comment by travisbrown** [comment]
Fixed in #995.
