### ISSUE TITLE
Instances for scala.concurrent.Duration/FiniteDuration

### ISSUE THREAD

**Issue by LukaJCB** [circe/circe#977]
It would be nice to be able to encode and decode Durations with Circe, was it a conscious design choice to not include these, or would you accept a PR to add these? :)

**Comment by travisbrown** [comment]
For the most part I've avoided including instances in core when there's not a relatively uncontroversial single encoding, but I agree that these would be useful, so yes (unless anyone else has serious objections).

**Comment by fsvehla** [comment]
Would those be nanos or ISO-8601 periods?
