### ISSUE TITLE
Option[Seq[Int]] encoded as `iterable`

### ISSUE THREAD

**Issue by jilen** [circe/circe#989]
+ scala : 2.12.7
+ circe: 0.10.0
+ example repo : https://github.com/jilen/circe-option-error
+ travis build: https://travis-ci.org/jilen/circe-option-error/jobs/442594794

```scala
import io.circe.generic.auto._
import io.circe.{Encoder => CE, Decoder => DE, _}

case class Foo(
  bar: Option[Seq[Int]] = None
)

object Main {
  def main(args: Array[String]): Unit = {
    val e = implicitly[CE[Option[Foo]]]
    val r = Foo()
    println(e.apply(Some(r)).noSpaces)
  }
}

```

Above code print
```
{"bar":[]}

```

Actually it should be
```
{"bar":null}

```

Seems `Encoder[Optio[Seq[Int]]` was inferred as `ecndoeIterable` due to `Option.option2Iterable` conversation.

**Comment by abdheshkumar** [comment]
It is an issue with auto macro
```scala
import io.circe._
import io.circe.generic.auto._

case class Foo(
                bar: Option[Seq[Long]] = None
              )

object CirceJsonApp {

  def main(args: Array[String]): Unit = {

    val e = implicitly[Encoder[Option[Foo]]]
    val r = Foo(bar = None)
    println(e.apply(Some(r)).noSpaces)
  }
}
```
Above code produce the result:
`[{"bar":null}]`
if you move Foo inside object CirceJsonApp then result would be `{"bar":null}`

It will work fine you use semiauto
```scala
import io.circe._
//import io.circe.generic.auto._
import io.circe.generic.semiauto._

case class Foo(bar: Option[Seq[Long]] = None)

object Foo {
  implicit val d = deriveEncoder[Foo]
}

object CirceJsonApp {

  def main(args: Array[String]): Unit = {

    val e = implicitly[Encoder[Option[Foo]]]
    val r = Foo(bar = None)
    println(e.apply(Some(r)).noSpaces)
  }
}
```
It produce result {"bar":null} which is expected.

**Comment by travisbrown** [comment]
This is a weird one. I can confirm that the following test fails on 2.12.8 with circe 0.12.0-M2:
```scala
import io.circe.generic.auto._, io.circe.syntax._  

case class Foo(bar: Option[Seq[Long]] = None)

object FooTestDefs {
  val foo = Foo(bar = None)
  val str = Option(foo).asJson.noSpaces
}

import org.scalatest._

class FooSpec extends FlatSpec with Matchers {
  "circe" should "encode opt" in {
    FooTestDefs.str should equal("""{"bar":null}""")
  }
}
```

But even minor rearrangements can make it pass, pasting the first part into the REPL produces the expected output, etc.

More importantly, the tests pass unaltered with 0.12.0-M2 on 2.13.0-RC2. If that's still the case with the eventual 0.12.0 release on 2.13.0, I'll probably close this issue.

**Comment by travisbrown** [comment]
Just confirmed that I can reproduce the failure with circe 0.12.0-M3 on 2.12.8 but not on 2.13.0, so I'm closing the issue as an upstream compiler problem (probably related to the divergence checker) that's been resolved.
